### ISSUE TITLE
Front/Formulaire de candidature : ajouter le champ "domaine professionnel" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1012]
Objectif : Donner la possibilité aux candidats postulant à une offre de renseigner leur spécialisation (soit le domaine professionnel de référence/dans lequel il exerce actuellement). 

Aujourd'hui, la possibilité existe seulement pour les candidats soumettant une candidature spontanée. Il serait opportun que tous les candidats qu'ils postulent spontanément ou à une offre d'emploi puissent renseigner cette information, cela permettra par ailleurs d'avoir un profil + complet. 

Champ non obligatoire.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1018.osc-fr1.scalingo.io/

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel au niveau du front. 
En revanche en back, la donnée n'apparaît au niveau de l'onglet profil de la carte candidat. (cf. écran). 
![Capture d’écran 2021-06-30 à 15.22.02.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/8a2a7c69-222c-4f20-893c-600a8dd92d04)

Et lorsque l'on filtre le vivier par domaine professionnel (menu déroulant), la carte candidat n'apparaît pas.

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd Je viens d'effectuer le test mais le domaine professionnel n'apparaît toujours pas en back. 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/a0b8e56e-d788-4d1f-a42c-96e94e28fe48)

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/9598011d-407d-42c3-9417-db8dac15ae51)

Lien URL de la carte candidat : https://erecrutement-cvd-staging-pr1018.osc-fr1.scalingo.io/admin/offresdemploi/responsable-achat-d-infrastructures-f-h-fb43a7b7-a1b2-4922-b5df-63941bfd71f7/candidatures/28f11705-ebea-4b54-a3a4-c2f160152c11

**Comment by btrd** [comment]
Je l'ai affiché sur la staging en fait

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel !
