### ISSUE TITLE
Vivier / Carte candidat : pouvoir visualiser le CV d'un candidat qui n'a pas postulé à une de mes offres d'emploi

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1015]
Règles : Le vivier centralise l'ensemble des cartes candidats de l'outil. Lorsqu'un employeur clique sur une carte candidat, il doit pouvoir visualiser le CV du candidat et son historique de candidature. L'employeur a ensuite seulement accès aux candidatures relatives à ses offres. 

Comportement constaté : l'employeur n'a pas de visibilité sur le CV d'un candidat qui n'a pas postulé à l'une de ses offres d'emploi. 

Comportement souhaité : l'employeur doit pouvoir visualiser l'ensemble des CV des cartes candidats du vivier. 

Testé en pré-prod et en prod 
Dans la vidéo copie d'écran : Omar Test est un candidat qui a postulé à l'une de mes offres d'emploi et Léo Fouali non. 

https://user-images.githubusercontent.com/58481185/123284135-4f330680-d50c-11eb-9d33-cb8fbe951abf.mov

**Comment by btrd** [comment]
C'est corrigé !

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel en staging avec le rôle employeur, merci !
