### ISSUE TITLE
Vivier / Carte candidat : les employeurs doivent pouvoir envoyer une offre d'emploi

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1016]
Comportement constaté : seul le BANT a la possibilité d'envoyer une offre d'emploi à un candidat qui a accepté de recevoir des nouvelles offres d'emploi à son inscription sur le site

Comportement souhaité : les employeurs doivent aussi avoir la possibilité d'envoyer une offre d'emploi à un candidat qui a accepté de recevoir des nouvelles offres d'emploi à son inscription sur le site

**Comment by btrd** [comment]
Je viens pourtant de le faire avec un compte employeur

**Comment by mch2608** [comment]
test réalisé en staging 

https://user-images.githubusercontent.com/58481185/123432912-2faee300-d5cb-11eb-8993-7145989cb8ae.mov

**Comment by btrd** [comment]
Corrigé

**Comment by Grainedepaillette** [comment]
@btrd En staging, on visualise effectivement l'action "envoyer une offre" avec le rôle employeur MAIS lorsque l'on saisit une référence (d'une offre créée par l'employeur et que l'on clique sur le bouton "envoyer" alors on a un message d'erreur qui apparaît (cf. écran). 

![Capture d’écran 2021-06-30 à 15.52.21.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/308f5baa-edae-4135-80d4-86f93963c0a1)

**Comment by btrd** [comment]
C'est corrigé
