### ISSUE TITLE
Vivier : pouvoir ajouter des candidats sélectionnés avec le système à cocher dans une liste candidat

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1017]
test réalisé en pré-prod et en prod

Comportement constaté : 
- un employeur sélectionne un ou plusieurs candidat(s) à partir du système à cocher
- il sélectionne ensuite une liste candidat dans le menu déroulant "Ajouter à une liste candidat" 
- il clique sur le bouton "Ajouter" mais l'opération ne fonctionne pas 

Comportement souhaité : lorsque l'employeur clique sur le bouton "Ajouter", les candidats sélectionnés par le système de cases à cocher sont affectés à la liste candidat sélectionnée dans le menu déroulant 

https://user-images.githubusercontent.com/58481185/123288088-88b94100-d50f-11eb-83cd-72e7ad3c9355.mov

**Comment by btrd** [comment]
C'est corrigé !

**Comment by mch2608** [comment]
Ça fonctionne en staging, merci !
