### ISSUE TITLE
Améliorer les pièces jointes dans les emails

### ISSUE THREAD

**Issue by btrd** [betagouv/civilsdeladefense#1029]
- Gérer les pièces jointes envoyer par emails
- Gérer plusieurs pièces jointes

Suite du ticket https://github.com/betagouv/civilsdeladefense/issues/471

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1030.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Après test sur l'environnement : 

Côté envoi par le recruteur : 
- Envoi d'un courriel + 1 P.J en back à l'attention du candidat : réception via l'espace candidat + visualisation P.J ET depuis la messagerie perso du candidat = Opérationnel 

- Envoi d'un courriel + 2 P.J en back à l'attention du candidat : pas possible en back, lorsque l'on souhait téléverser plusieurs pièces cela écrase la précédente. donc on ne peut pas envoyer plusieurs P.J avec 1 seul courriel 

Côté envoi par le candidat : 
- - Envoi d'un courriel + 1 P.J via l'espace candidat à l'attention du recruteur : réception via l'espace recruteur + téléchargement P.J + visualisation P.J = Opérationnel 

- Envoi d'un courriel + 2 P.J  via l'espace candidat à l'attention du recruteur :  lorsque l'on souhait téléverser plusieurs pièces cela écrase la précédente. donc on ne peut pas envoyer plusieurs P.J avec 1 seul courriel

**Comment by btrd** [comment]
>  lorsque l'on souhait téléverser plusieurs pièces cela écrase la précédente

Il faut utiliser la touche CTRL ou CMD pour ajouter plusieurs pièces jointes.

**Comment by Grainedepaillette** [comment]
@btrd Ca me va pour la manip', par contre en front, côté espace candidat on pourrait avoir les P.J sous forme de liste et pas sur les mêmes lignes (comme ce qu'on retrouve en back côté recruteur ?) (cf. écrans). 

![Capture d’écran 2021-07-08 à 14.46.53.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/a71434e3-7b27-44e4-ae9d-a390486cf049)

![Capture d’écran 2021-07-08 à 14.48.12.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/db9ac343-2a15-4fe5-b53c-db717e5370ef)

**Comment by mch2608** [comment]
Fonctionnalité opérationnelle : je réouvre le ticket car l'envoi du courriel est très long lorsque l'employeur clique sur le bouton "Envoyer". L'utilisateur peut croire que le mail n'est pas parti et peut recliquer (au risque d'envoyer le courriel plusieurs fois).

**Comment by jrmlnzz** [comment]
@sebastiencarceles, tu as tout l'historique plus haut mais l'idée serait d'améliorer une feature déjà existante : pouvoir ajouter plusieurs fichers en PJ d'un mail, côté back et candidat, lorsqu'on clique sur ajouter un ficher, c'est le dernier sélectionné qui est pris en compte (quand tu les fais un par un) mais il est possible d'en ajouter plusieurs en les sélectionnant avec cmd. Est-ce que tu penses qu'on pourrait faire en sorte de pouvoir ajouter différentes pj de manière singulière ?

**Comment by sebastiencarceles** [comment]
Oui c'est possible, il faut probablement reconstruire la feature un peu différemment pour gérer les pièces jointes indépendamment les unes des autres. Il faut que je plonge dans le code pour en savoir plus.

**Comment by sebastiencarceles** [comment]
@jrmlnzz j'ai fais quelques recherches et c'est un sujet complexe. On pourrait faire du direct upload avec des outils plus modernes mais ceux du projet sont un peu anciens, et je ne peux pas les migrer à un coût raisonnable (ie en quelques heures / jours). Il faudrait revoir pour cela pas mal de fondamentaux de la gestion des fichiers (actuellement opérée par CarrierWave), c'est clairement un rabbit hole : c'est transverse à tout le projet, il faudrait faire une migration technique et une migration de fichiers, etc.

Définition du direct upload si besoin : les fichiers sont uploadés au fur et à mesure de leur sélection (éventuellement une barre de progression s'affiche), et non au moment de la soumission du formulaire.

Ce que j'envisage de faire, en revanche, ce serait quelque chose comme ça : 

---
> nom_du_fichier_01.pdf&ensp;&ensp;&ensp;:heavy_multiplication_x:
> nom_du_fichier_02.pdf&ensp;&ensp;&ensp;:heavy_multiplication_x:
> [Ajouter une pièce jointe](#)
---

- La croix :heavy_multiplication_x: permet de supprimer une pièce jointe.
- Le lien "Ajouter une pièce jointe" permet d'en ajouter plusieurs si la personne en sélectionne plusieurs dans la boîte de dialogue.
- Il n'y a pas de direct upload, pour la raison indiquée ci-dessus, donc les fichiers sont uploadés au moment de la soumission du formulaire.

Qu'en penses-tu ? Est-ce que ça serait une amélioration significative de la gestion des pièces jointes ?

**Comment by jrmlnzz** [comment]
Bien compris. Éclaire-moi juste sur ce que tu envisages de faire :
-Si je clique sur "Ajouter une pièce jointe" je peux ajouter mes fichiers les uns après les autres, et ils s'afficheront comme "nom_du_fichier_01.pdf" à la suite les uns des autres au fur et à mesure ?
-Ou quand je sélectionne mes fichiers je dois les uploads en même temps, en faisant une sélection groupée ?

**Comment by sebastiencarceles** [comment]
> -Si je clique sur "Ajouter une pièce jointe" je peux ajouter mes fichiers les uns après les autres, et ils s'afficheront comme "nom_du_fichier_01.pdf" à la suite les uns des autres au fur et à mesure comme sur Gmail, par exemple ?

Tout à fait : ça permet d'ajouter une ou des pièces jointes à la liste, qui viendra donc s'agrandir et afficher les nouveaux fichiers ajoutés en dessous des précédents. 

En revanche, à la différence de Gmail, on n'a pas la petite barre de progression qui exprime que le fichier est immédiatement uploadé.

> -Ou quand je sélectionne mes fichiers je dois les uploads en même temps, en faisant une sélection groupée ?

Les deux restent possible. Quand je clique sur "Ajouter une pièce jointe", la boîte de dialogue de sélection s'ouvre. Je peux :
- sélectionner un seul fichier => il vient s'ajouter à la liste
- sélectionner plusieurs fichiers => ils viennent s'ajouter à la liste

Dans tous les cas, quand je clique sur "Ajouter un pièce jointe", les pièces jointes précédemment ajoutées restent dans la liste, elles ne sont pas remplacées. Le seul moyen de les supprimer de la liste est d'appuyer sur :heavy_multiplication_x: pour chaque pièce jointe à retirer.

**Comment by jrmlnzz** [comment]
Aaaaaah ouais, je vois ! Écoute, c'est très bien comme comportement ! Vraiment, pas de soucis pour la petite progress bar, ce n'était pas primordial. Si t'as le temps, on peut partir là-dessus, oui ! Ce serait top !
