### ISSUE TITLE
Back/Paramètres : non modification positionnement éléments 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1042]
Testé en production 

Comportement constaté : lorsque l'on clique sur les flèches, les éléments ne basculent pas d'une ligne à l'autre (cf. vidéo). 

Comportement souhaité : pouvoir basculer un élément d'une ligne à l'autre à partir des flèches. 
https://images.zenhubusercontent.com/146276066/d58f812b-debd-4b38-84b9-8c3f1b4c6138/non_modification_positionnement_liste_parame_tres.mov

**Comment by btrd** [comment]
Corrigé en staging

**Comment by Grainedepaillette** [comment]
@btrd Test effectué en staging avec Mozilla, le clic sur la flèche ne correspond pas à l'action réalisée (cf. vidéo). 
Je me permets de réouvrir le ticket 

Lorsque je clique sur la flèche descendante : l'info remonte ou stagne 
Lorsque je clique sur la flèche ascendante  : l'info descend ou stagne 

https://images.zenhubusercontent.com/146276066/48dd7392-baf5-47cf-a8fb-308ad7580f03/fle_ches.mov

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel en staging, testé avec Mozilla
