### ISSUE TITLE
Back : création d'un bouton "Aide" qui renvoie vers le guide d'aide à l'utilisation de l'outil

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1044]
Comportement souhaité : 
- création d'un bouton qui renvoie vers le document PDF d'aide à l'utilisation de l'outil 
- le bouton est paramétrable par l'administrateur qui choisit le document PDF à insérer en back office

Objectifs : mettre en continue à disposition des utilisateurs une aide pendant leur utilisation de l'outil

Emplacement : 
- Scénario 1 : bouton "Aide" qui apparait en bas de chaque page du back office 
- Scénario 2 : création d'un onglet "Aide" qui apparait en haut de page 
- Scénario 3 : bouton en bas de page et création de l'onglet 

Format du document : PDF
Taille du document : 2,57Mo 
Nombre de pages : 52

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1078.osc-fr1.scalingo.io/

**Comment by mch2608** [comment]
Voici mes retours après test : 

1. L'onglet est bien visible pour tous les utilisateurs et accepte le document d'environ 50 pages. 

2. Dans les paramètres, est-il possible de reprendre la mise en forme de "image arrière plan" ? 

- Titre : Guide d’utilisation de l’outil
- Bouton "Parcourir" + encart pour téléverser le document 
- Coche "Supprimer le guide d'utilisation de l'outil" (en français) 

<img width="1440" alt="Capture d’écran 2021-07-23 à 16 01 59" src="https://user-images.githubusercontent.com/58481185/126793696-1b47c48d-f7f5-4e11-bf44-3dca2bd00fd0.png">

3. Au niveau du titre de l'onglet : "guide d'aide", je me demande si c'est très parlant. En revanche, "Guide d'utilisation de l'outil" risque de rendre un onglet trop grand. @Grainedepaillette Qu'en penses-tu ? 

4. Tu me confirmes bien qu'il n'y a pas de bouton développé et nous partons uniquement sur l'onglet ?

**Comment by Grainedepaillette** [comment]
@mch2608 @btrd 

> 3. Au niveau du titre de l'onglet : "guide d'aide", je me demande si c'est très parlant. En revanche, "Guide d'utilisation de l'outil" risque de rendre un onglet trop grand. @Grainedepaillette Qu'en penses-tu ?

Je propose de mettre simplement "Aide" cela parlera à tout le monde. 

> 4. Tu me confirmes bien qu'il n'y a pas de bouton développé et nous partons uniquement sur l'onglet ?

Je confirme, on part sur un onglet comme sur l'environnement c'est pas mal !

**Comment by mch2608** [comment]
> @mch2608 @btrd

> Je propose de mettre simplement "Aide" cela parlera à tout le monde.
Merci pour ton retour. Je suis d'accord. 

> Je confirme, on part sur un onglet comme sur l'environnement c'est pas mal !
Je suis d'accord, je me demandais s'il y avait un bouton à paramétrer que je n'avais pas vu pendant le test.

**Comment by btrd** [comment]
C'est corrigé, je me permet de mettre en staging directement

**Comment by Grainedepaillette** [comment]
@btrd c'est opérationnel staging !

**Comment by mch2608** [comment]
Je réouvre le ticket : 
comportement constaté en staging :  lorsque l'utilisateur souhaite supprimer l'aide, l'onglet "Aide" est toujours visible et renvoie vers le document qui n'est donc pas supprimé


https://user-images.githubusercontent.com/58481185/127559781-9cfdc821-5117-47d7-8f82-a7c560d124d3.mov


comportement souhaité : lorsque l'utilisateur souhaite supprimer l'aide, deux options : 
1 - l'onglet "Aide" disparait (option privilégiée) 
2 - l'onglet est toujours visible mais ne renvoie vers aucun document

**Comment by btrd** [comment]
C'est corrigé
