### ISSUE TITLE
Intégrer des bulles d'informations explicatives lorsque l'utilisateur approche un bouton / onglet 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1045]
Comportement souhaité : 

Lorsqu'un utilisateur approche un bouton, une bulle apparait pour expliquer les modalités d'utilisation de ce bouton. Exemple du BANT : lorsqu'un utilisateur la barre de recherche des offres, une bulle apparaît et indique les modalités de saisie. 

Les contenus de chaque bouton serait à définir par l'administrateur --> boutons paramétrables

**Comment by jrmlnzz** [comment]
@sebastiencarceles, aucune idée du temps que ça pourrait prendre, ni à quel point ça pourrait casser l'existant, mais je trouvais l'idée intéressante. Qu'est-ce que tu en penses ?

**Comment by sebastiencarceles** [comment]
J'ai l'impression qu'on a déjà cette logique de tooltip, surtout en front office. Quelques exemples : 

![image](https://user-images.githubusercontent.com/1193334/183590924-e04ee187-a0a7-4f93-87d6-8add3f020679.png)

![image](https://user-images.githubusercontent.com/1193334/183590987-719c99d9-0b7d-4983-8106-984f7e2ad437.png)

Comme on le voit ici, ces tooltips n'apportent pas grand chose.

J'ai un peu peur qu'on se lance dans une usine à gaz (rendre chaque bouton paramétrable depuis les paramètres), et je n'en comprends pas vraiment la valeur ajoutée. Est-ce que tu peux me donner des exemples d'endroits où ce serait utile ? Et quel texte on mettrait ?

Ensuite, en supposant qu'on parvienne vraiment à donner de cette manière une info utile à l'utilisateur·rice, il faut encore qu'on montre pourquoi ce serait utile de rendre ces tooltips paramétrables par l'administrateur·rice. La valeur n'est vraiment pas évidente pour moi, je rate peut être quelque chose ?

**Comment by jrmlnzz** [comment]
<img width="1428" alt="Capture d’écran 2022-08-09 à 09 39 42" src="https://user-images.githubusercontent.com/88372553/183592481-9789af64-a7db-4ba7-b8fc-a7156d1e7132.png">

De la manière dont je l'imaginais, ça aurait pu donner la possibilité d'expliciter les rôles par exemple, ou alors certaines appellations qui aurait pu être obscures dans le bo, mais en te lisant je me rends qu'effectivement ça peut rapidement devenir une machine à gaz qui n'apporte pas réellement de valeur ajoutée.

Dans le sens où pour mon exemple, les rôles seront bien compris des users et à défaut renseignés dans la documentation, et que si une appellation, ou nomination d'une section/ d'un bouton ne convient pas, on peut toujours le changer. 🤔

**Comment by sebastiencarceles** [comment]
OK je comprends mieux où on veut aller.

Seulement, en effet, rendre tous les boutons / liens / éléments de l'UI "explicables" par une tooltip, ça va être très compliqué. Ce serait beaucoup moins cher et beaucoup plus maintenable d'identifier, dans l'application, tous les endroits où on veut ajouter une explication. On se fait un petit ticket à chaque fois avec : 
- l'endroit concerné
- le texte explicatif

Ensuite, sur l'endroit en question, on affiche un petit :information_source: ou :eye: , qui indique à la personne qu'il y a une aide pour en savoir plus en passant la souris dessus : 

![image](https://user-images.githubusercontent.com/1193334/183598020-c8cf56dd-2ac7-41a1-8d0c-1e49d9457307.png)


Enfin, si le texte doit changer, il faudra faire intervenir un·e dev, mais comme pour tous les textes de l'application en fait.

**Comment by jrmlnzz** [comment]
Ouais finalement, je vois en en discutant avec toi que ça risque d'engendrer beaucoup trop d'éventuelles complications ce ticket, je te propose de le fermer, et on verra au cas par cas si jamais il y a des besoins d'expliciter des éléments.

**Comment by jrmlnzz** [comment]
J'avais pas vu tout ça sous cet angle, mais effectivement je m'en rends compte maintenant.

**Comment by sebastiencarceles** [comment]
> Ouais finalement, je vois en en discutant avec toi que ça risque d'engendrer beaucoup trop d'éventuelles complications ce ticket, je te propose de le fermer, et on verra au cas par cas si jamais il y a des besoins d'expliciter des éléments.

OK en effet, il me semble que voir au cas par cas est la meilleure approche. Je t'invite à faire un ticket si tu veux mettre un tooltip sur les rôles admin, pour commencer.
