### ISSUE TITLE
Back/Offres : création page de validation avant accès au formulaire rédaction offre 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1050]
Comportement constaté : aujourd'hui les recruteurs ont directement accès au formulaire de rédaction d'une offre d'emploi en cliquant sur le bouton "ajouter une offre". 

Comportement souhaité : créer une page intermédiaire lorsque les recruteurs cliquent sur le bouton "ajouter une offre" afin de s'assurer que les recruteurs ont bien le "droit" de publier sur E - recrutement. 

Ci - dessous l'écran modélisé : 
![Capture d’écran 2021-07-08 à 12.05.06.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/6361f79f-d8ae-47fd-af02-b8268ba8bc7d)

**Règles de gestion ** 
- Si clic une des options "oui" puis clic sur bouton "valider" ALORS redirection vers la page "formulaire de rédaction de l'offre" 
- Si clic une des options "non" puis clic sur bouton "valider"  ALORS message apparaît indiquant : _"Vous ne pouvez pas créer et publier d'offre sur le site au regard des dispositions de la Loi de transformation de la fonction publique"_ 
- Rendre impossible de cocher une même option "oui" et "non" : afficher message d'erreur : _"vous ne pouvez pas effectuer cette action"_
- Rendre impossible de cocher toutes les options "oui" : afficher message d'erreur : _"vous ne pouvez pas effectuer cette action"_
- Rendre impossible de cocher toutes les options "non" : afficher message d'erreur : _"vous ne pouvez pas effectuer cette action"_
 

**Paramétrage de la page** 
- Pouvoir paramétrer le titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le sous-titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le nombre d'options et le texte pour chacune des options par le rôle BANT au niveau de l'onglet "paramètres"
- Si l'ensemble des éléments ci - dessous ne sont pas alimentés par le BANT au niveau des paramètres ALORS ne pas afficher la page

**Comment by Grainedepaillette** [comment]
@btrd Suite à notre échange, ci- dessous les règles mises à jour : 

**Règles de gestion**

- Retrait de la colonne "NON" 
- Si aucune case n'est cochée ALORS bouton "valider" est grisé 
- Il faut cocher au minimum 1 fois "OUI" 
- Il n'est pas possible de cocher 3 fois "OUI" SINON apparition d'un message expliquant les raisons (à fournir par le BANT). 

**Paramétrage de la page** --> règles validées 

- Pouvoir paramétrer le titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le sous-titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le nombre d'options et le texte pour chacune des options par le rôle BANT au niveau de l'onglet "paramètres"
- Si l'ensemble des éléments ci - dessous ne sont pas alimentés par le BANT au niveau des paramètres ALORS ne pas afficher la page

**Comment by btrd** [comment]
Comportement constaté : aujourd'hui les recruteurs ont directement accès au formulaire de rédaction d'une offre d'emploi en cliquant sur le bouton "ajouter une offre". 

Comportement souhaité : créer une page intermédiaire lorsque les recruteurs cliquent sur le bouton "ajouter une offre" afin de s'assurer que les recruteurs ont bien le "droit" de publier sur E - recrutement.

**Règles de gestion ** 
- Si sélection *d'au moins* une options alors le bouton "valider" redirige vers la page "formulaire de rédaction de l'offre"
- Sinon (sélection d'aucune option) le bouton est grisé
- Rendre impossible de cocher toutes les options : afficher message d'erreur (à fournir par le BANT)

**Paramétrage de la page** 
- Pouvoir paramétrer le titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le sous-titre de la page par le rôle BANT au niveau de l'onglet "paramètres"
- Pouvoir paramétrer le nombre d'options et le texte pour chacune des options par le rôle BANT au niveau de l'onglet "paramètres"
- Si l'ensemble des éléments ci - dessous ne sont pas alimentés par le BANT au niveau des paramètres ALORS ne pas afficher la page

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630366463376439373465376338323135343833316634642f36333631663739662d643861652d343766642d616630322d623832363862613862633764](https://user-images.githubusercontent.com/1385737/125155032-8edd2d80-e15d-11eb-8c1d-589e6d682471.png)

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1058.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Mes résultats après tests : c'est opérationnel, en revanche au niveau des paramètres, je ne vois pas le paramétrage des options (nombre et contenu texte) (cf. écran). 

![Capture d’écran 2021-07-14 à 22.26.04.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/96e12154-3094-4c2f-b8a5-c166b36a5624)

**Comment by btrd** [comment]
Pour les options il faut aller tout en bas de la colonne de gauche.

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel sous Mozilla. 
Seul élément : serait-il possible d'afficher le "message d'erreur" en rouge ? Afin qu'il soit visible ? On a du mal à le distinguer actuellement (cf. écran). Merci. 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/6f60baa6-5411-4f81-b505-771b3faedc69)

**Comment by btrd** [comment]
C'est fait je merge en staging

**Comment by Grainedepaillette** [comment]
Merci :) j'attends ton go pour faire un dernier test en staging.

**Comment by btrd** [comment]
Go

**Comment by Grainedepaillette** [comment]
@btrd La page n'apparaît pas en staging avec le rôle employeur lorsque l'on clique sur le bouton "ajouter une offre". L'utilisateur "employeur " a directement accès au formulaire de rédaction d'une offre.

**Comment by btrd** [comment]
@Grainedepaillette Tu as créé des critères avec le BANT avant ?

**Comment by Grainedepaillette** [comment]
@Grainedepaillette Shame on me, je n'avais pas fait le nécessaire. La fonctionnalité est opérationnelle en staging avec Mozilla (test rôle BANT + employeur )

**Comment by mch2608** [comment]
Malgré la saisi des critères, la page n'apparait pas après clic sur le bouton '"ajouter une offre" en PROD. Je réouvre le ticket.

**Comment by mch2608** [comment]
https://images.zenhubusercontent.com/146276066/f649d955-fb6b-40f2-bff0-300fb213afa8/enregistrement_de_l__cran_2021_07_29___22_05_19.mov

**Comment by btrd** [comment]
Est-ce que tu as mis un titre et un sous-titre aussi ? Dans les paramètres

**Comment by mch2608** [comment]
Pour reprendre l'expression de Sarah : "shame on me" ! . C'est opérationnel.
