### ISSUE TITLE
Back/formulaire rédaction offre : ajout champs

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1051]
**Ajouter champs** au niveau du formulaire de rédaction de l'offre /partie "paramètres de l'offre/ à droite (à confirmer). 

**1) PEP** 
- Référence offre; champ texte libre 
- Date publication offre; JJ/MM/AA (calendrier)

**2) BNE**
- Référence offre; champ texte libre 
- Date publication offre; JJ/MM/AA (calendrier)

**Règle de gestion :** 
- Pour pouvoir créer l'offre (clic boutons "enregistrer" OU "publier") il faut que l'une ou l'autre des catégories (PEP OU BNE) soit complété (les 2 champs : référence + date)  

Cas de figures associés : 
1. Je complète les champs de la catégorie "PEP" ALORS je peux créer l'offre 
2. Je complète les champs de la catégorie "BNE" ALORS je peux créer l'offre 
3. Je complète les champs de la catégorie "PEP" et "BNE" ALORS je peux créer l'offre 
4. Je ne complète aucun des champs de la catégorie "PEP" et "BNE" ALORS je peux ne peux PAS créer l'offre lorsque je clique sur le bouton, un message d'erreur indiquant de compléter les champs doit s'afficher. 

Ces informations ne doivent pas apparaître en front office, elles sont destinées aux recruteur + BANT pour un suivi interne. 

Pour les offres déjà existante publiées ou en pauses assigner les informations suivantes : 
- Référence : "inconnue"
- Date de publication : 01/01/2020

**Comment by btrd** [comment]
Bloqué par https://github.com/betagouv/civilsdeladefense/issues/1053

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1071.osc-fr1.scalingo.io/

**Comment by Grainedepaillette** [comment]
@mch2608 J'ai reproduis tous les scénarios possibles de mon côté et c'est opérationnel. Tu confirmes de ton côté aussi ? Merci.

**Comment by mch2608** [comment]
C'est vérifié de mon côté. C'est opérationnel.
