### ISSUE TITLE
Back/Vivier : bouton "exporter" ne fonctionne pas

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1052]
En pré-production, cela fonctionne. 

En production, cela ne fonctionne pas. 
Rôle utilisé pour le test : BANT 

Comportement constaté : lorsque l'on clique sur le bouton exporter (pour exporter une sélection de profils avec ou sans filtre ou la totalité du vivier), aucune action ne se réalise. 

Comportement souhaité : lorsque clique sur le bouton "exporter" la sélection des profils effectuée (quelle qu'elle soit) puisse être effectivement exporter au format CSV

**Comment by btrd** [comment]
C'est logiquement corrigé avec la dernière MEP

**Comment by Grainedepaillette** [comment]
@btrd Testé en production sur Mozilla, le bouton "exporter" permet effectivement d'avoir un fichier CSV mais le PB c'est que celui ci est vide (que l'on applique des filtres ou non avant export). 

Voici le contenu de l'export une fois enregistrer sur le PC. 

![Capture d’écran 2021-07-14 à 22.05.55.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/e4318e00-9070-4889-9e39-ed81a4ccb341)

**Comment by Grainedepaillette** [comment]
Aussi, je réouvre le ticket.

**Comment by btrd** [comment]
Est-ce que tu as bien sélectionné des candidats avant d'exporter ? Parce que chez moi ça fonctionne bien

**Comment by Grainedepaillette** [comment]
@btrd Il me semble avoir appliqué les filtres lors de la 1ère phase de test.  J'ai refait les tests et cela fonctionne, je ferme le ticket et ré-ouvre si je vois le PB réapparaître.
