### ISSUE TITLE
Back/Formulaire rédaction offre : création statut "pré-publication" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1053]
Ce statut permettra aux utilisateurs de finaliser la rédaction d'une offre d'emploi en vue de la publication et du délai prévu avant publication automatique. 

Il existera 3 statuts : 

- enregistrer un brouillon de l'offre : le recruteur pourra alimenter les champs souhaités et enregistrer l'offre afin d'y revenir plus tard afin de la compléter en vue de la pré-publication. 
- pré publier l'offre : ce statut implique de compléter l'ensemble des champs du formulaire afin qu'elle soit pré-publiée est soumis au délai fixé par le BANT pour vérification. 
- publier l'offre : la publication pourra être réaliser automatiquement passé le délai fixé par le BANT via les paramètres OU manuellement par le BANT en cliquant sur le bouton.

**Comment by Grainedepaillette** [comment]
@btrd Après avoir mis à plat nos échanges, je me pose la question de la pertinence de cette fonctionnalité : 

Pourquoi ne pas modifier le statut actuel "enregistrement format brouillon" et ne plus y appliquer de restrictions : le recruteur peut renseigner seulement les champs dont il a connaissance et enregistrer en attente des éléments manquants (quel que soit le champ) 

Conserver le statut "publier" : en appliquant l'ensemble des restrictions identifiées pour chaque champ du formulaire. 

Au final on modifie le 1er statut en le rendant moins restrictif et on concentre les restrictions au niveau de la 2ème étape, qui sera soumise de fait à vérification (cf. délai)

Qu'en penses -tu ?

**Comment by btrd** [comment]
> Pourquoi ne pas modifier le statut actuel "enregistrement format brouillon" et ne plus y appliquer de restrictions : le recruteur peut renseigner seulement les champs dont il a connaissance et enregistrer en attente des éléments manquants (quel que soit le champ)

Cela pause des problèmes d'UX que je ne sais pas résoudre facilement. Par exemple, comment faire savoir à l'utilisateur que le titre est obligatoire sans le rendre obligatoire tant que l'annonce est en brouillon ? Pareil pour la mention `F/H`, etc

C'est possible et je pense une bonne chose pour les utilisateurs mais ça demande plus de réflexion.

Par contre dans ta 2e proposition on perd la fonctionnalité de publication automatique, c'est voulu ?

**Comment by Grainedepaillette** [comment]
Au regard de tes derniers éclairages, je serai d'avis d'abandonner la création d'un statut supplémentaire et rester sur le portage actuel : 

- enregistrement brouillon "contraignant" : il faut saisir toutes les données pour enregistrer et y revenir pour "peaufiner" (éléments textes, acteurs tagguées).

- publication : automatique passé le délai fixé. 

Juste quand tu parles de PB UX : pourquoi ne par reporter les restrictions au niveau du bouton "publier" : Je clique sur le bouton publier ALORS je vois apparaître l'ensemble des restrictions (qui sont aujourd'hui visibles lorsque l'on clique sur le bouton "enregistrer")

Pour répondre à ta question concernant la publication automatique : non on conserverait la publication automatique mais le clic bouton serait bloqué SI les restrictions ne sont pas respectées.

**Comment by btrd** [comment]
Au final la fonctionnalité n'est pas nécessaire (pour le moment en tout cas).
