### ISSUE TITLE
Front/Espace candidat : affichage message erreur 500 lorsque téléversement P.J

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1061]
**Testé en production**

**Comportement constaté :** 

Les candidats qui téléversent leur P.J via leur espace candidat en production ont un message d'erreur qui s'affiche. 

![Image Pasted at 2021-7-13 17-06.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/5ae1e25a-da08-4ef7-af6f-e6926ade8a03)

Lorsque l'on rafraîchit la page, les P.J ont bien été téléversées et le candidat peut le voir. 

**Comportement souhaité :** absence de message d'erreur lorsque le candidat effectue une action de téléversement des P.J

**Comment by btrd** [comment]
Corrigé et déployé en production

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel en production sur navigateur mozilla + chrome !
