### ISSUE TITLE
Back/Stats offres : message erreur s'affiche lorsque clic sur la page

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1062]
Testé en production 
Rôle BANT 

**Comportement constaté :** en back office, lorsqu'un administrateur (dans le cadre du test, le BANT) clique sur le l'onglet statistiques offres ALORS un message d'erreur s'affiche (cf. écran). 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/e643e857-27c7-41ad-990a-4ba5a2bb2867)

**Comportement souhaité :** afficher la page et les données associées lorsque l'on clique sur cet onglet.

**Comment by btrd** [comment]
C'était corrigé en staging mais pas en prod, c'est maintenant chose faite.

**Comment by Grainedepaillette** [comment]
@btrd Testé en production c'est opérationnel sur Mozilla et Chrome
