### ISSUE TITLE
Front / Espace candidat : modifier l'intitulé "Profile" 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1063]
TEST PROD

Comportement constaté : dans l'espace candidat, le 4ème onglet s'intitule "Profile" 

Comportement souhaité : enlever le "e" et nommer le 4ème onglet "Mon profil"

**Comment by btrd** [comment]
Corrigé

**Comment by mch2608** [comment]
C'est OK en staging
