### ISSUE TITLE
Front / Espace candidat / Onglet "Mes documents" : supprimer l'indication "Aucun fichier sélectionné" lorsque la PJ est déjà déposé 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1064]
Comportement constaté : lorsqu'un candidat dépose une PJ dans son onglet "Mes documents" de son espace candidat, le message "Aucun fichier sélectionné" apparait toujours à droite du bouton "Parcourir". Le candidat peut croire avec ce message que le document n'a pas été déposé malgré le fait que le message "Vous avez déjà téléversé ce fichier, il est en attente ........ " s'affiche bien en haut du bouton. 

Comportement souhaité :
1 -  lorsqu'un candidat dépose une PJ dans son onglet "Mes documents" de son espace candidat, le message "Aucun fichier sélectionné" n'est plus visible. 
2 - lorsqu'un candidat dépose une PJ dans son onglet "Mes documents" de son espace candidat, le message "Vous avez déjà téléversé ce fichier" en haut du fichier est mis en gras

Peux-tu nous faire une estimation pour les deux comportements souhaités ?

**Comment by btrd** [comment]
Proposition https://erecrutement-cvd-staging-pr1065.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd J'ai tenté de tester, mais en voulant postuler, je ne peux pas téléverser de cv et LM, il manque le bouton, sur l'environnement en question (cf. écran) 

![Capture d’écran 2021-07-14 à 22.29.46.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/e20c0afe-5e9c-4119-95e6-94615637557e)

**Comment by btrd** [comment]
C'est corrigé, le changement est visible sur la page Mes documents

**Comment by Grainedepaillette** [comment]
@btrd La fonctionnalité est opérationnelle sur Mozilla. En revanche, par rapport à l'ancien fonctionnement, on a perdu le code couleur : vert quand le fichier est validé et rouge quand le fichier est non validé. (cf. écran). 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/8789db06-4003-42b7-bbd9-9fc1e8e87adc)


Serait-il possible de récupérer ce code couleur au niveau du texte ? 
- en vert : Ce fichier a été validé ! + Vous pouvez consulter ce fichier.
- en rouge : Votre fichier n'est pas valide, veuillez en téléverser un nouveau.

**Comment by btrd** [comment]
<img width="641" alt="Capture d’écran 2021-07-19 à 18 50 13" src="https://user-images.githubusercontent.com/1385737/126197160-f4b53ee1-cca9-40f1-bc00-9c0bd733109a.png">

Ma proposition qui est déployé

**Comment by mch2608** [comment]
Le système des couleurs est opérationnel. En revanche, lorsque le candidat est face au message en rouge et qu'il re-téleverse une pièce : on ne lui indique pas que la nouvelle pièce a bien été téléversé.

**Comment by btrd** [comment]
![Capture d’écran 2021-07-20 à 11 24 05](https://user-images.githubusercontent.com/1385737/126296991-3d16c15d-e22d-4b38-b584-84c2c0079b16.png)
Il y a ce message en haut qui indique qu'un nouveau document a été téléversé.

Par contre le document ne devrai pas rester marqué comme non valide effectivement, j'ai testé en staging c'est aussi le cas.

Possible d'avoir un nouveau ticket pour ce bug ?

**Comment by mch2608** [comment]
Voici le ticket #1069
