### ISSUE TITLE
Front/Espace candidat : expiration de la session au bout d'1h

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1067]
[Cf. Ticket 683](https://app.zenhub.com/workspaces/e---recrutement-contractuels-606dc7f03bd5d900102637b6/issues/betagouv/civilsdeladefense/683) 

**Comportement constaté :**

Aucun dispositif d'expiration de la session candidat n'existe en front office.

**Comportement souhaité :**

Afficher un message d'information, indiquant que sans action de la part du candidat dans le prochaines minutes (5 ou 10min), sa session expirera et donner la possibilité de poursuivre la navigation.

**Format du message :** Sans action de votre part dans les 10 prochaines minutes, votre session expirera et vous serez déconnecté de la plateforme à 17H16".

En complément il faudrait activer le délai des 1heure pour affichage du message (cf. ticket 

Cette fonctionnalité répond également au RGAA.

**Comment by btrd** [comment]
> Comportement constaté :
> Lorsque le délai de 1h est écoulé sans que le candidat n'ait effectué d'actions (clic bouton) ALORS il est éjecté du portail 

Justement non, c'est le cas pour le backoffice mais pas sur le front.

**Comment by Grainedepaillette** [comment]
@Grainedepaillette je confirme, je corrige.

**Comment by Grainedepaillette** [comment]
Vérifier ateliers SSI pour shoot ticket

**Comment by jrmlnzz** [comment]
@sebastiencarceles désolé, je fais un peu de tri donc je vais peut-être te tag dans des choses qui ne sont peut-être pas très passionnante, mais tu veux bien vérifier si la session expire bien au bout d'une heure, comme ça on close le ticket.

**Comment by sebastiencarceles** [comment]
@jrmlnzz le timeout est actif côté admin seulement. Je l'ajoute donc également, calé sur une heure, pour le côté user (en front office, donc).


Pour l'autre partie de la demande :

> Afficher un message d'information, indiquant que sans action de la part du candidat dans le prochaines minutes (5 ou 10min), sa session expirera et donner la possibilité de poursuivre la navigation.
> Format du message : Sans action de votre part dans les 10 prochaines minutes, votre session expirera et vous serez déconnecté de la plateforme à 17H16".

Je peux effectivement ajouter cette fonctionnalité. Toutefois, même si ce n'est pas extrêmement compliqué, il y a quand même un peu de travail. Cette demande est-elle donc toujours d'actualité ? 

Documentation pour moi-même : https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/hooks/timeoutable.rb
