### ISSUE TITLE
Back/Paramètres généraux : délai avant publication doit être calculé en jours ouvrés

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1068]
**Comportement constaté :** Aujourd’hui le délai avant publication est calculé en heures (cf. écran). 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/6afc42d3-0891-4c90-a747-d1be47999ba6)

**Comportement souhaité :** Pouvoir calculer le délai avant publication d'une offre en jour ouvrés via un calendrier. Ce calendrier prendra également en compte les jours fériés.

**Comment by btrd** [comment]
Je ne comprends toujours pas la partie "calendrier", il faut choisir une date sur un calendrier ? Pour moi il faut juste choisir un nombre de jours.

**Comment by Grainedepaillette** [comment]
@btrd Effectivement, abus de langage de ma part, il faut passer en jours sans mise en forme calendrier. Seulement les WE + jours fériés ne doivent pas être pris en compte.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1072.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
J'ai été trop rapide ahah !
![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/d88a89b6-5cb8-4662-a786-302a4df68034)

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel depuis Mozilla.
