### ISSUE TITLE
Front / Espace candidat / Onglet "Mes documents" : le message "le fichier n'est pas valide" doit disparaitre lorsqu'on téléverse un nouveau document 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1069]
Comportement constaté : lorsqu'un employeur indique que le document téléversé par le document n'est pas conforme, un message "le fichier n'est pas valide..." apparait dans l'encart du document concerné pour le candidat. Lorsqu'il tente de téléversé un nouveau document par dessus, le message "le fichier n'est pas valide..." est maintenu 

Comportement souhaité : lorsqu'un employeur indique que le document téléversé par le document n'est pas conforme, un message "le fichier n'est pas valide..." apparait dans l'encart du document concerné pour le candidat. Lorsqu'il tente de téléversé un nouveau document par dessus, le message "le fichier n'est pas valide..." disparaît.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1075.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
C'est opérationnel. En revanche, on perd le système des couleurs du #1064 😢. Possible de le réinstaurer ?

**Comment by btrd** [comment]
Effectivement ! Tout est en staging maintenant :)

**Comment by mch2608** [comment]
C'est testé en staging, tout est opérationnel ! merci !
