### ISSUE TITLE
Back/Paramètres : pouvoir saisir plusieurs suffixes courriels

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1070]
Besoin exprimé par le SGDSN. 

**Comportement constaté :** 
Aujourd'hui le responsable fonctionnel ne peut saisir et autoriser u'un seul type de courriel pour l'accès au back office (cf. écran). 
![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/7e567511-2d36-43cd-8dad-8d7414b7e70a)

Comportement souhaité : Permettre au responsable fonctionnel de saisir plusieurs types de courriels (bouton "ajouter") et qu'il puisse également les modifier et les supprimer.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1074.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Testé sur Mozilla c'est opérationnel. Par contre on voit apparaître une coche verte seulement pour la 1ère ligne est-ce normal ? Car cela peut induire en erreur l'utilisateur. Il faudrait retenir une des 2 options : 
1) afficher la coche verte pour l'ensemble des lignes 
2) ne pas afficher de coche verte pour ce paramètre

**Comment by btrd** [comment]
La coche verte c'est pour l'ensemble du champ, je vais voir pour la retirer
