### ISSUE TITLE
Front / Espace candidat / Mes informations : pouvoir supprimer un souhait géographique 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1076]
TEST EN PRE-PROD et en PROD

Comportement constaté : dans l'onglet "Mes informations" de l'espace candidat, la suppression d'un souhait géographique ne s'enregistre pas

Comportement souhaité : dans l'onglet "Mes informations" de l'espace candidat, lorsqu'un candidat souhaite supprimer un souhait géographique, la suppression doit s'enregistrer. 

https://user-images.githubusercontent.com/58481185/126783488-cf2bcf50-8317-4645-a51f-06d62105a40e.mov

**Comment by btrd** [comment]
Corrigé en staging

**Comment by mch2608** [comment]
je rencontre toujours le problème en staging. 


https://user-images.githubusercontent.com/58481185/126787924-debb10cd-3bd6-4700-89a4-a8605cae1d98.mov

On remarque aussi dans la vidéo que lorsque le candidat a plusieurs souhaits géographiques déjà enregistrés et qu'il souhaite en supprimer un en cliquant sur le bouton "enregistrer", les souhaits géographiques déjà enregistrées se dupliquent.

**Comment by btrd** [comment]
C'était pas encore déployé quand j'ai écris mon message, maintenant c'est ok
