### ISSUE TITLE
Front / Espace candidat / Mes informations : ne pas dupliquer les souhaits géographiques existant à l'ajout d'un nouveau souhait géographique

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1077]
Comportement constaté 
- Dans l'onglet "mes informations" de l'espace candidat, lorsque le candidat a un / des premier(s) souhait(s) géographique(s) enregistré(s) et souhaite ajouter un nouveau, il sélectionne dans le menu déroulant un département et clique sur enregistrer 
- Le / Les premier(s) souhait(s) géographique(s) initialement enregistré(s) se duplique et le nouveau département sélectionné s'ajoute 

Comportement souhaité : 
-   Dans l'onglet "mes informations" de l'espace candidat, lorsque le candidat a un / des premier(s) souhait(s) géographique(s) enregistré(s) et souhaite ajouter un nouveau, il sélectionne dans le menu déroulant un département et clique sur enregistre
- Seul le nouveau département sélectionné s'ajoute à la liste des souhaits géographiques du candidat 

https://user-images.githubusercontent.com/58481185/126787357-80e1a11e-4b2b-485d-88a7-70adde5a30d8.mov

**Comment by btrd** [comment]
C'est lié au ticket #1076
