### ISSUE TITLE
[Environnement DGA] : un message d'erreur s'affiche lorsqu'on téléverse une PJ 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1085]
Comportement constaté dans l'environnement de la DGA : 

1. Lorsque le candidat remplit les champs du formulaire de candidature pour postuler à une offre, téléverse ses documents (CV et lettre de motivation) et clique sur le bouton "Je postule" --> un message d'erreur s'affiche et la candidature n'est pas déposée 
2. Lorsqu'un compte RF paramètre les PJ afin que les documents ne soient pas demandés dans le formulaire de candidature,  le candidat qui remplit les champs du formulaire et clique sur le bouton "Je postule" --> la candidature est bien prise en compte
3. Lorsqu'un candidat dépose une PJ dans l'onglet "Mes documents" de son espace candidat, un message d'erreur s'affiche automatiquement
https://user-images.githubusercontent.com/58481185/126986064-b3ead753-3fd7-4ada-8342-27a3576f6287.mov
4. Lorsque l'employeur dépose une PJ dans le dossier d'un candidat, un message d'erreur s'affiche automatiquement

**Comment by btrd** [comment]
C'est corrigé

**Comment by mch2608** [comment]
Je demande à la DGA de tester, merci !

**Comment by mch2608** [comment]
C'est testé par l'ANSSI et c'est ok
