### ISSUE TITLE
Général : pouvoir visualiser les intitulés complets des filtres

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1087]
comportement constaté : sur la page "vivier" et "statistiques candidatures" (en staging), l'intitulé du filtre  "souhait(s) géographique(s) (département)" déborde de l'encart et une partie n'est pas visible : l'utilisateur ne peut donc pas lire l'intitulé complet 

<img width="1440" alt="Capture d’écran 2021-07-28 à 12 02 58" src="https://user-images.githubusercontent.com/58481185/127304197-2effaec5-483a-4e4a-b55f-ef0b8d752851.png">

<img width="1439" alt="Capture d’écran 2021-07-28 à 12 05 06" src="https://user-images.githubusercontent.com/58481185/127304528-1f00a6da-7a84-43e9-a21c-fa2852aa64d5.png">

Comportement souhaité : pouvoir visualiser l'ensemble de l'intitulé d'un filtre

**Comment by mch2608** [comment]
je n'ai pas les droits pour l'associer à un sprint ou une colonne du zenhub. Mais on aimerait le faire passer en fin du sprint si possible, si le temps le permet

**Comment by sebastiencarceles** [comment]
C'est bien noté.
