### ISSUE TITLE
Back/Carte candidat : non visualisation CV + LM et impossibilité de télécharger 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#1119]
Comportement constaté : Les CV et LM de certains candidats ayant postulé aux offres en production, ne sont pas visibles en back office par les recruteurs. En lieu et place des fichiers, apparaît une page/écran blanc. Lorsque les recruteurs souhaitent télécharger le fichier pour le visualiser hors outil, le fichier est bien télécharger mais le contenu est vierge. 
Ce problème est aléatoire car pour une même offre des candidatures sont concernées et d'autres non. 

1er hypothèse : 
J'ai essayé de retracer le PB via send in blue pour voir de quelle manière ont postulé des candidats mais je ne trouver aucune trace des courriels de confirmation de compte et candidatures sur l'app. Est-ce dû au PB rencontré cet été ? 

2ème hypothèse : 
Le candidat n’a pas suivi la procédure classique de candidature à une offre d’emploi sur le site. Il initie 2 procédures distinctes en lieu et place de la procédure de candidature : une procédure de mot de passe oublié dans 1er temps puis une procédure de confirmation de création de compte dans un 2nd temps alors même que le compte n’était pas créé.
Peut être que le système les a bloqués pour des raisons de sécurité, la procédure classique n’ayant pas été suivie ?

Comportement souhaité : pouvoir visualiser les fichiers (CV + LM) téléversés par les candidats lorsqu'ils postulent.

**Comment by btrd** [comment]
Avons-nous ce problème en staging ?

**Comment by btrd** [comment]
Effectivement ça a l'air lié à tes hypothèses

https://rollbar.com/NVL/civilsdeladefense/items/718/

**Comment by mch2608** [comment]
> Avons-nous ce problème en staging ?

oui

**Comment by mch2608** [comment]
> Effectivement ça a l'air lié à tes hypothèses
> 
> https://rollbar.com/NVL/civilsdeladefense/items/718/

On n'a pas d'accès au lien. C'est un nouveau outil de ticketing ?

**Comment by btrd** [comment]
> On n'a pas d'accès au lien. C'est un nouveau outil de ticketing ?

Non c'est un outil technique, j'ai juste mis le lien pour le référencer pour moi sur l'issue

**Comment by btrd** [comment]
@mch2608 Tu as la procédure pour reproduire l’erreur en staging ?

J'ai ajouté un fix pour empêcher l'utilisateur de submit plusieurs fois le formulaire, ça peut-être une des sources du problème

**Comment by mch2608** [comment]
Exemple:  
- Le premier candidat nous pouvons visualiser et télécharger les pièces (document blanc, c'est normal) 
- Le second candidat nous ne parvenons pas à visualiser et télécharger le CV 
- 
https://user-images.githubusercontent.com/58481185/134320315-1bae2755-85f3-40f3-aa0d-56f49e0c0630.mov

**Comment by btrd** [comment]
Et tu sais me dire la procédure pour reproduire des candidatures qui bug ?
