### ISSUE TITLE
Modification de la SMTP_URL

### ISSUE THREAD

**Issue by sisitototest** [betagouv/civilsdeladefense#1122]
Je viens de modifier l'url smtp
J'ai une erreur 500 à chaque fois avec cette nouvelle url.
Lorsque je rebascule sur l'ancienne bon fonctionnement.
La nouvelle smtp_url comporte un - dans la première partie du mail et le mot de passe comporte des minuscule majuscule et des _ dont un à la fin du mot de passe.

Merci beaucoup pour votre aide
bonne journée

**Comment by jrmlnzz** [comment]
@sebastiencarceles, un sujet un peu technique, dis-moi si ça te parle ou si tu as déjà constaté ce comportement sinon on peut le clode. :)

**Comment by sebastiencarceles** [comment]
Je ne sais pas de quoi il s'agit et je ne connais pas la valeur de cette nouvelle URL. J'ai l'impression qu'on peut clôturer.
