### ISSUE TITLE
Back / Offres : pouvoir archiver une offre brouillon sans la publier

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1124]
Comportement constaté : Seuls les offres publiées et en pause peuvent être directement archivées. Pour archiver une offre brouillon, l'utilisateur est dans l'obligation de faire publier dans un premier temps son offre pour ensuite l'archiver.

Comportement souhaité : Permettre à l'utilisateur de directement archiver toutes les offres actives (publiées, en pause, en brouillon) à partir du bouton "...".

**Comment by sebastiencarceles** [comment]
@jrmlnzz je comprends bien la demande "Archiver depuis le bouton `...`" : 

![image](https://user-images.githubusercontent.com/1193334/173862030-6601f4e7-4f54-49f1-a772-c5b130d9ac24.png)

En revanche, je ne comprends pas la demande "Archiver à l'aide d'un bouton en bas de formulaire de création d'offres'". S'agirait-il de cet écran ?

![image](https://user-images.githubusercontent.com/1193334/173862461-76beabfb-6aed-4af6-bdf3-9e51d7323290.png)

**Comment by jrmlnzz** [comment]
Désolé, je n'ai pas pris le temps de modifier le ticket et je suis passé sur autre chose. Je pense qu'on peut retirer la dernière partie de la demande : "ou d'un bouton en bas de formulaire de création d'offres", on va rester sur les "..." qui permettent plus d'options.
