### ISSUE TITLE
Front / Filtre "Niveau d'expérience" : erreur affichage dans les intitulés des filtres

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1126]
Comportement constaté : Les intitulés affichés ne correspond pas aux intitulés paramètrés par le RF en back. 

<img width="1440" alt="Capture d’écran 2021-09-17 à 09 36 35" src="https://user-images.githubusercontent.com/58481185/133743777-f350fe7f-fa12-4337-b2ac-72765e0203a0.png">
<img width="646" alt="Capture d’écran 2021-09-17 à 09 38 13" src="https://user-images.githubusercontent.com/58481185/133743784-c4da3b5b-a73f-4358-b383-2edfce0fa84d.png">

Comportement souhaité : les intitulés formulés en back doivent apparaître en tant que tel en front

**Comment by btrd** [comment]
Corrigé en staging

**Comment by mch2608** [comment]
C'est ok
