### ISSUE TITLE
Back / Vivier / Liste de candidats : pouvoir supprimer un candidat d'une liste candidat

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#1127]
Comportement constaté : les utilisateurs n'ont pas la possibilité de supprimer un ou plusieurs candidats d'une liste de candidats. Ils ont uniquement la possibilité de supprimer une liste complète de candidat. 

Comportement souhaité : permettre aux utilisateurs de sélectionner des candidats dans une liste pour les supprimer sans pour autant supprimer la liste complète.

**Comment by sebastiencarceles** [comment]
J'aimerais des précisions ici stp @jrmlnzz .

1/ Je vais dans une liste 
![image](https://user-images.githubusercontent.com/1193334/174029993-c6c8b263-61ac-49a1-9519-dd8b1286fad4.png)

2/ Pour un·e candidat·e, j'appuie sur "Mon vivier"
![image](https://user-images.githubusercontent.com/1193334/174030147-5bc6b215-a302-4966-b41c-9a82b72fc057.png)

=> on est d'accord que, sur cette page, je peux **enlever le·a candidat·e de ma liste** ?

En conséquence, qu'est-ce qu'on souhaite faire ici ? Simplement rendre cette fonctionnalité plus accessible ? Si oui, est-ce qu'un bouton "Retirer de la liste" à côté de "Mon vivier" pourrait convenir ?

**Comment by jrmlnzz** [comment]
Comment tu accèdes à ton deuxième écran ?

**Comment by sebastiencarceles** [comment]
Grâce à "Mon vivier" en bas à droite : 
![image](https://user-images.githubusercontent.com/1193334/174031636-979989cd-0f30-47e1-802c-5f00238b0462.png)

**Comment by jrmlnzz** [comment]
Ah oui ! D'accord, j'avais du tout capté que c'était cliquable !

**Comment by jrmlnzz** [comment]
En vrai, on peut peut-être garder l'idée d'avoir une page "Mon vivier" où tu peux delete une même personne de plusieurs listes, mais peut-être changer l'icône (étoile) et le wording ?

**Comment by jrmlnzz** [comment]
Je sais pas si c'est pertinent mais quelque chose du genre "Accéder aux listes du candidat" ? Qu'est-ce que tu en penses ? "Gérer les listes du candidats" ?

**Comment by sebastiencarceles** [comment]
Oui voila mes propositions : 

1/ Renommer le lien "Mon vivier" en "Listes"

2/ Ajouter à sa droite un lien "Retirer" pour enlever rapidement le·a candidat·e de la liste courante

Ça ferait quelque chose comme ça : 

![image](https://user-images.githubusercontent.com/1193334/174033870-c484aeb0-e5d4-48ae-9ba7-795827d15b93.png)

(il faut imaginer des icônes plus adaptées également)

Qu'en penses-tu ? C'est assez clair ? Ou bien tu préfères une nomenclature plus détaillée, comme "Gérer ses listes" et "Retirer de la liste" ?

**Comment by sebastiencarceles** [comment]
J'ai l'impression qu'il y a des icônes au format SVG issues de fontawesome, je pense pouvoir y trouver mon bonheur :+1: 

![image](https://user-images.githubusercontent.com/1193334/174035511-27c2b96a-dc1e-4349-8ad1-fb4d7d2b3a2a.png)

**Comment by jrmlnzz** [comment]
Super !
