### ISSUE TITLE
Rendre le descriptif de l'organisation obligatoire

### ISSUE THREAD

**Issue by btrd** [betagouv/civilsdeladefense#1131]
En production aujourd'hui sur 1854 offres, 161 ont le statut publié, dont 43 n'ont pas de descriptif.

Si l'on rend le descriptif obligatoire, 1563 vont être invalide tant que le descriptif n'est pas ajouté. Ma proposition est de rendre le description obligatoire uniquement pour les offres publiés et de mettre les 43 offres publiés sans descriptif en brouillon.

**Comment by jrmlnzz** [comment]
@sebastiencarceles, qu'est-ce que tu en penses ? Est-ce que tu crois qu'il est possible de rendre le descriptif obligatoire pour les prochaines offres seulement qui seront publiées ? Ce que j'entends par là, c'est qu'on laisse en l'état celle qui sont publiées, mais que pour toutes les prochaines ou celles qui change de statut (brouillon-> publiée ou archivée-> publiée) doivent avoir une description ?

**Comment by sebastiencarceles** [comment]
Oui ça me convient : 

1. La description est obligatoire pour publier une offre
2. On laisse en l'état celles qui sont publiées (ie elles restent publiées même si elles n'ont pas de description)

Je te laisse mettre ce ticket dans le projet ?

**Comment by jrmlnzz** [comment]
Exactement, on fait comme ça merci ! (Le ticket est déjà dans le nouveau projet, héhé. 👀)
