### ISSUE TITLE
Impossible changer mail pour un compte déjà crée

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1161]
En tant qu'administrateur (BANT), quand je clique sur le profil d'un utilisateur (dans "Aministration" -> "Comptes admin") pour modifier son adresse mail et que je sauvegarder les changements, ils ne sont pas pris en compte et le mail reste le même.

**Comment by sebastiencarceles** [comment]
Bonjour @jrmlnzz 

Est-ce qu'on parle bien de cet écran là : 
![Screenshot 2022-06-02 at 09-23-55 Comptes admin - Civils de la Défense](https://user-images.githubusercontent.com/1193334/171576123-791e583b-8641-43c4-a6e2-8661e9d77efd.png)
(ici j'ai remplacé `cvd_employer2` par `cvd_employor2`).

Si oui, je pense que c'est normal. Au moment où on change l'adresse email, un email de confirmation est envoyé à la nouvelle adresse : 
![Screenshot 2022-06-02 at 09-25-03  Civils de la Défense  Instructions de confirmation](https://user-images.githubusercontent.com/1193334/171576319-c09ce873-179b-4974-9795-068483a1c8d8.png)

Une fois que la nouvelle adresse email est confirmée, alors le changement est bien pris en compte : 
![Screenshot 2022-06-02 at 09-26-01 Comptes admin - Civils de la Défense](https://user-images.githubusercontent.com/1193334/171576588-a247f22b-4ada-41bd-99f4-7a1a77a0678c.png)

Donc ici on est plutôt dans le cadre du fonctionnement normal. Est-ce que c'est réellement un problème ?

**Comment by jrmlnzz** [comment]
Ah, je viens de voir ta réponse Sébastien. Au temps pour moi, je ferme le ticket.
