### ISSUE TITLE
Instance DGA - Descriptif onglet

### ISSUE THREAD

**Issue by HP94** [betagouv/civilsdeladefense#1170]
# Situation actuelle
Sur l'instance de la DGA : https://ict-tct.contractuels.civils.defense.gouv.fr/
le texte de l'onglet le texte est manquant

# Situation souhaitée
Mettre le texte suivant : (à voir avec Jérome)

**Comment by HP94** [comment]
@jrmlnzz Jérome tu pourrais voir avec Marie Schneck et christelle Latge si elles ont une idée ? Sinon reprend comme pour CVD en adaptant : "Plateforme de recrutement du personnel civil contractuel pour la Direction Générale de l'Armement"

**Comment by btrd** [comment]
Vous êtes autonome pour configurer les instances dans la partie admin. Pour le moment je ne peux pas vous inviter car il manque l'email par défaut.

https://github.com/betagouv/civilsdeladefense/issues/1159#issuecomment-976269399

**Comment by jrmlnzz** [comment]
> @jrmlnzz Jérome tu pourrais voir avec Marie Schneck et christelle Latge si elles ont une idée ? Sinon reprend comme pour CVD en adaptant : "Plateforme de recrutement du personnel civil contractuel pour la Direction Générale de l'Armement"

Je viens de voir avec Marie et Christelle, elles me disent qu'elles préfèrent rédiger ce titre elles-mêmes, une fois qu'elles auront des comptes administrateurs.
