### ISSUE TITLE
Multidiffusion des offres publiées

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1267]
Lorsqu'une offre est créée/ publiée sur le portail e-recrutement, on aimerait pouvoir la diffuser également sur d'autres plateformes comme l'APEC, LinkedIn ou encore Indeed. Il faudrait voir si on peut se câbler à leur api, pour pouvoir faire le lien automatiquement, et ne pas refaire le travail a la main de créer la même offre sur plusieurs sites.

**Comment by sebastiencarceles** [comment]
Comme discuté, je vais clôturer cette issue et en créer une par plateforme cible.
