### ISSUE TITLE
Case "Sélectionner tout" ne fonctionne pas dans le BO

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1271]
Ce que je fais :
1/ Je me connecte sur la partie back-office
2/ Dans les Offres ou alors dans le Vivier, quand je coche la case "Tout sélectionner" rien ne se passe
3/ Cependant, quand je coche la case "Sélectionner la page" toutes les offres (ou candidats) sont sélectionnés

Ce qu'il se passe :
La case "Tout sélectionner" n'exécute (à priori) aucune action, et la case "sélectionner la page" sélectionne toutes les entrées de notre liste.

Ce qu'il devrait se passer :
Peut-être pourrait-on fusionner les deux cases en une seule ? Sinon, la case "Tout sélectionner" devrait sélectionner les différents éléments des Offres, ou du Vivier.

Criticité :
- faible : il y a un bug, mais on peut vivre avec. On a en l'occurrence l'alternative d'utiliser une case plutôt que l'autre.

Fréquence :
Systématique.

Informations complémentaires
Je connaissais Loom de nom, mais jamais utilisé alors : https://www.loom.com/share/a0b2dc8ed7a5480f9c5cfea436cf4a0b 👀

**Comment by sebastiencarceles** [comment]
@jrmlnzz je viens de vérifier, et en fait, ça fonctionne, mais c'est améliorable. 

En effet, si je fais : 

1. je vais dans le vivier
2. je fais "Tout sélectionner" => seule la case "Tout sélectionner" est cochée, pas les autres
3. je fais "Exporter"

Alors, le fichier téléchargé contient bien _tous·tes_ les candidat·es.

---

À l'inverse, si je fais : 

1. je vais dans le vivier
2. je fais "Sélectionner la page" => les case des candidat·es sont aussi sélectionnées
3. je fais "Exporter"

Alors le fichier téléchargé contient _seulement_ les candidat·es de la page en cours.

---

Donc à mon avis c'est bien le comportement attendu. Il s'agit de deux fonctionnalités légèrement différentes, puisque la première sélectionne bien tous·tes les candidat·es, et la seconde seulement celleux de la page.

En revanche, le défaut d'après moi,  c'est que lorsqu'on fait "Tout sélectionner", il n'y a pas de feedback visuel. On devrait voir, à ce moment là, les cases des candidat·es être cochées aussi.

Est-ce que tu es d'accord avec ça ?

**Comment by jrmlnzz** [comment]
Ah oui, au temps pour moi ! Je n'avais pas été jusqu'à l'export. Mais sinon, oui complètement d'accord avec toi !
