### ISSUE TITLE
Pastilles de notification persistantes dans le BO

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1279]
Ce que je fais :
1/ Je me connecte sur le back office en tant qu'administrateur
2/ Je scroll parmi les Offres, et certaines ont une pastille rouge de notification (avec le nombre)
3/ Quand je rentre sur l'offre en question la pastille est bien visible à droite de l'écran, mais n'est pas cliquable
4/ Je dois me rendre dans la partie "Candidatures" et chercher quels candidats sont à l'origine de la notification
5/ Et, une fois que je clique sur le candidat je peux bien marquer ses mails comme lus (ce qui retire la pastille de notification) et accepter ou non le document qu'il m'a transmis pour retirer la pastille des documents

Ce qu'il se passe :
En réalité, malgré que l'expérience ne soit pas forcément très intuitive (on ne peut pas accéder directement aux notifications (il faut les chercher)), il faudrait simplement avoir un moyen de marquer toutes les notifications comme lues

Ce qu'il devrait se passer :
Avoir une manière plus intuitive de gérer les notifications ? (On s'en parle si besoin)

Criticité :
faible : il y a un bug, mais on peut vivre avec

Informations complémentaires :
Si le compte du candidat est supprimé entre temps, il est impossible de retirer la pastille de notification.
En faisant le record de mon screen, j'ai constaté que certains nombres n'étaient pas cohérents avec le réel de notifications/ actions à mener.

https://www.loom.com/share/7b23026d43d94cdfbe75ec8910b861a2

https://www.loom.com/share/02c9affe054e489295cc2879812dcaed

**Comment by sebastiencarceles** [comment]
Il y a deux demandes dans ce ticket :

1. une évolution de périmètre : "Tout marquer comme lu"
2. un bug : incohérence entre le nombre affiché au niveau du job et le détail des emails / documents reçus

Pour l'évolution, comment vois-tu les choses ? Est-ce qu'on met un nouveau bouton en bas à droite ici, ou dans le menu `...` ?
![image](https://user-images.githubusercontent.com/1193334/174273908-624f00f1-2cd8-44e1-8111-b9e8df6d50a5.png)

Pour les bug d'incohérence, je n'ai pas encore réussi à déterminer si ça vient simplement de la suppression de la candidature ou s'il y a un problème plus global. Pour commencer, je vais corriger la suppression de la candidature, qui devrait mettre ses emails / documents à lus (et donc faire baisser le nombre de notifs).

**Comment by jrmlnzz** [comment]
Ah oui, je me suis un peu emballé en rédigeant le ticket je tombais sur des nouvelles choses, ahah. Ouais complètement pour l'évolution, on peut simplement rajouter l'option dans les "...". :)
