### ISSUE TITLE
Admin/ Pouvoir envoyer un mail à plusieurs destinataires

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1280]
J'ai eu un retour d'utilisateurs qui me demandaient vouloir envoyer un même mail à plusieurs destinataires (candidats).

Sur le screenshot lié à cette ce ticket, j'ai suivi le chemin :
1/ Je me suis connecté en tant qu'admin dans le bo
2/ J'ai cliqué sur l'offre "EMA3 Responsable Achat d’Infrastructures F/H"
3/ Puis parmi les 16 candidats, j'ai choisi Gaston Nguyen
4/ Et enfin, je suis entré dans la section "Courriels"

J'imaginais que peut-être dans cette vue, on pourrait avoir un champ "Destinataires" avec le nom du candidat sélectionné pré-rempli, et la possibilité d'en rajouter à la main ?
Ou alors, peut-être faire une liste de diffusion, et choisir d'envoyer le même mail aux candidats qui sont dans la catégorie "nouveau" ?

Qu'est-ce que tu en penses ? Comment tu vois les choses ?
<img width="1140" alt="Capture d’écran 2022-06-20 à 08 51 00" src="https://user-images.githubusercontent.com/88372553/174543398-8a5dc614-52f6-49a1-ac98-8394ed67c884.png">

**Comment by sebastiencarceles** [comment]
Ca m'ennuie d'envoyer un courriel à plusieurs candidat.es alors qu'on se trouve sur la page d'un.e candidat.e en particulier. Il me semble que ce n'est pas clair pour l'admin.

Je te propose une autre approche, basée sur ton idée de liste de diffusion. Supposons qu'on dispose du module suivant, qui permet d'envoyer le courriel à plusieurs personnes à la fois :

![image](https://user-images.githubusercontent.com/1193334/174587930-0211f37b-f9d1-453f-a42c-2d39176ecfe8.png)

Maintenant, supposons qu'on ait un bouton, sur les colonnes des candidatures, qui permette d'invoquer ce module : 

![image](https://user-images.githubusercontent.com/1193334/174586733-2fb62a56-14fe-46fb-b5f6-a7e6e3ad4467.png)

Les destinataires seraient alors les personnes présentes dans la colonne (hors comptes supprimés ou suspendus). Est-ce que ça fonctionnerait ?

Le problème, c'est si on souhaite envoyer un courriel à certaines de ces personnes seulement. Est-ce un besoin ? Il faudrait alors un système de checkbox pour sélectionner les destinataires, mais ça va être difficile à faire rentrer dans cette colonne, on manque d'espace. Je recommanderais alors de passer par un écran intermédiaire, qui liste les destinataires, où toutes les cases sont cochées par défaut mais où on peut les décocher : 

![image](https://user-images.githubusercontent.com/1193334/174587562-bdd2d959-e188-4346-9d23-dc835274ab34.png)

On pourrait d'ailleurs probablement avoir, sur cet page, la liste des destinataires et le module de courriel. Qu'en penses-tu ?

**Comment by sebastiencarceles** [comment]
Oui ce serait possible en effet, je vais partir sur ta proposition.

Le point de complexité, c'est bien sûr le champ "Destinataires". C'est plutôt facile de le préremplir avec les personnes de la colonne, et de permettre d'en enlever. C'est beaucoup plus compliqué d'en ajouter : 
- du point de vue du look n feel, si on veut s'approcher d'un gmail, il y a un peu de travail
- je suppose qu'on aurait envie d'avoir de l'autocomplétion

En effet, si je commence à taper "sebas", j'ai envie que ça me propose directement tout ce qui peut matcher, comme nom, prénom ou adresse email. Il y a un peu de travail de ce côté là aussi.

**Comment by jrmlnzz** [comment]
Ah oui bien sûr, je comprends totalement pour la complexité au niveau de l'ajout de destinataires, je n'y avais pas pensé (et surtout pour l'autocomplétion).

Néanmoins, si c'est jouable, ou si ça te semble réalisable ça peut-être intéressant à mettre en place, qu'est-ce que tu en penses ?
Enfin, si ça représente un trop gros ticket, on peut le séparer en :
Ticket n°1 : Champ destinataires pré-rempli avec les personnes de la colonne et possibilité d'en retirer
Ticket n°2 : Ajout de destinataires, et autocomplétion

Dis-moi comment tu vois les choses. :)

**Comment by sebastiencarceles** [comment]
Je défriche le terrain et je te dis !
