### ISSUE TITLE
DashLord : Accessibilité

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1368]
![Capture d’écran 2022-08-02 à 14 06 43](https://user-images.githubusercontent.com/88372553/182370688-12ad61cd-c929-4552-ae97-2750e17ac918.png)
Deux choses ici :
- La mention "Accessibilité : non conforme" doit être présente sur toutes les pages. Pour moi, c'est le cas dans le footer : Est-ce que tu sais si le robot arrive à l'identifier, est-ce que le fait que ce soit un link puisse l'empêcher de lire la mention ?
![Capture d’écran 2022-08-02 à 14 07 43](https://user-images.githubusercontent.com/88372553/182371065-0f8a4e25-f146-4423-a8b8-c803dee598df.png)
- La déclaration n'a pas été trouvée : pourtant, on a bien la page qui existe.
https://contractuels.civils.defense.gouv.fr/pages/declaration-d-accessibilite

**Comment by sebastiencarceles** [comment]
> La mention "Accessibilité : non conforme" doit être présente sur toutes les pages. Pour moi, c'est le cas dans le footer : Est-ce que tu sais si le robot arrive à l'identifier, est-ce que le fait que ce soit un link puisse l'empêcher de lire la mention ?

D'après ce que je vois dans le code du robot, on veut avoir ici la phrase "Accessibilité : non confirme". Or sur CVD, on a seulement "Accessibilité : non". Je peux déjà patcher ce wording, ça me permettra d'entrer dans le sujet !

**Comment by jrmlnzz** [comment]
Ah mais oui, bien vu. Je comprenais tellement pas pourquoi on avait cette alerte que je ne faisais même plus attention au wording, et au fait qu'il manquait un mot.

**Comment by sebastiencarceles** [comment]
> La déclaration n'a pas été trouvée : pourtant, on a bien la page qui existe.
> https://contractuels.civils.defense.gouv.fr/pages/declaration-d-accessibilite

En toute logique, c'est quand on clique sur "Accessibilité : non conforme" qu'on devrait arriver sur cette page, n'est-ce pas ? Car, actuellement, ce n'est pas relié. Le lien de "Accessibilité : non" ne mène nulle part.

**Comment by jrmlnzz** [comment]
Hmm, qu'est-ce que tu en penses sachant qu'on peut y avoir accès grâce au link juste à droite ?
<img width="1345" alt="Capture d’écran 2022-08-04 à 15 00 54" src="https://user-images.githubusercontent.com/88372553/182853337-d6bf277d-9fad-420a-abcc-571f5b7614c9.png">

- Est-ce qu'on met "Accessibilité : non conforme" et "Déclaration d'accessibilité" en lien cliquable
- Est-ce qu'on garde "Accessibilité : non conforme" sans lien et "Déclaration d'accessibilité" cliquable ?

**Comment by sebastiencarceles** [comment]
D'après ce que je comprends du code du robot, il va d'abord chercher le lien qui correspond à "Accessibilité : non conforme", le cas échéant. Aujourd'hui, ce n'est pas branché, mais il suffit ici de rediriger vers la bonne page et ça réglera le problème sur DashLord.

Ensuite, s'il ne trouve pas de lien (ou qu'il ne trouve pas "Accessibilité : non conforme"), il cherche un lien avec le texte le plus proche possible de "Accessibilité", et s'il existe, il suppose que la page est là.

Donc techniquement, tes deux options devraient fonctionner. J'ai regardé quelques autres startups et c'est la première option qui est retenue. Par exemple : 
- Accessibilité : non conforme => https://metiers.numerique.gouv.fr/
- Accessibilité : partiellement conforme => https://www.data.gouv.fr/fr/

Du coup, ça te convient si on reste là-dessus ?

**Comment by jrmlnzz** [comment]
Ouais carrément, faisons comme ça !

**Comment by sebastiencarceles** [comment]
C'est corrigé et je pense que ça sera pris en compte sur la page du DashLord ce dimanche, donc lundi prochain ça devrait être OK. Donc c'est bon pour CVD aka https://contractuels.civils.defense.gouv.fr/

Pour info, la page "Déclaration d'accessibilité" est une page dynamique, qui est éditable depuis les paramètres : 
![image](https://user-images.githubusercontent.com/1193334/182868638-719c1e58-16ed-41c3-94dc-cf9b094381a9.png)

Et, c'est important, les instances de l'ANSSI (https://talents.ssi.gouv.fr/) et de la DGA (https://ict-tct.contractuels.civils.defense.gouv.fr/) **n'ont pas** de page de déclaration d'accessibilité. Est-ce que tu peux voir avec elleux pour qu'elle soit ajoutée ? Il faut impérativement que la page ait le titre "Déclaration d'accessibilité", sinon le lien ne fonctionnera pas dans le footer.

Merci

**Comment by jrmlnzz** [comment]
Aaaaaah ! Hyper intéressant, je m'en occupe. Merci de l'info !
