### ISSUE TITLE
Admin - CTA retour haut de la page à déplacer

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1379]
<img width="1433" alt="Capture d’écran 2022-08-03 à 13 12 09" src="https://user-images.githubusercontent.com/88372553/182594587-aae0ad8a-8074-4f1c-a5bf-99a3c1755256.png">

Comme tu peux le voir sur la capture ci-dessus, dans la partie "Paramètres" du bo, on a un CTA qui trigger un retour en haut de la page, positionné en bas à gauche de l'écran, et qui masque certaines entrées. Est-ce que tu pourrais le déplacer à la droite de l'écran plutôt ? On le garde toujours en bas mais pour ne plus qu'il soit superposé sur d'autres éléments et surtout qu'il soit du côté de la page sur lequel il a une action. :)

**Comment by jrmlnzz** [comment]
On en discutait ce matin sur Mattermost, tu peux me filer le lien pour que je puisse tester la feature, s'il te plaît ? 🙏 Enfin, si c'est bon pour toi, bien sûr.

**Comment by sebastiencarceles** [comment]
Yes ! Le voici : https://erecrutement-cvd-staging-pr1382.osc-fr1.scalingo.io/admin
C'était dans la [PR correspondante](https://github.com/betagouv/civilsdeladefense/pull/1382) :)

**Comment by jrmlnzz** [comment]
Ah oui, j'avais pas vu désolé ! Sinon, c'est bon pour moi : impec !

**Comment by jrmlnzz** [comment]
Merci. :)
