### ISSUE TITLE
BO : les menus déroulants ne s'affichent plus

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1407]
**Ce que je fais**
Lorsque j'arrive dans le back-office de l'outil en tant qu'administrateur, l’ensemble des menus déroulants de l’application ne sont plus accessibles (tous les modules sont concernés).

https://www.loom.com/share/1a9be518e8f14120a3a126b31ffb918b

Pour aller encore plus loin, le même cas de figure se présente sur les boutons « … » accessibles au niveau de la page « Offres » pour chaque cartouche, le bouton permettant une action rapide sur une offre n’est plus accessible (le menu déroulant ne s’affiche pas).

https://www.loom.com/share/7532d9ef6cab49238b53efc629878131

J'imagine que les deux sujets sont liés.

**Ce qu'il devrait se passer**
Les menus déroulants devraient fonctionner, ils devraient afficher les différentes options.

**Criticité**
- majeur : il y a un bug, ça n'empêche pas de travailler / d'utiliser l'application mais ça serait bien de le résoudre

**Fréquence**
 Tout le temps.

**Comment by sebastiencarceles** [comment]
Note to self : le problème apparaît à partir de https://github.com/betagouv/civilsdeladefense/pull/1394

Ça vient très certainement de la mise à jour de la lib `bootstrap.native`

**Comment by sebastiencarceles** [comment]
Doublon avec #1423
