### ISSUE TITLE
Notifications journalières ne sont pas reçues

### ISSUE THREAD

**Issue by jrmlnzz** [betagouv/civilsdeladefense#1408]
Absence de réception du récapitulatif journalier sur les boîtes mail des utilisateurs (tous les rôles sont concernés).

Peut-être un rapport avec l'autre sujet relatif aux mails ? Peut-être que les mails envoyés par l'application se perdent ?

**Comment by JohHar-dot** [comment]
Depuis le 30 octobre, nous ne recevons plus de notifications journalières.

**Comment by SophieLarroumet** [comment]
Entre le 13 septembre et le 18 octobre plus de notification et c'est revenu le 19 octobre. 
Dernière notification le 29 octobre

**Comment by sebastiencarceles** [comment]
@SophieLarroumet je mets ce ticket dans "Review in progress" parce que je reçois bien les notifications journalières. Je pense que ce problème n'existe plus depuis qu'on avait réparé l'envoi des emails. Il y a peut être un autre problème, ou alors le bug persiste dans une forme différente ou dans des conditions différentes, qui pourraient mériter un nouveau ticket le cas échéant.

**Comment by SophieLarroumet** [comment]
Je viens d'avoir le retour et c'est bon ils ont les notifications
