### ISSUE TITLE
Migration to Stack scalingo-20

### ISSUE THREAD

**Issue by sebastiencarceles** [betagouv/civilsdeladefense#1436]
You receive this email as you currently run one or multiple applications on Scalingo using the scalingo-18 stack. This stack is based on Ubuntu 18.04 which will reach end of life on April 2023. You are strongly encouraged to migrate your applications to the scalingo-20 stack.

Configuring your applications to use a new stack is easy. We published a guide to assist you with this on [our documentation](https://scalingo.intercom-clicks.com/via/e?ob=k%2B%2F8L%2FHAjFudtHtsQoDJ0bk9zjp%2Bn0N7zxJ%2BouHjeKXgnS%2FRwGRIDHINr9aKDr2nvz%2FWq6%2BWx%2FbVDdRwlQ8VsNmaAJxNcZOn4MZvnG96oS4lZrFN02c4vF44WGzvj3tn&h=642d55e29bd45c1d245ab85f35478af3890aba2d-w4oogu7s_12375700134242&l=cd6952640a0612516824a611bfa5f62edcc71f0f-40344888). In case of trouble, our support team is always here to help you.

The deprecation schedule for the scalingo-18 stack is as follow:

1.    3rd of January 2023 scalingo-18 stack is deprecated. It is no longer possible to update the stack of an application to use it.
2.    1st of April 2023: automatic update the stack of all applications still using scalingo-18 to scalingo-20. The change will take effect at the next deployment.
3.    30th of April 2023: automatic redeploy of all applications which haven't been deployed since the 1st of April 2023. This automatic procedure is not without risk for the availability of your applications as we cannot guarantee that the applications will work the same way with scalingo-18 and scalingo-20.

**Comment by sebastiencarceles** [comment]
@SophieLarroumet si c'est ok pour toi, j'ajoute cette tâche dans la todo list. Il faut migrer les applications vers une stack plus récente parce que ubuntu 18.04 ne sera bientôt plus maintenu.

**Comment by SophieLarroumet** [comment]
Salut @sebastiencarceles : c'est ok pour moi.

**Comment by SophieLarroumet** [comment]
Hello @sebastiencarceles 
C'est ok pour moi
