### ISSUE TITLE
Création d'une offre - Bug BOP - env Scallingo

### ISSUE THREAD

**Issue by SophieLarroumet** [betagouv/civilsdeladefense#1463]
**Ce que je fais :** 
Sur l'environnement : https://erecrutement-cvd-staging-pr1462.osc-fr1.scalingo.io/admin/
Lorsque je créé une nouvelle formation, il faut que je sélectionne le BOP et la liste n'apparait pas 

https://www.loom.com/share/ca06bd225c2342f6a280f847c12a52c1

**Ce qu'il doit se passer :** 
Normalement la liste suivante apparait : 
- SRHC
- DGA
- SIC
- Candidatures spontanées
- DGA

**Comment by sebastiencarceles** [comment]
Il s'agissait d'une review app, je ne suis pas sûr qu'elle ait eue les bonnes données. Désormais elle est fermée, comme j'ai clôturé la branche correspondante...
Le bug est-il reproductible en production ?

**Comment by SophieLarroumet** [comment]
Non le bug n'existe pas sur la prod. 
Je supprime ce ticket
