### ISSUE TITLE
Création Offre - Bouton Archiver - Env Scallingo

### ISSUE THREAD

**Issue by SophieLarroumet** [betagouv/civilsdeladefense#1464]
**Ce que je fais :** 
Après avoir rempli le formulaire de création de mon offre je souhaite l'archiver je tombe sur une page d'erreur.

https://www.loom.com/share/133bba3fc68a4bd998c14ddef3a70afd

**Comment by sebastiencarceles** [comment]
Sur quel instance rencontres-tu ce bug ?
Est-il reproductible en staging ou production ?
Merci

**Comment by SophieLarroumet** [comment]
Pareil que sur l'autre ticket. 
Je ne le reproduit pas sur la préprod
