### ISSUE TITLE
Création d'un statut inactif pour les comptes "recruteurs"

### ISSUE THREAD

**Issue by chakerb** [betagouv/civilsdeladefense#15]

**Comment by yannski** [comment]
Utiliser les fonctionnalités de la gem "Devise" pour gérer ça : https://rubygems.org/gems/devise
Pour le design, se référer à Zeplin.

**Comment by yannski** [comment]
Référence design : 
![8c_membres](https://user-images.githubusercontent.com/11287/45365551-07ea5e00-b5dd-11e8-8a73-3f60986cf7fc.png)

**Comment by yannski** [comment]
Fixed in https://github.com/betagouv/civilsdeladefense/commit/9fe95ddec3af89ef86451c57600ae995d702b199
