### ISSUE TITLE
[Admin] Afficher un champ "Durée de contrat" quand type de contrat est CDD

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#20]

**Comment by yannski** [comment]
Pour basculer l'affichage du champ dans le formulaire, l'API et le JS correspondant pour faire ça pourrait s'inspirer de https://github.com/vollnhals/dependent-fields-rails

**Comment by yannski** [comment]
En fait, pas la peine de prendre en compte tous les cas pour le moment. Il suffit d'écrire le code JS spécifique à ce champ là en se basant sur ce qui a été fait pour les rôles employeurs https://github.com/betagouv/civilsdeladefense/blob/master/app/javascript/js/dependent-fields.js

**Comment by N1colas** [comment]
Questions: 
Q1:
Offre en CDI => duration_contract=null ou duration_contract=0

**Comment by yannski** [comment]
Le champ pourrait être de type string et donc chaîne vide par défaut par
exemple

**Comment by N1colas** [comment]
OK ! j'étais parti pour mettre un integer ou une date ! 
mais un String c'est encore + simple.

**Comment by N1colas** [comment]
![image](https://user-images.githubusercontent.com/6283122/45421392-27d95a80-b68d-11e8-82da-40bee335e09a.png)

est ce que la durée doigt apparaitre ici ?

**Comment by N1colas** [comment]
![image](https://user-images.githubusercontent.com/6283122/45421444-57886280-b68d-11e8-9fd7-d37de24348e7.png)

sur l'offre on doit l'affiché ? mais a quel place ? et quel logo utiliser ?

**Comment by N1colas** [comment]
je vous propose ce logo là (entre CDD et 01/01/2019)
![image](https://user-images.githubusercontent.com/6283122/45421568-bfd74400-b68d-11e8-9e23-7521dae677d5.png)

**Comment by yannski** [comment]
source de l'icône ? En général je regarde ici https://materialdesignicons.com/ et je sauvegarde la version SVG

**Comment by yannski** [comment]
En tout cas, je suis d'accord avec tes propositions sur le placement en Front

**Comment by N1colas** [comment]
je l'ai trouvé sur 
 https://fontawesome.com/icons/business-time?style=solid

**Comment by N1colas** [comment]
il me semble que tu m'avais it que tu triché avec les icons... mais je ne sais pas comment.

**Comment by yannski** [comment]
En fait je pense qu'une icône n'est pas nécessaire. Je propose d'afficher
"CDD 3 mois" et basta.

**Comment by N1colas** [comment]
pas de soucis 
autant ici
![](https://user-images.githubusercontent.com/6283122/45421392-27d95a80-b68d-11e8-82da-40bee335e09a.png)

que 

![](https://user-images.githubusercontent.com/6283122/45421444-57886280-b68d-11e8-9fd7-d37de24348e7.png)
