### ISSUE TITLE
Voir s'il est possible de supprimer le premier mail "Mot de passe modifié" lors de la confirmation de compte

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#202]

**Comment by Grainedepaillette** [comment]
@btrd Après test en production, le candidat ne reçoit effectivement plus courriel "Mot de passe modifié".

**Comment by Grainedepaillette** [comment]
@btrd Je ferme le ticket, car le PB venait bien du fait qu'il le recevait sans raison au moment de la création de son compte.
