### ISSUE TITLE
[Admin] Ajouter un sélecteur de date "visuel" pour le champ "date de début de contrat"

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#24]

**Comment by yannski** [comment]
avant de choisir une lib javascript pour créer ce datapicker, demandez moi mon avis, on évaluera cette biblithèque ensemble

**Comment by N1colas** [comment]
https://cdn.vaadin.com/vaadin-date-picker/3.2.0/demo/#date-picker-basic-demos

![image](https://user-images.githubusercontent.com/6283122/45353986-d497d700-b5bc-11e8-8440-8c3d3b952124.png)

celui ci est sympas
