### ISSUE TITLE
Informations supplémentaires pour récap journalier

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#255]
Type de notification | Contenu | Grand employeur | Employeur | ES | BRH | BANT | Remarques
-- | -- | -- | -- | -- | -- | -- | --
Avertissement PJ complet contrat |   |   |   |   |   | X | Rien jusqu’à retenu
Avertissement PJ complet dossier prise en charge |   |   |   |   | X |   |  

Voir #238 pour le début

**Comment by Grainedepaillette** [comment]
1ère piste, A CONFIRMER par le métier. 

Règles : 
Condition 1 : Si Candidat est retenu 
Condition 2 : Les PJ demandées ont été téléversées (dossier "complet") 
Action 1 : affichage dans le récap journalier du dossier complet du candidat sur l'offre + envoi aux destinataires : BANT + BRH. Pourquoi ne pas l'envoyer à tous les rôles ? 
Hypothèse 1 : si ajout d'une nouvelle P.J ou MAJ d'une P.J existante ALORS action 1 se répète à nouveau.

**Comment by btrd** [comment]
Closed pour ne conserver que ce ticket #238
