### ISSUE TITLE
Problème de notifications des acteurs quand connecté en tant qu'Employeur

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#297]
**Comportement actuel** 
PB N° 1 : Une fois les adresses intradef saisies, celles-ci s'ajoutent bien lorsque l'on clique sur le bouton "ajouter" mais ne s'enregistrent pas au moment de l'enregistrement et/ou publication de l'offre 
PB N° 2 : Impossibilité de renseigner plus d'un acteur par rôle. Ils ne peuvent pas renseigner 2 employeurs superviseurs par exemple. 

**Comportement souhaité** 
Enregistrement des acteurs saisies/ notifiés et possibilité d'ajouter plusieurs adresses intradef pour un même rôle.

**Comment by yannski** [comment]
Après avoir testé, je n'arrive pas à reproduire le problème...
