### ISSUE TITLE
La durée du contrat devrait être un paramètre du type de contrat

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#303]
Exemple:
CDD -> ajout de durée obligatoire
CDI -> pas d'ajout de durée
Détachement -> ajout de durée obligatoire

**Comment by Grainedepaillette** [comment]
Pour CDD : bloquer la saisie de l'onglet "durée du contrat"
- Pour les mois : de 1 à 12
- Pour les années de 1 à 6

**Comment by Grainedepaillette** [comment]
***Confort : 
Lorsque sélection "CDD" : apparition d'une astérisque à côté intitulé champ "durée de contrat" pour signifier que obligatoire

**Comment by Grainedepaillette** [comment]
Ajout de 3 niveaux de valeurs dans le champs : années + mois + jours

**Comment by btrd** [comment]
Si je comprends bien la demande il faut : 
- Ajouter dans `Paramètres -  Rédaction offres d'emploi` une section `Durées de contrat`
- Dans cette section avoir une liste de `Durées de contrat` et pouvoir ajouter des nouvelles durées
- Dans la section `Types de contrat` pouvoir ajouter un booléen pour définir si le type a une durée de contrat associé ou non
- À l'ajout d'une offre en fonction du type de contrat rendre obligatoire le choix d'une durée de contrat dans la liste

> Ajout de 3 niveaux de valeurs dans le champ : années + mois + jours
Un simple champ texte ne suffit pas ? Étant donné que ce sera une liste fixe qui ne risque pas de changer régulièrement.

**Comment by Grainedepaillette** [comment]
@btrd Oui c'est bien ça. 

Le champ texte existe déjà, le pb est que la saisie est libre (donc chaque recruteur renseigne la durée (en jour, mois ou année) et l'on perd en harmonie au niveau du descriptif de l'ensemble des offres (cf. vidéo) 

Si le champ correspond à un menu déroulant --> OK. Mais je comprends que le menu déroulant sera un menu par défaut et non pas paramétrable par le RF (BANT) ? Si tel est le cas, je dois les solliciter afin d'avoir la liste des durées souhaitées. 

https://user-images.githubusercontent.com/51794334/105194978-68d5b980-5b3a-11eb-8e85-bc216172fe79.mov

**Comment by btrd** [comment]
> Si le champ correspond à un menu déroulant --> OK. Mais je comprends que le menu déroulant sera un menu par défaut et non pas paramétrable par le RF (BANT) ? Si tel est le cas, je dois les solliciter afin d'avoir la liste des durées souhaitées.

Ce sera paramétrable par le RF.

**Comment by btrd** [comment]
## Gérer l'existant

- [ ] Garder la colonne `duration_contract` dans `JobOffer`
- [ ] Écrire un script de migration de données qui créé les `ContractDuration` à partir des `duration_contract`

@Grainedepaillette En production actuellement on a des données avec des doublons, tu veux garder quoi comme format ?

> [36 mois, 1 AN, 1 AN , 12 mois, , 3 ans, 2 ans, 36 mois , 6 mois, 1 an, 3 ANS, aaaaa, 36, 3 ans renouvelable, 3 ans renouvelables, 1 an renouvelable, 4 ans, 1 ans, 2 ans renouvelable, 1, 3 mois, 12 MOIS, 1 an , 6 mois renouvelable, 1an, 12 mois , 36 MOIS, 12 mois renouvelables, 36 ans, 5 ans max, 36 Mois]

**Comment by btrd** [comment]
@Grainedepaillette Je me permet de te relancer pour avoir la liste des durées de contrat ou le format que vous voulez suivre.

Ma proposition : `*nbr* (mois/ans) [renouvelable]` Ex: 6 mois renouvelables, 2 ans,  2 ans renouvelables, ...

Pour les mois on peut aller d'1 mois à 11 mois et pour les années de 1 an à 5 ans avec à chaque fois renouvelables ou non

**Comment by Grainedepaillette** [comment]
@btrd Désolée pour ce retour tardif. 
Je valide la proposition. 
Pour ce qui est des valeurs : il faudrait aller de 1 à 12 mois et de 1 à 6 ans.

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)
