### ISSUE TITLE
Non téléversement des PJ dans dossier candidat  par l'employeur et le candidat

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#307]
***Comportement constaté : 

Le candidat à téléverser ses PJ mais invalidation pour cause de non conformité par l'employeur . Le candidat puis l'employeur tente de téléverser la version conforme des documents mais cela ne fonctionne pas : message d'erreur apparaît (écrans ci -joint) 

***Comportement souhaité : 
Téléversement des PJ par le candidat ou l'employeur accepté par l'outil même si invalidation par l'employeur lors du 1er téléversement par le candidat 

![bug_pj](https://user-images.githubusercontent.com/51794334/61718138-a2214380-ad62-11e9-868d-4f74bf5539f6.png)

![bug_pj_2](https://user-images.githubusercontent.com/51794334/61718669-bdd91980-ad63-11e9-8ab7-947b5e3482cd.png)

**Comment by btrd** [comment]
@Grainedepaillette C'est encore d'actualité ?

**Comment by Grainedepaillette** [comment]
@btrd Non, je ferme le ticket
