### ISSUE TITLE
Lorsque je postule une nouvelle fois, je peux choisir CV et LM que j'ai envoyés à des offres auxquelles j'ai candidatées précédemment

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#311]

**Comment by Grainedepaillette** [comment]
![Exemple_Formulaire_candidature_sélection_CV_LM](https://user-images.githubusercontent.com/51794334/61806915-e252f580-ae38-11e9-813a-b061ec0a8532.png)

**Comment by btrd** [comment]
@Grainedepaillette Si l'utilisateur reprends un CV déjà existant et qu'il a déjà été validé, est-ce que l'on garde la validation ? Ou faut-il une validation par fichier ET candidature ?

**Comment by Grainedepaillette** [comment]
@btrd Il faut que le fichier soit à nouveau validé, même s'il a été repris et validé précédemment car 1 candidature = 1 poste = 1 recruteur et donc les infos présentes dans le CV doivent correspondre au poste (décisif dans l'estimation de la rémunération finale).

**Comment by btrd** [comment]
Disponible ici https://erecrutement-anssi-staging-pr871.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd En voulan tester la fonctionnalité en staging, un message d'erreur s'affiche lorsque l'on tente de postuler à une offre alors que l'on est connecté à son compte. 

En revanche, lorsqu'il s'agit de postuler pour la 1ère fois, l'accès au formulaire de candidature est opérationnel. 

https://user-images.githubusercontent.com/51794334/114214405-90cc0080-9964-11eb-8063-b1c9384d7934.mov

**Comment by btrd** [comment]
Ça a été compliqué mais c'est corrigé !

**Comment by Grainedepaillette** [comment]
@btrd 

Voici mes résultats après teste en pré-prod : 
Je visualise le menu déroulant affiché et les documents précédemment téléchargés. 
Les problématiques rencontrées : 

1. Lorsque je sélectionne un document présent dans le menu déroulant (existant car téléversé précédemment) pour le CV et la LM et que je tente de valider, un message d'erreur apparaît "veuillez compléter les champs ci - dessous) (cf. vidéo)
[Uploading... Non enregistrement CVLM existant.mov]

2. Lorsque je télé-verse  un nouveau document pour le CV et la LM et que je tente de valider, un message d'erreur apparaît "veuillez compléter les champs ci - dessous) (cf. vidéo)
[Uploading... Enregistrement nouveau CV + LM.mov]

Pour le 1 et 2 même en rafraîchissant la page ça ne fonctionne pas, je pense que c'est le même PB

3. Le titre du menu déroulant est en anglais " job applications file existing"

**Comment by Grainedepaillette** [comment]
Vidéo cas 1
https://user-images.githubusercontent.com/51794334/114432411-f5839700-9bc0-11eb-924e-2a368f5a7253.mov

**Comment by btrd** [comment]
> 3. Le titre du menu déroulant est en anglais "job applications file existing"

Je ne savais pas quoi mettre comme texte et j'ai oublié de te demander si toi tu en avais.

**Comment by btrd** [comment]
Le bug est corrigé ! (enfin)

**Comment by Grainedepaillette** [comment]
@btrd Top ça fonctionne en staging ! 

Pour le titre, pour conserver la même terminologie du bouton du dessus "choisir un fichier" je propose de mettre "choisir un fichier existant" pour le menu déroulant.

**Comment by Grainedepaillette** [comment]
En vérifiant ce ticket j'ai remarqué  qu'en production profite apparaît la mention "choisir un fichier" (pas le bouton) à droite  sans raison apparente (cf. écran) : que le fichier ne soit pas encore téléversé ou après qu'il ait été téléversé (cf. écrans). 

Est-ce possible de le traiter ou j'ouvre un ticket spécifique ? Merci 

### **ECRAN 1 : fichiers non télé-versés.** 

![Capture d’écran 2021-04-13 à 12.42.17.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/ff667a85-00b5-4ef7-9afe-beb54930c212)


### **ECRAN 2 : fichiers télé-versés**
![Capture d’écran 2021-04-13 à 12.37.18.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/c1cdc5d5-4b49-4867-b1aa-e4bdc0d79f23)

**Comment by btrd** [comment]
C'est corrigé via ce ticket justement

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel en staging

**Comment by Grainedepaillette** [comment]
@btrd En staging, un nouvel élément bloquant est apparu : lorsque je suis connecté à mon espace candidat et que je souhaite postuler à une nouvelle offre et que je sélectionne mon CV à partir du menu déroulant, alors quand je souhaite valider ma candidature, un message apparaît "veuillez choisir un fichier" au niveau du CV alors même que je l'ai sélectionné à partir du menu déroulant. Ce problème n'existe pour la LM. 

Capture d'écran : 
![Capture d’écran 2021-04-28 à 12.01.41.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/c33638e7-1354-425e-a5ce-dee84fca7911)
