### ISSUE TITLE
[Admin/Ajout vivier] si candidat existe déjà dans la liste, notification d'erreur explicite doit aparaître

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#341]
Ex: "Ce candidat existe déjà dans cette liste"

**Comment by Grainedepaillette** [comment]
@btrd Je ferme ce ticket, car plus pertinent au regard des derniers développements effectués : ajout de la page intermédiaire avec les liste alors que précédemment l'ajout à une liste se faisait directement à partir du bouton "mon vivier". 

![Capture d’écran 2021-04-26 à 13 47 32](https://user-images.githubusercontent.com/51794334/116077642-fd017080-a695-11eb-84e9-6bae500cd56b.png)
