### ISSUE TITLE
Offre publiée/onglet "description" (back) : titres s'affichent en anglais 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#355]
Bug détecté seulement en back office 
Toutes les offres sont concernées 

Référence offre pris en exemple : SIMU 1
URL : https://civilsdeladefense.fabnum.fr/admin/offresdemploi/charge-de-prevention-des-risques-professionnels

![Bugs_titres_anglais](https://user-images.githubusercontent.com/51794334/68841012-18580600-06c4-11ea-9ea9-2a70c5c08faf.png)

**Comment by yannski** [comment]
Fixed by https://github.com/betagouv/civilsdeladefense/commit/35ae0dcf41c1c5d28f5cee7f290b8637a70a324b
