### ISSUE TITLE
Créer un bouton pour faciliter le retour en haut de page 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#360]
- Bouton disponible quelle que soit la page de l'outil 
- Bouton présent tout au long de la navigation (emplacement : espace gris à gauche /droite ? )

**Comment by btrd** [comment]
@yannski Tu pourrais t'en occuper ? Ce sera peut-être plus simple à faire en même temps que le nouveau design

**Comment by btrd** [comment]
C'est fait

**Comment by Grainedepaillette** [comment]
@btrd en staging, en back office, le bouton n'est visible qu'au niveau de la page d'authentification de la page admin (cf. écran) mais pas sur les autres pages (offres, stats, etc)![Capture d’écran 2021-06-18 à 00.29.47.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/06c5e4ed-3f1a-439e-84a2-4a996331db44)

En front c'est ok

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd le bouton est bien visible en back office en staging sur les différentes pages de l'outil mais il saute cf. vidéo https://images.zenhubusercontent.com/146276066/3942336a-3b89-4f2f-b17d-c0b89e33299e/bouton_haut_de_page_.mov

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel après test en staging sur l'ensemble des pages en BO
