### ISSUE TITLE
Déplacer tous les filtres à gauche de l'écran + option filtres "volants" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#361]
Les filtres doivent être disponibles peu importe le niveau de la page auquel l'utilisateur se situe (haut, milieu, bas). 
Exemple : boutiques en ligne

**Comment by btrd** [comment]
@Grainedepaillette Ce serait possible de me faire une capture d'écran de la page en question ?

**Comment by Grainedepaillette** [comment]
@btrd ce ticket concerne plusieurs pages du site (toutes celles où il y a 1 barre de recherche + des filtres) : 
En BACK : la page "Offres" ; la page "Vivier" et la page "Statistiques" 
En FRONT : la page d'accueil 

Un seul écran designé correspond à ce ticket (écran ci - dessous) MAIS seuls les filtres sélectionnés apparaissent sur la colonne à gauche, mais il faudrait également que les filtres (menus déroulants apparaissent) à gauche. 
Si tu as besoin de + de précisions, n'hésite pas. 

Réf. FIGMA " A1_Offres" : 
![A1_Offres actives](https://user-images.githubusercontent.com/51794334/105189227-08904900-5b35-11eb-99fa-2b9081ef5c84.png)

**Comment by btrd** [comment]
J'ai fait une proposition plus simple à mettre en place (1h au lieu de 2/3jours de travail) ici https://erecrutement-anssi-staging-pr922.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Je viens de checker l'environnement mais je ne vois pas de différences au niveau des filtres. Pourrais-tu m'indiquer la page où se trouve les nouveaux éléments ? Merci.

**Comment by btrd** [comment]
Sur la première page https://erecrutement-cvd-staging-pr922.osc-fr1.scalingo.io/admin
Quand tu scroll la bar de recherche reste afficher en haut.

<img width="1152" alt="Capture d’écran 2021-04-29 à 13 03 27" src="https://user-images.githubusercontent.com/1385737/116541085-4b5b7d00-a8eb-11eb-9505-51aa37ec6421.png">

**Comment by Grainedepaillette** [comment]
@btrd Merci ! Effectivement ! Ça me convient.  
Ce ticket comportait également l'affichage des filtres sélectionnés (cf. design), avec le système proposé on pourrait les afficher au dessous de la barre de recherche et des filtres. 
Qu'en penses - tu ?

**Comment by btrd** [comment]
<img width="1089" alt="Capture d’écran 2021-05-03 à 15 34 17" src="https://user-images.githubusercontent.com/1385737/116882733-115ce480-ac25-11eb-8d78-a6554454cf80.png">

Je trouve ça redondant avec la liste là, mais je connais moins l'usage des recruteurs que toi.

**Comment by Grainedepaillette** [comment]
@btrd Oui effectivement. Ce qui peut être bloquant c'est de retourner sur chaque menu déroulant (clic) et faire défiler la sélection. Te propose de laisser en l'état actuel et de voir à l'usage si l'on a des retours.

**Comment by mch2608** [comment]
Après vérification, la barre de recherche avec les filtres ne se maintient que sur la page des offres. La fonctionnalité doit aussi apparaître sur la page Vivier et Statistiques.

**Comment by btrd** [comment]
C'est corrigé !
