### ISSUE TITLE
Expiration session utilisateur : rallonger délai avant expiration

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#363]
Problématiques : 
- Augmenter le délai d'expiration et passer de 30min à 1h voire 2h ? 
- A quelle moment considéré comme inactivité ? (absence de rédaction texte, clic souris) 
- Sauvegarde des actions menées avant expiration ?

**Comment by yannski** [comment]
Action : déjà modifier le timeout à 1h
