### ISSUE TITLE
Templates courriel : contenu ne s'affiche pas lorsque sélection du modèle

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#364]

**Comment by yannski** [comment]
Fonctionne quand on recharge la page concernée. Sans doute problème de chargement Javascript avec Turbolinks.

**Comment by yannski** [comment]
Comment reproduire : Vivier > Carte candidat > Courriels > Sélectionner un modèle de courriel.

Autre façon : Offres > Afficher une offre > Candidatures (Trello) > Carte candidat > Courriels > Sélectionner un modèle de courriel.
