### ISSUE TITLE
Intitulé offre : bloquer les parenthèses dans le champ + inscrire en dur la mention "F/H"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#376]

**Comment by btrd** [comment]
@Grainedepaillette Bonjour, tu entends quoi par `inscrire en dur la mention "F/H"` ?

Si je pré-rempli le champ avec `F/H` et que j'empêche la création (ou la mise à jour) de l'offre dans le cas où le titre ne fini pas par `F/H` c'est ok pour toi ?

**Comment by Grainedepaillette** [comment]
@btrd Bonjour, l'idée est que lorsqu'une offre est créée (enregistrée en format brouillon ou publiée) la mention F/H soit présente à la suite de l'intitulé de l'offre. Oui le système que tu proposes me convient. 

Pour mon info, si la mention F/H n'apparaît pas et que le recruteur souhaite enregistrer l'offre, est- ce que le message d'erreur indiquera pourquoi ?

A ta dispo, si tu as besoin de plus d'explications.

**Comment by btrd** [comment]
Super

<img width="477" alt="Capture d’écran 2021-01-18 à 15 36 50" src="https://user-images.githubusercontent.com/1385737/104928469-fe3e4580-59a2-11eb-8f95-c0e3143de23e.png">

Ça va ressembler à ça.

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)

**Comment by Grainedepaillette** [comment]
@btrd Voici les règles de gestion :

- Si le recruteur créé une nouvelle offre ALORS la restriction relative aux parenthèses s'impose
- Si le recruteur modifie une offre publiée (créée avant la mise en place de la restriction) ALORS la restriction ne s'impose pas.
- Si le recruteur republie une annonce archivée, brouillon ou mise en pause (créée avant la mise en place de la restriction) ALORS la restriction ne s'impose pas.

Peut-être aurais-tu besoin d'une date précise à partir de laquelle les offres doivent respecter la restriction ?

**Comment by btrd** [comment]
Envoyer la liste des offres avec des parenthèses à Sarah.

**Comment by btrd** [comment]
@Grainedepaillette Je dois toujours vous envoyer la liste ou c'est ok ?

**Comment by Grainedepaillette** [comment]
@btrd Preneuse de la liste oui, afin que l'on puisse communiquer et que les modifications soient faites en amont avant que les utilisateurs soient contraints.

**Comment by btrd** [comment]
Envoyé sur Mattermost

**Comment by btrd** [comment]
@mch2608 Disponible https://erecrutement-cvd-staging-pr957.osc-fr1.scalingo.io/

**Comment by mch2608** [comment]
Opérationnel
