### ISSUE TITLE
Front/ Page accueil : La barre de recherche doit prendre en compte le contenu des offres et les caractères spéciaux (accents) 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#380]
Testé en production 
**Comportement constaté :** 
Lorsqu'un utilisateur saisit du texte dans la barre de recherche alors : 
- non prise en compte des informations contenues dans les offres (seuls les intitulés des offres sont pris en compte) 
- non prise en compte des caractère spéciaux type accents 

**Comportement souhaité** : Avoir une barre de recherche (moteur de recherche) plus performant permettant de faire de la recherche sur toute la page (intitulés + contenus des offres d'emploi) et avoir des résultats que l'utilisateur saisisse des accents ou pas.

**Comment by btrd** [comment]
Disponible en staging

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel
