### ISSUE TITLE
Comptes admin : erreur intitulé 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#385]
Ajouter un "p" à "comte désactivé"

**Comment by Grainedepaillette** [comment]
![Parametres_intitulé_compte](https://user-images.githubusercontent.com/51794334/71002120-f0066180-20de-11ea-8ebe-e5423064bd77.png)

**Comment by yannski** [comment]
Avait été réglé par a1c038a5385ea22d5013d0ff8f3e69d6572494f3
