### ISSUE TITLE
Rédaction offre/ notifs acteurs : non enregistrement des adresses saisies 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#390]
cas rencontré pour : 
-  GE
- ES 
- RH de proximité( lorsque ce n'est pas l'employeur) 

Les adresses ne s'enregistrent pas lorsque clic sur bouton "ajouter" : cas rencontré pour les GE, ES et RH de proximité lorsque ce n'est pas un employeur

**Comment by yannski** [comment]
On est bien d'accord qu'il faut cliquer sur "Ajouter" pour chaque adresse, puis cliquer sur "Sauvegarder" tout en bas du formulaire ?

**Comment by Grainedepaillette** [comment]
Je confirme
