### ISSUE TITLE
Carte candidat : non enregistrement du motif de refus une fois sélectionné 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#392]
Si candidature refusée (refusée ou refusée après entretien tel) + sélection du motif de refus : le motif de refus s'affiche une fois sélectionné. 
Mais  lorsque l'on : 
- quitte la page (exemple : retour à la page principale : clic onglet "Viviers") et que l'on tente d'accéder à nouveau à la carte candidat en question 
- ou que l'on réactualise la même page

Alors le motif de refus sélectionné initialement n'apparaît pas.

**Comment by Grainedepaillette** [comment]
@yannski Je réouvre le ticket car en production le motif de refus une fois sélectionné ne s'enregistre pas.

PB : 
- Utilisateur sélectionne le motif de refus mais non enregistrement du motif sélectionné
- Si utilisateur actualise/rafraîchit la page et sélectionne à nouveau le motif de refus : le motif sélectionné s'enregistre

**Comment by Grainedepaillette** [comment]
@yannski Problème présenté en décembre 2019 (cf. 1er commentaire du ticket) constaté à nouveau en production sur cette fonctionnalité. 

Rôles concernés : BANT, employeur et RH de proximité

**Comment by mch2608** [comment]
@yannski réouverture du ticket car : 
- PB1 : utilisateur sélectionne "Refusé" mais apparition du champ "Motif de refus" seulement après rafraîchissement de la page 
- PB2 : utilisateur sélectionne son motif de refus mais enregistrement de la sélection seulement après rafraîchissement de la page

**Comment by Grainedepaillette** [comment]
- Testé en pré-production 
- Rôle : BANT, Employeur 

- Comportement constaté : à partir de la carte candidat lorsque je sélectionne l'état de la candidature (refusé ou refusé après entretien tél.) de la candidature (1er menu déroulant), le motif de refus (2ème menu déroulant) n'apparaît pas (automatiquement). Il est nécessaire de rafraîchir la page ou quitter puis revenir sur la page pour qu'il apparaisse. 

- Image sans rafraîchissement de la page : 

![Refus 1](https://user-images.githubusercontent.com/51794334/102594508-97650c80-4116-11eb-8f46-7f7b2320e3f5.png)

- Image après rafraîchissement de la page : 

![refus 2](https://user-images.githubusercontent.com/51794334/102594530-9c29c080-4116-11eb-9004-28b72a0a5561.png)

- Comportement souhaité : affichage automatique du motif de refus lorsque l'état de la candidature (refusé/refuse après entretien tél.) est sélectionné.

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)

**Comment by mch2608** [comment]
Réouverture du ticket car après constats en pré-prod et en prod: 

**PB1** : Lorsque l'utilisateur sélectionne un motif de refus d'un candidat "Refusé", le motif de refus s'enregistre mais la coche verte n'apparait qu'après actualisation de la page 


https://user-images.githubusercontent.com/58481185/115534335-f63ebc00-a297-11eb-8fc5-70587187c692.mov



**PB2** : Lorsque l'utilisateur sélectionne un motif de refus d'un candidat "Refusé après entretien tel" ou "Rencontré mais refusé", le motif de refus ne s'enregistre pas et disparaît après actualisation 

**Comportements souhaités** : 
- Lorsque sélection d'un motif de refus --> enregistrement du motif de refus et apparition instantanée de la coche verte pour tous les cas de refus 

https://user-images.githubusercontent.com/58481185/115535322-ed021f00-a298-11eb-9dd5-65f1e1a60513.mov

**Comment by Grainedepaillette** [comment]
@btrd Possible de le traiter en P0 dans le SPRINT ? PTI, c'est un bug récurrent. cf. détails du bug ci - dessus.

**Comment by btrd** [comment]
J'ai corrigé PB2 qui me semble plus problématique.

Pour PB1 je viens bien un nouveau ticket.

**Comment by Grainedepaillette** [comment]
@btrd C'est bien pris en compte.

**Comment by Grainedepaillette** [comment]
@btrd Après test en staging le PB2 persiste.

**Comment by btrd** [comment]
C'est corrigé, petite erreur de ma part

**Comment by Grainedepaillette** [comment]
@btrd je viens de tester à nouveau, cela fonctionne !

**Comment by Grainedepaillette** [comment]
@btrd Est-ce possible de le passer directement en production sans attendre la fin du Sprint ?

**Comment by Grainedepaillette** [comment]
@mch2608 pourrais-tu ouvrir un nouveau ticket pour le PB 1 ? (cf. échanges supra) Merci !

**Comment by mch2608** [comment]
C'est fait : ticket #964
