### ISSUE TITLE
Implémenter 2FA pour l'authentification

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#430]
En attente spec sur les devices/méthodes à supporter.

**Comment by B611** [comment]
Je suggère d’implémenter l’authentification à 2 facteurs en utilisant le TOTP (Time-based One-time Password algorithm https://tools.ietf.org/html/rfc6238 ). Le TOTP est plus sécurisé que le HOTP ou qu’envoyer un code par SMS/email.

Ce protocole d’authentification à 2 facteurs est déjà très utilisé dans l’industrie (Protonmail, Github, Amazon…), et est compatible avec les applications d’authentification majeures comme Authy ou Google Authenticator, ainsi que leurs alternatives open-source, tels que andOTP ou FreeOTP. Le TOTP est également supporté par les gestionnaires de mots de passe majeurs.

Il existe des librairies Ruby permettant de mettre cela en place rapidement, celle-ci est très utilisée : https://github.com/mdp/rotp

**Comment by yannski** [comment]
Pas de reco d'outils TOTP ?

**Comment by yannski** [comment]
Je veux dire l'ANSSI est OK avec Google Auth ?

**Comment by B611** [comment]
L'outil utilisé pour le TOTP dépend de l'utilisateur, les sites qui implémentent le TOTP sont compatibles avec tous les clients supportant ce standard.

L'ANSSI préfère sûrement un client open-source tel que andOTP ( https://github.com/andOTP/andOTP )
