### ISSUE TITLE
Implémenter France Connect pour les candidats

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#431]

**Comment by Grainedepaillette** [comment]
@btrd Serait-il possible de faire apparaître bouton FC sur le formulaire de candidature ? Pour rappel, il avait été retiré car il y pas opérationnel (rien ne se passait lorsqu'on cliquait dessus) je ne sais pas si tu as pu travaillé sur le sujet depuis. 
SI tu le souhaite je peux réouvrir le ticket ou en ouvrir un nouveau. Merci

**Comment by btrd** [comment]
Effectivement, j'ajoute ce ticket au sprint 2.

**Comment by btrd** [comment]
@Grainedepaillette J'ai trouvé une solution, j'ai bougé l'url pour postuler de `/offresdemploi/responsable-adjoint-de-la-communication-f-h/apply` à `/offresdemploi/apply?id=responsable-adjoint-de-la-communication-f-h` ce qui permettra d'activer FranceConnect sur cette page en production (le problème n'existe pas en staging).

J'ai redirigé l'ancienne URL vers la nouvelle.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr920.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd J'ai testé, la disposition du bouton convient ! Par contre, lorsque je clique sur le bouton France Connect, rien ne se passe.

**Comment by btrd** [comment]
@Grainedepaillette C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd après test c'est opérationnel
