### ISSUE TITLE
Back / Modification d'offre : apparition de caractères spéciaux dans les zones de texte 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#439]
A partir d'un compte BANT, clic sur "Modifier" une offre en état brouillon, archivée ou publiée.
Sur la page modification de l'offre, il apparaît des caractères spéciaux dans les zones de textes (descriptif de l'offre, profil recherché et process de recrutement). 
 
![image](https://user-images.githubusercontent.com/58481185/72797428-65ff6a80-3c41-11ea-8ce4-e2925ff613ac.png)

Côté front, les textes apparaissent normalement, sans présence de caractères spéciaux. 

![image](https://user-images.githubusercontent.com/58481185/72797451-71eb2c80-3c41-11ea-8afb-160fa8b04cf1.png)

**Comment by yannski** [comment]
C'est un problème de chargement de l'éditeur visuel. Il faudrait me donner une méthode reproductible pour faire apparaitre ce bug. Dans l'intervalle, recharger la page fera appaitre correctement l'éditeur visuel.

**Comment by mch2608** [comment]
![image](https://user-images.githubusercontent.com/58481185/72974396-367e6880-3dcf-11ea-9619-e4925063553a.png)
Apres un clic sur l'offre "Chargé de projets en Maîtrise d'oeuvre (conducteur de travaux) F/H" pour exemple puis un clic sur "modifier"
![image](https://user-images.githubusercontent.com/58481185/72974527-6b8abb00-3dcf-11ea-8651-4a8e089d41ee.png)
Il apparaît les caractères spéciaux dans les zones de texte. 

Après une actualisation de la page, le texte saisi apparait bien normalement.

**Comment by btrd** [comment]
@mch2608 Je me permet de fermer, si le bug est toujours existant ne pas hésiter à rouvrir le ticket

**Comment by mch2608** [comment]
Ok ! Bug non aperçu depuis des mois.
