### ISSUE TITLE
Rédaction offre/ Description : Limiter la saisie à 1050 caractères et l’indiquer par un message 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#441]
- [x] Limite des tailles des champs :
- Titre 70
- Description de l’offre 2000
- Description de l'entreprise/organisation 1000
- Profil recherché 1000
- Process de recrutement 700

- [x] Ajouter un compteur de caractères sur les champs.
- [x] Autoriser la dé-publication
- [x] Envoyer la liste des offres non valides et publiés

**Comment by mch2608** [comment]
Impossible de tester en pré-prod car un message d'erreur s'affiche lorsqu'on clique sur "Enregistrer" ou "Publier". Il y a t-il un lien avec la fermeture de ce ticket ? 
![limitation caractere](https://user-images.githubusercontent.com/58481185/105200620-53638e00-5b40-11eb-8e7c-439aaa792dc6.PNG)

**Comment by btrd** [comment]
@mch2608 C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd Voici les règles de gestion : 
- Si le recruteur créé une nouvelle offre ALORS la règle des 1000 caractères s'impose 
- Si le recruteur modifie une offre publiée (créée avant la mise en place de la limitation) ALORS la limitation ne s'impose pas. 
- Si le recruteur republie une annonce archivée, brouillon ou mise en pause (créée avant la mise en place de la limitation) ALORS la limitation ne s'impose pas. 

Peut-être aurais-tu besoin d'une date précise à partir de laquelle les offres doivent respecter la limitation ? 

En parallèle, le nombre de caractères risque sûrement de changer, car nous avons eu de nombreux retour de la part des utilisateurs.

**Comment by btrd** [comment]
Vérifier le nombre de caractères avec Broadbean et ajouter des limites pour la partie Profil recherché, Process de recrutement et le titre.

**Comment by btrd** [comment]
Limite des tailles des champs :
Titre : 70
Description de l’offre : 2000
Description de l'entreprise/organisation : 1000
Profil recherché : 1000
Process de recrutement : 700

Ajouter un compteur de caractères sur les champs.
Autoriser la dé-publication
Envoyer la liste des offres non valides et publiés

**Comment by Grainedepaillette** [comment]
@btrd est-ce que tu veux un ticket pour pour la limitation chaque champ du formulaire ?

**Comment by btrd** [comment]
Je préfère un ticket avec toutes les règles, merci

**Comment by Grainedepaillette** [comment]
@btrd Opérationnel en review app

**Comment by btrd** [comment]
- [ ] Extraire la liste des offres non valide

**Comment by Grainedepaillette** [comment]
Comme convenu, j'ajoute au ticket l'action suivante : 

- [ ] Extraire la liste des employeurs pour chaque offre non valide de la liste communiquée

**Comment by mch2608** [comment]
- Extrait de la liste des employeurs pour chaque offre non valide de la liste communiquée --> Sprint 2 
- Ticket 441 en tant que tel sur la limitation de caractère --> Sprint 3

**Comment by btrd** [comment]
Liste envoyé à @Grainedepaillette

**Comment by Grainedepaillette** [comment]
Campagne de communication démarrée le 04.05

**Comment by Grainedepaillette** [comment]
@btrd Campagne finalisée, prêt à être déployé. Je ferme le ticket.
