### ISSUE TITLE
Offre archivée : indiquer la date et le motif d'archivage 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#444]
Manière d'obtenir le motif d'archivage à discuter. 
Proposer une liste déroulante des motifs à chaque clic sur "Archiver" ?

**Comment by Grainedepaillette** [comment]
@btrd voici quelques précisions 

### **Comportement constaté :** 
Aujourd'hui, lorsqu'une offre est archivée en back office, il n'existe aucune indication relative à la date d'archivage et le motif de l'archivage au niveau de la cartouche de l'offre. Les utilisateurs n'ont pas la possibilité de situer l'action dans le temps et de connaître les motifs de réalisation de l'action. 

### **Comportement souhaité :**

- Pouvoir visualiser la date d'archivage : comme c'est le cas pour la date de publication d'une offre, enregistrer et afficher la date d'archivage de l'offre au niveau du cartouche offre. 
- Pouvoir saisir et enregistrer le motif d'archivage d'une offre : pouvoir sélectionner un motif d'archivage (cf. système pour le motif de refus) à partir d'un menu déroulant (alimenté au niveau des paramètres par l'admin), enregistré le motif et l'afficher au niveau du cartouche de l'offre.

**Comment by jrmlnzz** [comment]
@sebastiencarceles je pense que celui-ci peut être pratique pour les users

**Comment by sebastiencarceles** [comment]
> Pouvoir visualiser la date d'archivage : comme c'est le cas pour la date de publication d'une offre, enregistrer et afficher la date d'archivage de l'offre au niveau du cartouche offre.

En fait la date affichée ici est la date à laquelle l'offre est passée dans l'état actuel. Donc par exemple si elle a été publiée le 06/07/2022, et qu'elle est toujours en état "Publiée", alors la date de publication s'affiche : 
![image](https://user-images.githubusercontent.com/1193334/177505184-2b34b34b-cbea-4abe-ac77-2946fa29b1c5.png)

En conséquence, pour une offre archivée, c'est bien la date d'archivage qui est affichée ici : 
![image](https://user-images.githubusercontent.com/1193334/177504969-3ff2c080-fc0e-4afa-a33f-86754dbe734a.png)

Je me penche sur la deuxième partie du ticket maintenant, à savoir le motif d'archivage.
