### ISSUE TITLE
Création d'offre : non publication des offres

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#470]
Après la saisie de tous les champs pour la rédaction d'une nouvelle offre, un message d'erreur s'affiche, que les acteurs soient notifiés ou non. 

![image](https://user-images.githubusercontent.com/58481185/73928620-b3cbd200-48d3-11ea-86c8-6ffc3a0216d0.png)
![image](https://user-images.githubusercontent.com/58481185/73928648-c2b28480-48d3-11ea-9e01-f22c8ca405ef.png)

Après le message d'erreur, si on clique sur bouton "enregistrer", "modifier" ou "mettre en pause" un nouveau message d'erreur apparaît.
![image](https://user-images.githubusercontent.com/58481185/73928695-d231cd80-48d3-11ea-9ab2-8d7857a366c4.png)
 
La modification d'une offre déjà publié ou en état brouillon et la publication d'une offre en état brouillon sont opérationnelles (et ce, même après la notification de nouveaux acteurs).

**Comment by yannski** [comment]
Je pense qu'il s'agit ici d'un autre problème. Il y avait un conflit d'identifiant pour les annonces liées à l'employeur DIRISI. J'ai réglé le problème ne modifiant l'annonce "problématique".

Je ferme le ticket. N'hésite pas à réouvrir si tu arrives à reproduire le problème.
