### ISSUE TITLE
Back/Courriel : non confirmation de l'envoi d'un courriel avec PJ

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#471]
Après avoir cliquer sur le bouton "Envoyer au candidat", le courriel n'apparaît pas dans la zone de messagerie prévue. L'employeur n'a aucune indication concernant l'envoi du courriel. 
![image](https://user-images.githubusercontent.com/58481185/73947164-577aa980-48f7-11ea-8edf-f87747e2e724.png) 
En front le candidat reçoit le courriel. 
![image](https://user-images.githubusercontent.com/58481185/73947239-6feac400-48f7-11ea-985b-c41ab97daa52.png)
 Après actualisation de la page en back, le courriel apparaît dans la zone de messagerie. 
![image](https://user-images.githubusercontent.com/58481185/73947293-8264fd80-48f7-11ea-949c-ae3ce8cf1057.png)

**Comment by mch2608** [comment]
Lorsque le courriel ne comporte pas de PJ, l'envoi du mail et son apparition instantanée dans la zone de messagerie sont opérationnels.

**Comment by Grainedepaillette** [comment]
Tests réalisés en production : 
- lorsque le candidat consulte ses courriels à partir de son espace candidat : le courriel a bien été transmis et le candidat le visualise mais il n'y a pas de P.J
- lorsque le candidat consulte ses courriels à partir de sa messagerie personnelle : le courriel n'a pas été été transmis

**Comment by Grainedepaillette** [comment]
Nouveau test réalisé en production le 1.04.2021 : 

- lorsque le candidat consulte ses courriels à partir de son espace candidat : le courriel a bien été transmis et le candidat le visualise mais il n'y a pas de P.J
- lorsque le candidat consulte ses courriels à partir de sa messagerie personnelle : le courriel a été été transmis et le candidat a bien reçu la P.J et peut la télécharger. 

Action de correction à effectuer : visualiser la P.J également à partir de l'espace candidat/onglet courriel de la candidature

**Comment by Grainedepaillette** [comment]
@Grainedepaillette

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr973.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Après vérification, 
- Sur messagerie personnelle : le candidat reçoit le courriel, peut visualiser la PJ et la télécharger 
- Sur onglet "Mes échanges" de l'espace candidat : le candidat reçoit le courriel mais ne visualise pas la PJ 

<img width="1440" alt="Capture d’écran 2021-05-25 à 11 10 31" src="https://user-images.githubusercontent.com/58481185/119471713-d7758e80-bd49-11eb-8171-67c042881150.png">
<img width="1440" alt="Capture d’écran 2021-05-25 à 11 10 22" src="https://user-images.githubusercontent.com/58481185/119471721-d80e2500-bd49-11eb-900f-f644a96d9200.png">

Action de correction à effectuer identique au 1er avril : visualiser la P.J également à partir de l'espace candidat/onglet courriel de la candidature

**Comment by btrd** [comment]
C'est corrigé

**Comment by mch2608** [comment]
La PJ apparaît bien avec le message. Lorsqu'on clique sur le lien de la PJ, un onglet s'ouvre et se charge. Mais la PJ n'apparait jamais. Le fichier ne s'ouvre également pas avec Preview.  (test réalisé avec deux PC différents)

https://user-images.githubusercontent.com/58481185/121538110-cf357880-ca04-11eb-8478-2e8574a49c22.mov

**Comment by btrd** [comment]
@mch2608 Tu tests avec quel compte ?

**Comment by mch2608** [comment]
J'ai testé avec le compte BANT : cvd_bant@example.com

**Comment by btrd** [comment]
Est-ce qu'on doit laisser la possibilité pour les utilisateurs d'envoyer plusieurs documents ou un seul c'est ok ?

De plus on n'enregistre pas les documents quand le message est envoyé par email (et pas via le site).

Est-ce normal ?

**Comment by mch2608** [comment]
1. Oui, les utilisateurs sont censés avoir la possibilité d'envoyer plusieurs documents. 
2. Je ne suis pas sur de saisir la question.

**Comment by btrd** [comment]
- Gérer les pièces jointes envoyer par emails
- Gérer plusieurs pièces jointes

Voir combien de temps ça prends

**Comment by btrd** [comment]
@Grainedepaillette Une journée devrait suffire pour gérer ça

**Comment by Grainedepaillette** [comment]
@btrd Top ce serait bien que ce soit traité avant la fin du projet, je vais le positionner dans un sprint

**Comment by btrd** [comment]
Je me permet de fermer ce ticket pour mieux le définir https://github.com/betagouv/civilsdeladefense/issues/1029
