### ISSUE TITLE
Ajouter champ "souhait(s) géographique(s) (département)"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#476]
Information non obligatoire pour postuler. 
Seule saisie d'un département est valide. 
Format : champ libre + autocomplétion (algolia)

Ajouter sur les pages : Front/Formulaire candidature, Front/Espace candidat, Back/Carte candidat

Design associé :
![EXPORTS_CIVIL2-1 copie](https://user-images.githubusercontent.com/51794334/74322871-e61e7900-4d84-11ea-8fa5-a496972cdf4c.jpg)

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr955.osc-fr1.scalingo.io

**Comment by btrd** [comment]
@mch2608 Disponible ici https://erecrutement-cvd-staging-pr955.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Peut-on changer l'intitulé pour garder celui proposé par Sarah ? Avec l'intitulé de l'environnement, les candidats risquent de comprendre qu'on leur demande leur département dans lequel il réside et ne pas comprendre pourquoi on leur propose d'ajouter un département. Sinon la fonctionnalité est opérationnelle.
