### ISSUE TITLE
Ajouter champ "disponibilité" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#477]
- **Donnée liée au PROFIL ** 
- **Donnée existe déjà en back/carte candidat**
- **Ajout au niveau des pages :** 
- Front/Formulaire candidature : **Information NON OBLIGATOIRE pour postuler.** Sera auto-incrémentée dans le formulaire une fois saisie par le candidat une 1ère fois. 
- Front/Espace candidat : [#483] 

**Règles :**
- Général : la dernière donnée renseignée par le candidat (dernière action sur une donnée) est celle qui doit apparaître en front et en back.
- Si la donnée est renseignée dans le formulaire de candidature ALORS elle alimente l'espace candidat + la carte candidat
- Si la donnée est renseignée à partir de l'espace candidat ALORS elle alimente la carte candidat.

**Format : liste déroulante :** 
- "En poste" 
- "Disponible immédiatement" 
- "Disponible sous 1 mois"
- "Disponible sous 2 mois" 
- "Disponible sous 3 mois ou plus" 

![Capture d’écran 2021-04-12 à 09 18 28](https://user-images.githubusercontent.com/51794334/114355734-1e2f7080-9b70-11eb-97ec-5bb0a8af74fe.png)

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr891.osc-fr1.scalingo.io
