### ISSUE TITLE
Ajouter champ "niveau études" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#478]
- Information obligatoire pour postuler.
- Ajout au niveau des pages : Front/Formulaire candidature ; Front/Espace candidat.
- Cette donnée existe déjà en Back/ Carte candidat (cf. écran) 

![Capture d’écran 2021-04-12 à 09 26 06](https://user-images.githubusercontent.com/51794334/114356896-63a06d80-9b71-11eb-985f-934d40823e02.png)

Format : liste déroulante. Le contenu de la liste doit correspondre au référentiel alimenté au niveau des paramètres par le RF : https://contractuels.civils.defense.gouv.fr/admin/parametres/study_levels

**Règles :**
- Général : la dernière donnée renseignée par le candidat (dernière action sur une donnée) est celle qui doit apparaître en front et en back.
- Si la donnée est renseignée dans le formulaire de candidature ALORS elle alimente l'espace candidat + la carte candidat
- Si la donnée est renseignée à partir de l'espace candidat ALORS elle alimente la carte candidat.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr891.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd En testant le ticket sur les langues, je me suis aperçu en staging que les informations obligatoires et non obligatoires dans le formulaire de candidature ne correspondent pas aux mentions dans les tickets : **l'expérience est OBLIGATOIRE, il faut donc ajouter l'astérisque avant le passage en prod. Merci.**
