### ISSUE TITLE
Ajouter champ "expérience" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#479]
- **Donnée liée au PROFIL ** 
- **Donnée existe déjà en back/carte candidat**

### **Comportement actuel :**
- Le candidat n'a pas la possibilité de renseigner cette information depuis le formulaire de candidature et l'espace candidat.
- Elle existe déjà en Back/ Carte candidat (cf. écran) et ne peut être alimenté que par les recruteurs. 
![Capture d’écran 2021-04-12 à 10 03 18](https://user-images.githubusercontent.com/51794334/114361367-5639b200-9b76-11eb-9458-556624f45d0b.png)

### **Comportement souhaité :**
- Donner également la possibilité au candidat de renseigner cette information à partir du formulaire de candidat. 
- Ajouter la liste déroulante afin que le candidat puisse renseigner cette donnée.

### **Emplacement :** 
- Ajout au niveau des pages : Front/Formulaire candidature : **Information NON OBLIGATOIRE pour postuler.** Sera auto-incrémentée dans le formulaire une fois saisie par le candidat une 1ère fois. 

### **Règles :**
- Général : la dernière donnée renseignée par le candidat (dernière action sur une donnée) est celle qui doit apparaître en front et en back.
- Si la donnée est renseignée dans le formulaire de candidature ALORS elle alimente l'espace candidat + la carte candidat
- Si la donnée est renseignée à partir de l'espace candidat ALORS elle alimente la carte candidat.
- Si la donné est alimentée/modifiée par le recruteur en back via la carte candidat ALORS elle modifie les informations en front/espace candidat

### **Format :** 
Liste déroulante. Le contenu de la liste doit correspondre au référentiel alimenté au niveau des paramètres par le RF : https://contractuels.civils.defense.gouv.fr/admin/parametres/experience_levels

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr891.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd En testant le ticket sur les langues, je me suis aperçu en staging que les informations obligatoires et non obligatoires dans le formulaire de candidature ne correspondent pas aux mentions dans les tickets : **l'expérience est NON obligatoire, il faut donc retirer l'astérisque. Merci.**
