### ISSUE TITLE
[Admin] Adapter le listing des admins avec le design de référence

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#48]
![8a_membres](https://user-images.githubusercontent.com/11287/45365401-be9a0e80-b5dc-11e8-8262-23b7f5eda22e.png)

**Comment by N1colas** [comment]
Me confirmer :  il faut ajouter une contrainte Obligatoire sur employer.

**Comment by yannski** [comment]
L'employeur n'est pas nécessairement présent (cas des BANT par exemple).

**Comment by N1colas** [comment]
Ok, super. J’avais un doute avec notre seed où effectivement le BANT est vide et la maquette.
