### ISSUE TITLE
Ajouter champ "langue étrangère" + "niveau"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#481]
- **Donnée liée au PROFIL ** 
- **Donnée nouvelle à créer **
- **Ajout au niveau des pages :** 
- Front/Formulaire candidature : **Information NON OBLIGATOIRE pour postuler.** Sera auto-incrémentée dans le formulaire une fois saisie par le candidat une 1ère fois. 
- Back/Carte candidat/ Données professionnelles et statistiques 

### **Format** : 
Liste déroulante (cf. référentiel des langues + référentiel niveaux ?). Avoir la possibilité de sélectionner plusieurs langues et niveaux associés.

Sera alimenté par le RF en back office via les paramètres (onglet à créer). Jean pourra ajouter la liste des langues + niveau au script sur demande.

**Comment by btrd** [comment]
@Grainedepaillette Le recruteur doit pouvoir mettre à jour les langues du candidat dans le backoffice ?

**Comment by btrd** [comment]
Disponible ici https://dashboard-next.scalingo.com/apps/osc-fr1/erecrutement-cvd-staging-pr898 (sans l'edit par l'admin)

**Comment by btrd** [comment]
> @Grainedepaillette Le recruteur doit pouvoir mettre à jour les langues du candidat dans le backoffice ?

Pas pour le moment (en attente de l'atelier fonctionnel)

**Comment by Grainedepaillette** [comment]
@btrd Après test, voici les résultats : 

### **1er cas de figure / Le candidat complète le formulaire sans être connecté à son espace candidat :** 
- Lorsqu'un candidat sélectionne UNE SEULE langue dans le formulaire 
A) EN FRONT : lorsqu'un candidat valide sa candidature (clic bouton) le champ est invalide : affichage du message "doit exister" au niveau du champ "langues". 
![Capture d’écran 2021-04-26 à 09 57 05](https://user-images.githubusercontent.com/51794334/116048767-d0d5f780-a675-11eb-9cf5-a71e944f9487.png)
B) EN BACK : la langue sélectionnée en front apparaît bien au niveau de la carte candidat 

- Lorsqu'un candidat sélectionne PLUSIEURS langues dans le formulaire : 
A) EN FRONT : La candidature est bien validée et transmise. 
B) EN BACK : seule 1 langue apparaît au niveau de la carte candidat/onglet profil 
![Capture d’écran 2021-04-26 à 10 06 00](https://user-images.githubusercontent.com/51794334/116049832-0d562300-a677-11eb-9e7f-8f5582c067a4.png)

### **2ème cas de figure / Le candidat complète le formulaire en étant connecté à son espace candidat :** 
- EN FRONT : 
- Lorsqu'un candidat clic sur le bouton "ajouter" alors affichage de plusieurs champ "langues" supplémentaires ALORS qu'un seul champ devrait être ajouté à la fois.  

https://user-images.githubusercontent.com/51794334/116051173-97eb5200-a678-11eb-9f25-3c2a953571e0.mov

- Lorsqu'un candidat sélectionne 1 première langue supplémentaire puis une 2ème (clique sur bouton "ajouter"") ALORS affichage de plusieurs champ "langues" supplémentaires ALORS qu'un seul champ devrait être ajouté à la fois + reprise de la 1ère langue saisie dans ces nouveaux champs. En BACK les langues apparaissent bien. 

https://user-images.githubusercontent.com/51794334/116051820-48f1ec80-a679-11eb-83bc-3d1fe3d756e6.mov

**En complément, mettre un A majuscule à "Ajouter"**

**Comment by btrd** [comment]
@Grainedepaillette Merci pour tes retours ! Ils ont été corrigés

**Comment by Grainedepaillette** [comment]
@btrd Yes, j'ai testé tous les cas de figures et ça fonctionne !
