### ISSUE TITLE
Front/Espace candidat : ajouter champ "photo" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#489]
- **Donnée liée à l'UTILISATEUR**
- **Donnée existe déjà en front/ formulaire de candidature + back/carte candidat**
- **Ajout au niveau des pages : Espace candidat/Onglet "mon compte"/ Encart "mes informations" #483**

### **Comportement actuel :** 
Le candidat a la possibilité de télé-verser une photo depuis le formulaire de candidature ( elle est non obligatoire) et alimente le Back/Carte candidat

### **Comportement souhaité :** 
Donner la possibilité au candidat de télé-verser une photo depuis son espace candidat. Ajouter le champ "photo" (cf. écran formulaire de candidature) afin que le candidat puisse ajouter/modifier/supprimer cette donnée. 

### **Règles :**
- Général : la dernière donnée renseignée par le candidat (dernière action sur une donnée) est celle qui doit apparaître en front et en back.
- Si la donnée est renseignée dans le formulaire de candidature ALORS elle alimente l'espace candidat + la carte candidat
- Si la donnée est renseignée à partir de l'espace candidat ALORS elle alimente la carte candidat.
- La donnée ne peut être modifiée par le recruteur en back.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr891.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Testé et opérationnel
