### ISSUE TITLE
Back/Carte candidat : ajouter champ " souhait(s) géographique(s) (département)"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#499]
Seule saisie d'un département est valide.
Format : champ libre + autocomplétion (algolia)

**Comment by btrd** [comment]
Je me permet de supprimer ce ticket pour ne conserver que https://github.com/betagouv/civilsdeladefense/issues/476

**Comment by Grainedepaillette** [comment]
@btrd Bien pris en compte
