### ISSUE TITLE
Back/Carte candidat : ajouter champ "disponibilité"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#500]
Format : liste déroulante :
"En poste"
"Disponible immédiatement"
"Disponible sous 1 mois"
"Disponible sous 2 mois"
"Disponible sous 3 mois ou plus"

**Comment by yannski** [comment]
@Grainedepaillette il y a déjà une liste de disponibilités sous forme de nombre de mois. Faut-il la remplacer par la demande de ticket ?

**Comment by Grainedepaillette** [comment]
@yannski oui pour ne conserver qu'un un seul champ et avoir les délais par "tranche" et pas en détail

**Comment by Grainedepaillette** [comment]
@yannski oui pour ne conserver qu'un un seul champ et avoir les délais par "tranche" et pas en détail

**Comment by Grainedepaillette** [comment]
@yannski oui pour ne conserver qu'un un seul champ et avoir les délais par "tranche" et pas en détail

**Comment by Grainedepaillette** [comment]
Opérationnel en pré-production : passage en production validé
