### ISSUE TITLE
Back/Statistiques candidatures : ajout donnée "délai moyen de recrutement "

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#503]
### **Comportement actuel :**  
Aujourd'hui il n'existe pas de donnée statistique permettant d'apprécier le délai moyen de recrutement global (de la 1ère à la dernière étape du processus) et les délais entre chaque étape du processus de recrutement. 

### **Comportement souhaité :** 
A partir de l'onglet "Statistiques",  ajouter et afficher la donnée "délai moyen de recrutement" global et les délais moyens entre chaque étape du processus de recrutement. 

### **Format** : 
**Délai moyen de recrutement sur l'ensemble du processus :** 

1. Afficher le délai de la date de publication de l'offre et l'étape "affecté"

**Délai pour chaque étape du processus :** 

2. Afficher le délai entre l'étape "nouveau" et l'étape "refusé" 
3. Afficher le délai entre l'étape "nouveau" et l'étape "entretien tèl." 
4. Afficher le délai entre l'étape "entretien tèl." et l'étape "refusé après entretien tèl." 
5. Afficher le délai entre l'étape "entretien tèl." et l'étape " à rencontrer"  
6. Afficher le délai entre l'étape "à rencontrer" et l'étape "rencontré mais refusé"  
7. Afficher le délai entre l'étape "à rencontrer" et l'étape "retenu"  
8. Afficher le délai entre l'étape "retenu" et l'étape "rédaction contrat"  
9. Afficher le délai entre l'étape "rédaction contrat" et l'étape " en attente retour contrat" 
10. Afficher le délai entre l'étape "en attente retour contrat" et l'étape "contrat reçu" 
11. Afficher le délai entre l'étape "contrat reçu" et "affecté"

Design associé : 
![EXPORTS_CIVIL2-2 copie](https://user-images.githubusercontent.com/51794334/74344114-60162880-4dac-11ea-96d4-ec10627ab444.jpg)

**Comment by Grainedepaillette** [comment]
@btrd Apport de précisions au commentaire précédent

**Comment by btrd** [comment]
C'est une statistique sur l'offre et pas sur la candidature non ?

**Comment by Grainedepaillette** [comment]
@btrd Il était prévu que la donnée apparaisse dans le stats candidatures et offres car elle concerne le "processus de recrutement" car cette données peut être appréciée tant par rapport aux profils des candidats qu'aux types de postes à pourvoir

**Comment by Grainedepaillette** [comment]
@btrd Pour faire suite au point hebdo : 

> **Délai moyen de recrutement sur l'ensemble du processus :**
> 1. Afficher le délai de la date de publication de l'offre et l'étape "affecté"

Doit apparaître au niveau des statistiques offres 

> **Délai pour chaque étape du processus :**
> 
> 1. Afficher le délai entre l'étape "nouveau" et l'étape "refusé"
> 2. Afficher le délai entre l'étape "nouveau" et l'étape "entretien tèl."
> 3. Afficher le délai entre l'étape "entretien tèl." et l'étape "refusé après entretien tèl."
> 4. Afficher le délai entre l'étape "entretien tèl." et l'étape " à rencontrer"
> 5. Afficher le délai entre l'étape "à rencontrer" et l'étape "rencontré mais refusé"
> 6. Afficher le délai entre l'étape "à rencontrer" et l'étape "retenu"
> 7. Afficher le délai entre l'étape "retenu" et l'étape "rédaction contrat"
> 8. Afficher le délai entre l'étape "rédaction contrat" et l'étape " en attente retour contrat"
> 9. Afficher le délai entre l'étape "en attente retour contrat" et l'étape "contrat reçu"
> 10. Afficher le délai entre l'étape "contrat reçu" et "affecté"

Doit apparaître au niveau des statistiques candidatures.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr890.osc-fr1.scalingo.io

> Délai moyen de recrutement sur l'ensemble du processus
> Afficher le délai de la date de publication de l'offre et l'étape "affecté"

Malheureusement on enregistre pas cette donnée, j'ai modifié pour que ce soit le cas maintenant. Les stats ne seront juste que pour les nouvelles offres.

Tu risques de pas pouvoir vérifier les données étant données qu'en staging les données ne sont pas "propre/correct".

**Comment by Grainedepaillette** [comment]
@btrd J'ai testé, voici mes retours : 
C'est opérationnel, j'ai créé une offre pour checker les automatismes entre les actions réalisées, le calcul du délai et l'affichage.

**Comment by btrd** [comment]
Pris en compte !

**Comment by Grainedepaillette** [comment]
@btrd Merci, après vérification :

> **Pour les statistiques candidatures : remplacer "Délai moyen de recrutement" par "Délai moyen par étape de recrutement"** 
> 
> ![Capture d’écran 2021-04-20 à 19 57 07](https://user-images.githubusercontent.com/51794334/115443681-d665b480-a213-11eb-97e7-9ea12c6bb827.png)

Cette demande concernait uniquement les **statistiques candidatures**, pour l**es statistiques offres, l'intitulé doit bien être "Délai moyen de recrutement "**

Merci

**Comment by btrd** [comment]
Oups, corrigé
