### ISSUE TITLE
Back/Statistiques candidatures : ajout donnée "corrélation entre localisation offre et souhait mobilité candidat" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#504]
% des candidats positionnés sur une offre dont le souhait de mobilité correspond à la localisation de l'offre 

Design associé : 
![EXPORTS_CIVIL2-2 copie](https://user-images.githubusercontent.com/51794334/74344560-1c6fee80-4dad-11ea-9d87-d09f4c19fae2.jpg)

**Comment by btrd** [comment]
Est-ce que je prends en comptes les candidats n'ayant pas renseignés de souhaits de mobilités ?

**Comment by Grainedepaillette** [comment]
@btrd Non ce ne sera pas utile ! On précisera aux utilisateurs que cette donnée se base sur les candidats ayant communiqué l'info dans le formulaire de candidature

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr955.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel :)
