### ISSUE TITLE
Back/Statistiques offres : ajout menu déroulant "localisation géographique "

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#511]
Seule saisie d'un département est valide
Format : champ libre + autocomplétion (algolia)

**Comment by Grainedepaillette** [comment]
# 521

**Comment by Grainedepaillette** [comment]
#521

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd 2 points : 

- L'intitulé du menu déroulant en production est "départements" au lieu de localisation géographique 
- Le contenu du menu déroulant ne sont pas les mêmes sur les fonctionnalités vivier et statistiques offres, pourquoi ? Pas le même logiciel derrière ?

**Comment by btrd** [comment]
> Le contenu du menu déroulant ne sont pas les mêmes sur les fonctionnalités vivier et statistiques offres, pourquoi ? Pas le même logiciel derrière ?

Pour le vivier ça prends en compte le choix des utilisateurs parmi une liste de département.
Pour les offres c'est la localisation des offres qui font partis d'un département.

C'est effectivement deux systèmes différents (mais qui peuvent fonctionner ensemble grâce au numéro de département).

**Comment by Grainedepaillette** [comment]
@btrd c'est toujours le même intitulé en pré-prod et prod et l'environnement n'est plus accessible. 

Du coup, est -ce qu'on pourrait retrouver la logique de numéro pour tous les menus déroulants quel que soit l'onglet ? Ou est-ce compliqué ? Merci.

**Comment by btrd** [comment]
Je trouvais ça pratique de grouper par région mais je peux retirer oui (et ajouter les numéros de département)

**Comment by btrd** [comment]
![Capture d’écran 2021-06-23 à 12 30 43](https://user-images.githubusercontent.com/1385737/123081972-d5711f00-d41e-11eb-90ef-34aa3816bbc1.png)

Pour info j'ai repris le fonctionnement de cette page

**Comment by btrd** [comment]
@Grainedepaillette C'est déployé

**Comment by Grainedepaillette** [comment]
@btrd Réflexion faite, je te rejoins sur la logique de 1er niveau région + 2ème niveau département comme ce qu'on a sur le front, l'idée est d'avoir les mêmes menus déroulants pour les onglets stats et vivier ; du coup serait-il possible d'avoir cette présentation pour le vivier également ?

(cf. écran) ![Capture d’écran 2021-06-30 à 14.08.17.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/ddf78ed7-50f9-44da-8afa-8282724b985e)

En conservation l'intitulé "localisation géographique" (que tu as déjà dev)

**Comment by Grainedepaillette** [comment]
La page stats offre du staging est down 
![Capture d’écran 2021-07-08 à 21.45.54.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/35e86c2f-3975-48e7-a051-8989350a050a)

Je me permets de réouvrir le ticket

**Comment by Grainedepaillette** [comment]
@btrd L'application seule du filtre localisation géographique ne fonctionne pas en production. Le filtre n'est pas pris en compte. (cf. vidéo) 

https://images.zenhubusercontent.com/146276066/0965c578-6948-4e8f-9e13-8098e326da9d/application_filtres_.mov

**Comment by Grainedepaillette** [comment]
Je me permets de réouvrir le ticket

**Comment by btrd** [comment]
C'est corrigé
