### ISSUE TITLE
Back/Statistiques offres : ajout donnée "nombre offres publiées" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#514]

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
- Ecrire comme intitulé "nombre d'offres publiées" (sinon c'est opérationnel)

**Comment by Grainedepaillette** [comment]
@btrd C'est validé
