### ISSUE TITLE
Back/Statistiques offres : ajout donnée "nombre offres pourvues" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#516]

**Comment by Grainedepaillette** [comment]
Les candidatures à comptabiliser pour considérer que les offres sont pourvues sont les candidatures taggées avec l'état : 
- Retenu 
- Rédaction contrat
- En attente retour contrat
- Contrat reçu
- Affecté

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
- Écrire comme intitulé "Nombre d'offres pourvues" (sinon c'est opérationnel)

**Comment by Grainedepaillette** [comment]
@btrd C'est validé
