### ISSUE TITLE
Back/Statistiques offres : ajout donnée "nombre offres à pourvoir"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#517]

**Comment by Grainedepaillette** [comment]
Cette donnée correspond à toutes les offres pour lesquelles une candidature n'a pas au minimum atteint l'étape "retenu". 
Ainsi, les offres pour lesquelles une candidature est à l'étape : 

- retenu 
- ou Rédaction contrat
- ou En attente retour contrat
- ou Contrat reçu
- ou Affecté(e)

ne doivent pas être prises en compte pour dans le calcul.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
- Écrire comme intitulé "Nombre d'offres à pourvoir" (sinon c'est opérationnel)

**Comment by Grainedepaillette** [comment]
@btrd C'est validé
