### ISSUE TITLE
Back/Statistiques offres : ajout donnée "nombre de candidatures"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#518]

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
- Ecrire comme intitulé "Nombre total de candidatures" (sinon c'est opérationnel)

**Comment by Grainedepaillette** [comment]
@btrd C'est validé.
