### ISSUE TITLE
Back/Statistiques offres : ajout donnée "nombre de candidats disponibles"

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#519]
Correspond aux candidats qui ne sont pas "En poste" (cf. ticket #477 #492 #500)

**Comment by Grainedepaillette** [comment]
Cette donnée correspond à tous les candidats ayant indiqué au moins 1 fois (sur une candidature) étant "disponible immédiatement". 
Si un candidat à indiquer être disponible immédiatement sur une candidature à une offre (formulaire de candidature) mais "disponible sous un mois" ou "en poste" sur une autre offre ALORS il doit tout de même être comptabiliser dans les candidats disponibles.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr965.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
- Peux-tu ajouter des propositions sur la liste déroulante "Disponibilités" que je puisse vérifier le ticket ? 
- Ecrire comme intitulé "Nombre de candidats disponibles"

**Comment by Grainedepaillette** [comment]
@mch2608 Testé, c'est okay, les candidats disponibles apparaissent bien dans les statistiques (cf. écran ci - dessous) ![Capture d’écran 2021-06-06 à 20.58.47.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/2f1690be-1efe-46e5-b06c-3c01586ffe83)

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel, seul point à modifier : ajouter la mention "candidats" pour avoir un intitulé correspondant à "candidats disponibles" (cf. écran). ![ajout candidats .png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/ecb91a34-c557-4a32-ad9d-53e82128873d)

**Comment by btrd** [comment]
C'est fait
