### ISSUE TITLE
Back/Vivier : ajout filtre "mobilité géographique" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#521]
Filtrer par département. 
Format : champ libre + autocomplétion (algolia)

**Comment by btrd** [comment]
@Grainedepaillette C'est un recruteur qui renseigne un département pour un utilisateur ? Un seul département ou plusieurs ? L'utilisateur a accès à cette information ? Il peut la modifier ?

**Comment by Grainedepaillette** [comment]
@btrd Il s'agit d'ajouter un filtre au niveau de la barre de recherche de sorte à ce que les profils candidats soient filtrés par zone géographique (leurs souhaits de mobilité). Le recruteur doit pouvoir sélectionner plusieurs départements. 

L'idée générale est que le recruteur puisse identifier les profils sur un "bassin d'emploi donné". 

Origine de la donnée : 
- elle peut être communiquée par le candidat lors de la candidature (cf. développement du formulaire #476)
- elle peut être communiquée par le candidat à partir de son espace candidat (cf. développement de l'espace candidat #491 )
- elle peut être communiquée par le recruteur à partir de la carte candidat/ onglet "profil" (cf. ticket #499 )

**Comment by btrd** [comment]
Du coup ce ticket dépend des trois autres tickets qui eux ne sont pas dans le Sprint 1. Je me permet de retirer ce ticket du Sprint 1 du coup.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr955.osc-fr1.scalingo.io

**Comment by btrd** [comment]
@mch2608 Disponible ici https://erecrutement-cvd-staging-pr955.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Principe du filtre opérationnel mais non apparition de la donné dans le profil de la carte candidat.

**Comment by btrd** [comment]
C'est corrigé
