### ISSUE TITLE
Back/Vivier : ajout champ "expérience antérieure au Ministère des Armées" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#524]
Format : bouton "oui" / "non"
Design associé :
![EXPORTS_CIVIL2-3 copie](https://user-images.githubusercontent.com/51794334/74354469-b2ab1100-4dbb-11ea-883b-5330c0591159.jpg)

**Comment by Grainedepaillette** [comment]
Opérationnel en pré-production : passage en production validé

**Comment by mch2608** [comment]
Je réouvre le ticket : actuellement ce filtre se nomme "expérience", ce qui fait doublon avec le filtre "expérience" qui correspond au niveau d'expérience du candidat. 

Comportement souhaité : changer l'intitulé du filtre par "expérience antérieure au Ministère des Armées"

**Comment by btrd** [comment]
Est-ce que "expérience interne" ce serait ok ? Pour que ça fonctionne aussi côté ANSSI, DGA, etc

**Comment by mch2608** [comment]
On peut partir sur "Expérience en interne". 
En front, au niveau du formulaire de candidature, il faudrait tout de même conserver l'intitulé "expérience antérieure au Ministère des Armées" si cela te convient.

**Comment by btrd** [comment]
Pour l'ANSSI on doit avoir quoi comme valeur ?

Ce qu'il y aurais de mieux ce serait `Expérience antérieure au [valeur]` avec comme la valeur du champs entité bloc marque (configurable par le BANT).

**Comment by mch2608** [comment]
On peut partir sur ça oui !

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1086.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
J'ai check l'environnement mais pas trouvé à quel niveau c'était paramétrable

**Comment by btrd** [comment]
C'est ici, c'est un champ qui existe déjà et dont je veux ré-utiliser la valeur

https://erecrutement-cvd-staging-pr1086.osc-fr1.scalingo.io/admin/parametres/organization/edit

**Comment by mch2608** [comment]
- OK au niveau du paramètre "nom de l'opérateur"
- après test, la saisie du champ permet de modifier l'intitulé au niveau du filtre du vivier. 
- Pour le front, il n'y a pas de modification. Tu ne voulais pas que ce soit aussi paramétrable pour l'adapter à l'ANSSI ?

**Comment by btrd** [comment]
J'avais utilisé le paramètre `bloc marque` mais effectivement `nom opérateur` si prête mieux, c'est modifié

**Comment by mch2608** [comment]
C'est opérationnel
