### ISSUE TITLE
Back/Vivier : pouvoir exporter une sélection de candidats 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#526]
Après sélection de cartes candidats dans le vivier via le système de case à cocher, pouvoir exporter la sélection à partir du vivier via bouton "exporter" 
Format export : PDF, Excel ? 

Design associé : 
![abcd](https://user-images.githubusercontent.com/51794334/74421932-1a11a100-4e4e-11ea-9778-29fc1d6d49ec.png)

**Comment by btrd** [comment]
Pour le format je conseil le format CSV qui fonctionne avec tous les logiciels (Office, LibreOffice, Google Doc, ...).

Il me faudra la liste des colonnes à exporter.

**Comment by Grainedepaillette** [comment]
@btrd Ok pour le format.

**Comment by Grainedepaillette** [comment]
@btrd La liste des données à exporter : 

### **Données présentes sur la page identifiée (onglet "vivier") :** 
- Nombre de candidats sélectionnés 
- Données Carte candidat (Prénom, Nom, Poste actuel,nombre de candidatures, Statut de la candidature, Date de la candidature/de l'inscription)

### **Données présentes sur autres pages**
- Adresse mail 
- Numéro de téléphone 
- Ensemble des candidatures du candidat (employeur, date de candidature, statut sur candidatures)
- Données professionnelles et statistiques du profil candidat (genre, statut actuel, tranche d'âge, disponibilité, niveau d'études, expérience, expérience MINARM, souhaits de mobilité géographique, langues étrangères). 
- CV

### **Données à créer**
- Date de l’export 
- Utilisateur à l’origine de l’export

**Comment by Grainedepaillette** [comment]
@btrd Après vérification sur un échantillon élargie de candidats, quelques éléments au niveau de l'export sont à modifier : 
1. Ajouter les intitulés pour chaque catégorie de données (cf. fichier en P.J avec modifications de la présentation des données). 

2. Ajouter les titres en gras + majuscules (si possible) : CARTE CANDIDAT N°1 et CANDIDATURES CANDIDAT N°1 

3. Pour la donnée expérience antérieure au minarm : remplacer "expérience dans l'entreprise" par "OUI" et si absence d'expérience "NON" (cf. carte candidat) 

4. Dans les données relatives au candidat, un chiffre apparaît (après le courriel), ça correspond l'étape de la candidature ? (cf. P.J, le chiffre 0 en rouge). 

[https://app.zenhub.com/files/146276066/168de5a3-dd04-4f62-a263-29137efee023/download](https://app.zenhub.com/files/146276066/168de5a3-dd04-4f62-a263-29137efee023/download)

**Comment by btrd** [comment]
@mch2608 Disponible https://civilsdeladefense-staging.fabnum.fr/

**Comment by mch2608** [comment]
Quelques éléments à modifier : 
- Une faute d'orthographe sur le mot "Statut" au niveau de la rubrique de la carte candidat 
- Même question que le #682, à quoi correspond le chiffre de la ligne 4 ? 
- Positionner l'intitulé "Candidatures candidat n°x) au même niveau que la candidature associée (exemple pour le premier candidat : intitulé ligne 16 à positionner ligne 17) 
- Ajouter les titres en gras + majuscules (si possible) : CARTE CANDIDAT N°1 et CANDIDATURES CANDIDAT N°1

**Comment by btrd** [comment]
1. Corrigé
2. Au nombre de candidats exportés
3. Voir https://github.com/betagouv/civilsdeladefense/issues/682#issuecomment-856807242
4. J'ai mis les majuscules (compliqué pour le gras)

**Comment by mch2608** [comment]
- [ ] sur les corrections 
En revanche, les employeurs n'ont plus l'autorisation d'exporter des candidats. Seul le BANT dispose de la fonctionnalité.

**Comment by btrd** [comment]
C'est corrigé

**Comment by mch2608** [comment]
Le bouton "Exporter" en bas de page ne fonctionne pas. Il est donc impossible d'exporter une sélection de candidat.

**Comment by btrd** [comment]
Je me permet de fermer comme c'est le même soucis que ce ticket https://github.com/betagouv/civilsdeladefense/issues/1017

**Comment by Grainedepaillette** [comment]
@btrd C'est OK, je comprends que c'était les bouton de la page qui n'étaient pas "activés" ? Merci.

**Comment by btrd** [comment]
C'est bien cela
