### ISSUE TITLE
Back/Vivier/Listes candidats : pourvoir exporter une liste candidats

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#527]
Pouvoir exporter les listes de candidats via bouton "exporter" 
Format export : PDF, Excel ?

**Comment by btrd** [comment]
https://github.com/betagouv/civilsdeladefense/issues/526#issuecomment-815177405

**Comment by Grainedepaillette** [comment]
@btrd La liste des données à exporter :

### **Données présentes sur la page identifiée (onglet "vivier") :**
- Nombre de candidats sélectionnés
- Données Carte candidat (Prénom, Nom, Poste actuel,nombre de candidatures, Statut de la candidature, Date de la candidature/de l'inscription)

### **Données présentes sur autres pages**
- Adresse mail
- Numéro de téléphone
- Ensemble des candidatures du candidat (employeur, date de candidature, statut sur candidatures)
- Données professionnelles et statistiques du profil candidat (genre, statut actuel, tranche d'âge, disponibilité, niveau d'études, expérience, expérience MINARM, souhaits de mobilité géographique, langues étrangères).
- CV

### **Données à créer**
- Date de l’export
- Utilisateur à l’origine de l’export

**Comment by btrd** [comment]
> Données à créer
> - Date de l’export
> - Utilisateur à l’origine de l’export
Il faut enregistrer ces données ou juste les afficher dans l'export ?

> Ensemble des candidatures du candidat (employeur, date de candidature, statut sur candidatures)
> Données professionnelles et statistiques du profil candidat (genre, statut actuel, tranche d'âge, disponibilité, niveau d'études, expérience, expérience MINARM, souhaits de mobilité géographique, langues étrangères).

Ça veut dire que pour un candidat on aura plusieurs lignes, donc on exporte des candidatures et pas des candidats c'est bien ça ?

Pour le CV ce n'est pas possible de mettre un fichier dans un tableur, tu penses à un lien ?

**Comment by Grainedepaillette** [comment]
> Il faut enregistrer ces données ou juste les afficher dans l'export ?
Les afficher dans l'export 

> Ça veut dire que pour un candidat on aura plusieurs lignes, donc on exporte des candidatures et pas des candidats c'est bien ça ?
On veut le profil candidat + les candidatures associées mais l'export doit être structuré par profil candidat.

> Pour le CV ce n'est pas possible de mettre un fichier dans un tableur, tu penses à un lien ?
Est-ce qu'on peut les avoir joint au fichier (documents annexes) ?

**Comment by btrd** [comment]
> On veut le profil candidat + les candidatures associées mais l'export doit être structuré par profil candidat.

Je crois que je vais avoir besoin d'un fichier d'exemple pour comprendre ce que tu veux. Tu peux me faire un tableur avec la structure que tu aimerais ? (LibreOffice ou Excel)

> Est-ce qu'on peut les avoir joint au fichier (documents annexes) ?
C'est plus compliqué que la demande de base qui était d'avoir un fichier CSV en export.

**Comment by Grainedepaillette** [comment]
@btrd Voici un exemple. A ta dispo pour en discuter. 

[Exemple-export-liste-candidats.xlsx](https://github.com/betagouv/civilsdeladefense/files/6415824/Exemple-export-liste-candidats.xlsx)

> C'est plus compliqué que la demande de base qui était d'avoir un fichier CSV en export.

Bien pris. Aujourd'hui on peut exporter le CV mais profil par profil. L'idée était de pouvoir exporter les informations contenues sur les pages et les CV correspondants. Pourrais-tu quantifier le besoin ?

**Comment by btrd** [comment]
> Pourrais-tu quantifier le besoin ?

Je te laisse faire un ticket pour ça

**Comment by btrd** [comment]
@Grainedepaillette Disponible ici https://erecrutement-cvd-staging-pr933.osc-fr1.scalingo.io/
