### ISSUE TITLE
Back/ Pouvoir envoyer une offre d'emploi 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#528]
### **Comportement actuel :** 
Le recruteur n'a pas la possibilité lorsqu'il identifie un ou plusieurs profils intéressants qu'il aurait découvert à partir du vivier (car le candidat n'a pas postulé aux offres publiées par le recruteur par exemple) de communiquer directement une ou des offres d'emploi susceptibles d'intéresser ces candidats. 

### **Comportement souhaité :** 
Donner la possibilité au recruteur d'envoyer une ou des offres d'emploi à : 

**A) un candidat à partir de la carte candidat : pour ce faire il faut créer un bouton " envoyer une offre " au niveau de la carte candidat/partie "actions"** 
- **Parcours associé :**

1. Clic bouton "envoyer une offre" 
2. Sélectionner l'offre qu'il souhaite envoyer à partir d'un menu déroulant listant les offres relatives à son périmètre. La saisie + auto-complétion doit également permettre de sélectionner l'offre 
3. Confirmer/Valider, ce qui enverra un courriel automatique aux candidats contenant un message + le lien URL de l'offre (le message sera envoyé à destination de l'espace candidat + boîte mail personnelle du candidat et doit être visible dans l'historique des courriels échangés en back et front). 

![nouveaux_outils](https://user-images.githubusercontent.com/51794334/116064295-2a462280-a686-11eb-9c55-72b03ea3f03a.png)

**B) un ou plusieurs candidats simultanément à partir du vivier** 
**C) aux candidats présents dans une liste/ à partir d'une liste candidats** 

- Pour ce faire il faut créer un bouton " envoyer une offre " en bas de page "Vivier".
- **Parcours associé : identique à celui présenté supra.**

![abcd](https://user-images.githubusercontent.com/51794334/74422099-55ac6b00-4e4e-11ea-80f5-ec1b7021ff90.png)

**Comment by btrd** [comment]
> et doit être visible dans l'historique des courriels échangés en back et front

Ce n'est pas possible étant donné que la personne n'a pas postulé

**Comment by Grainedepaillette** [comment]
> Ce n'est pas possible étant donné que la personne n'a pas postulé

Pour bien comprendre : cela enverra bien un mail automatique depuis la plateforme vers les boîtes mail perso des candidats MAIS aucune trace dans le système (en front et back) ? 

@btrd Ca c'est du temps de dèv optimisé ahaha ! C'est OK, pour la rèf.

**Comment by Grainedepaillette** [comment]
@btrd Parfait ! Concernant le contenu du courriel qui sera envoyé, je suppose que tu as besoin d'un modèle ? Car s'il est automatique il n'y aura pas la possibilité de le paramétrer en back au niveau des modèles de courriels existants. 

Merci.

**Comment by btrd** [comment]
Effectivement

**Comment by btrd** [comment]
@Grainedepaillette Disponible https://erecrutement-cvd-staging-pr947.osc-fr1.scalingo.io (d'ici 5min)

**Comment by Grainedepaillette** [comment]
@btrd Testé c'est opérationnel au niveau du vivier + au niveau de la liste candidats.

**Comment by Grainedepaillette** [comment]
@btrd Est-ce qu'on peut avoir le même design (police, taille, couleur) pour l'intitulé "Envoyer un offre par email au candidat" que celui existant pour les boutons "suspendre ce compte" et "supprimer ce compte" ? Pour avoir les actions au même "niveau" visuellement

**Comment by btrd** [comment]
Doit être déployé avec https://github.com/betagouv/civilsdeladefense/issues/482
