### ISSUE TITLE
Back/Formulaire création offre : ajouter rôle "CMG" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#531]
- Ajouter le rôle "CMG" dans la liste des acteurs à notifier. 
- Pouvoir sélectionner à partir d'une liste déroulante un ou plusieurs courriels des CMG concernés par l'offre d'emploi. 
- Liste déroulante paramétrable par le BANT via onglet "Paramètres".

**Comment by yannski** [comment]
Rôle "CMG" == rôle "RH"

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)
