### ISSUE TITLE
Back/Trello : non accès à colonne "retenu" si durée publication offre < 30 jours

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#533]
Tant que la durée de publication de l'offre est inférieure à 30 jours (à partir de la date PEP) alors le passage à la colonne "retenu" du Trello n'est pas accessible (mais une offre doit pouvoir être déjà retenu afin de gérer les cas de changement de date PEP)

Le recruteur peut traiter les candidatures sur toute la phase amont du processus ("nouveau" à "entretien physique") mais pas sélectionner un candidat tant que durée pas atteinte.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1027.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel, cf. ticket 674 pour prolongation du temps d'affichage du message.

**Comment by Grainedepaillette** [comment]
@btrd 

Il faudrait modifier la règle préalablement établie. La date faisant foi sera la date de publication "PEP" renseignée dans le formulaire de rédaction de l'offre. 

Cf. ouverture ticket #1051

**Comment by btrd** [comment]
Je ne dois pas déployer ce ticket du coup ?

**Comment by Grainedepaillette** [comment]
@btrd je confirme

**Comment by btrd** [comment]
Le ticket https://github.com/betagouv/civilsdeladefense/issues/674 sera aussi déployé en même temps dans ce cas

**Comment by Grainedepaillette** [comment]
@btrd Je confirme, l'idée est de déployer les tickets avec le label "PEP" à la fin du prochain sprint

**Comment by Grainedepaillette** [comment]
@btrd Voici pour rappel les règles de gestion : 
Pour pouvoir créer l'offre (clic boutons "enregistrer" OU "publier") il faut que l'une ou l'autre des catégories (PEP OU BNE) soit complété (les 2 champs : référence + date)

Cas de figures associés :
1. Je complète les champs de la catégorie "PEP" ALORS je peux créer l'offre
2. Je complète les champs de la catégorie "BNE" ALORS je peux créer l'offre
3. Je complète les champs de la catégorie "PEP" et "BNE" ALORS je peux créer l'offre
4. Je ne complète aucun des champs de la catégorie "PEP" et "BNE" ALORS je peux ne peux PAS créer l'offre lorsque je clique sur le bouton, un message d'erreur indiquant de compléter les champs doit s'afficher.

Ces informations ne doivent pas apparaître en front office, elles sont destinées aux recruteur + BANT pour un suivi interne. 


En complément et pour faire suit à notre échange : 
OK pour l'ajout des informations pour les champs des offres déjà publiées : 
Référence : "inconnue"
Date de publication : 01/01/2020

Règle associé : un candidat peut ETRE retenu (même si délai de 30 jours à partir de al date publication PEP non respectée) MAIS ne peut PAS DEVENIR retenu (lorsque délai de 30 jours à partir de al date publication PEP non respecté)

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1071.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
La fonctionnalité est opérationnelle à partir du trello et du menu déroulant de la carte candidat. Cependant, même problème que celui décrit par @Grainedepaillette sur le #674 : le message qui informe du changement de statut de la candidature disparait trop rapidement pour être visible par l'utilisateur.

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd Testé sur Mozilla c'est opérationnel, par contre pourrais-tu corriger le contenu du message et retirer le S à délai ? (cf. écran). Merci. 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/c9af6e2c-189d-4807-b925-4b0b928ad867)

**Comment by Grainedepaillette** [comment]
@btrd C'est passé en staging ? Je voulais checker le message. Merci !

**Comment by btrd** [comment]
C'est en staging oui

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel merci !!!

**Comment by mch2608** [comment]
On peut aussi préciser que le délai s'applique pour les publications PEP ? : "Un délai de 30 jours après la publication de l'offre sur la PEP doit être respecté avant d'accepter une candidature" ?

**Comment by btrd** [comment]
Modifié
