### ISSUE TITLE
Back/Carte candidat : supprimer les boutons "Demander" et "Télé-verser" pour les fichiers A et B

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#535]
Lorsque des fichiers sont taggés " fichier gérés hors outil" dans les paramètres, ne pas faire apparaître de boutons "demander" ou "téléverser" dans la carte candidat

**Comment by yannski** [comment]
Fixed in https://github.com/betagouv/civilsdeladefense/commit/acf836788b25760d229a416dd9c0b386ba02a962
