### ISSUE TITLE
Back/Carte candidat : Ajouter une case à cocher pour les fichiers A et B

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#536]
Lorsque des fichiers sont taggés " fichier gérés hors outil" dans les paramètres, faire apparaître une case à cocher

**Comment by yannski** [comment]
Fixed in https://github.com/betagouv/civilsdeladefense/commit/acf836788b25760d229a416dd9c0b386ba02a962
