### ISSUE TITLE
Non réception du recap journalier par le BANT

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#539]
Dernier reçu le 12/02

**Comment by yannski** [comment]
Le recap est bien envoyé tous les jours. Y a-t-il encore un souci à ce sujet ?

**Comment by Grainedepaillette** [comment]
Je confirme la bonne réception du récap depuis le 27.02 à 15h.

**Comment by Grainedepaillette** [comment]
@yannski Non réception du récap journalier depuis le lundi 04.04. Dernier reçu le vendredi 03.04

**Comment by Grainedepaillette** [comment]
@yannski Non réception du récap journalier depuis le lundi 14 avril. Dernier reçu le samedi 11 avril
