### ISSUE TITLE
Back / Offres : Si employeur change établissement alors absence de visibilité des offres précédemment publiées 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#540]
Un utilisateur doté d'un rôle employeur SID a changé d'établissement : passage de SID à DAJ. L'employeur a conservé la visibilité sur les offres publiées en tant qu'employeur SID bien que le BANT ait modifié son profil.

**Comment by Grainedepaillette** [comment]
Cf. Ouverture des tickets 548 à 552
