### ISSUE TITLE
Back / Offres : Non apparition de la date de publication 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#541]
Offres actifs concernées : 
SID53  SID56 SID57 SID58 SID241 SID242 SID246 SID251 SID256 
DIRISI27 
EMA/Employeur29 

Offres archivées concernées : 
DIRISI1 DIRISI2 DIRISI3 DIRISI8 DIRISI9 DIRISI11 DIRISI12 DIRISI13 DIRISI14 DIRISI15 DIRISI16 DIRISI17 DIRISI18 DIRISI21 DIRISI22 DIRISI23 DIRISI24 DIRISI25 DIRISI26 DIRISI28 DIRISI30 DIRISI32 DIRISI33 DIRISI38 DIRISI42 DIRISI44 DIRISI45 DIRISI47 DIRISI55 DIRISI58 DIRISI61 DIRISI67 DIRISI69 DIRISI70 DIRISI73 DIRISI75 DIRISI76 DIRISI84 DIRISI85 DIRISI86 DIRISI87 DIRISI88 DIRISI89 DIRISI90 DIRISI102 DIRISI108 DIRISI109 DIRISI121 DIRISI124 DIRISI133 DIRISI141 DIRISI144 DIRISI158 DIRISI166 DIRISI169 DIRISI173 DIRISI175 DIRISI176 DIRISI191 DIRISI195 DIRISI197 DIRISI199 DIRISI211 DIRISI217 

SID1 SID4 SID9 SID21 SID22 SID23 SID24 SID25 SID26 SID28 SID30 SID32 SID33 SID42 SID43 SID44 SID45 SID47 SID55 SID58 SID61 SID67 SID70 SID73 SID75 SID76 SID84 SID85 SID87 SID88 SID89 SID79 SID72 SID91 SID93 SID94 SID129 SID138 SID139 SID140 SID143 SID150 SID170 SID182 SID194 SID245 

EMA-GE 1

**Comment by Grainedepaillette** [comment]
@btrd La liste évoquée supra par Mchangama a évolué. L'absence de date de publication est afficher de manière aléatoire. Ce PB est constaté en back office et en front office où des offres d'emploi n'ont pas de dates.

**Comment by btrd** [comment]
C'est un bug qui concerne les offres qui sont directement créés en Publié, je corrige ça.

**Comment by Grainedepaillette** [comment]
@btrd @mch2608 Après vérification en production (back + front), toutes les dates semblent apparaître sous les offres publiées.
