### ISSUE TITLE
Back/Paramètres/Afficher la liste des annonces visibles par un recruteur

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#548]

**Comment by btrd** [comment]
@Grainedepaillette Tu peux spécifier la fonctionnalité ?

**Comment by Grainedepaillette** [comment]
@btrd En back office dans l'onglet "paramètres" (onglet auquel seul le RF a accès pour le paramétrage de la solution) puis l'onglet "Comptes admin", parmi les informations relatives aux comptes utilisateurs (cf. écran) doit apparaître la listes des offres auxquelles est associé l'utilisateur. Format : ajouter une colonne 

![Capture d’écran 2021-03-16 à 15 42 42](https://user-images.githubusercontent.com/51794334/111328235-5a091000-866e-11eb-9b8d-e81a04b26afc.png)

**Comment by Grainedepaillette** [comment]
@btrd Apport de précisions au commentaire précédent.

**Comment by btrd** [comment]
Tu dis au début
> les offres auxquelles chaque Employeur est associé
puis
> la liste des offres qu'il a créé/ publié

Pour moi on peut être associé a une offre sans l'avoir créé. On a un seul créateur mais plusieurs Employeur possible

![Capture d’écran 2021-04-07 à 18 34 33](https://user-images.githubusercontent.com/1385737/113902222-f2a73180-97cf-11eb-8e1f-4c780557af8c.png)

**Comment by Grainedepaillette** [comment]
@btrd Pour répondre à ta question : il est en effet préférable que le RF puisse visualiser les offres auxquelles sont rattachées les utilisateurs dotés du rôle "Employeur" qu'ils aient créé ou pas l'offre. 

En revanche les options "changement de propriétaire" et "ne plus notifier cet utilisateur" ne doivent apparaître que pour les employeur "créateurs" de l'offre, d'où la notion de "propriété". L'objectif étant de tracer qui est "responsable de l'offre" et à quel moment. 

Qu'en penses - tu ?

**Comment by btrd** [comment]
Ça me va. Je modifie ton commentaire pour que ce soit plus clair

**Comment by btrd** [comment]
À tester ici
https://erecrutement-cvd-staging-pr889.osc-fr1.scalingo.io
