### ISSUE TITLE
Back/Paramètres/Liste des annonces liées à un recruteur : changer le propriétaire des annonces

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#549]
Voir #548

**Comment by Grainedepaillette** [comment]
### **Contexte :**
Cette fonctionnalité concerne le RGPD et l'accès aux données candidats. Cette fonctionnalité vise à limiter l'accès à l'outil et plus précisément aux données candidats par des utilisateurs "Employeur" qui n'aurait plus le droit d'y accéder en raison d'un changement de poste/de service/de ministère ou d'un départ.

Cette fonctionnalité doit donc permettre :
- au RF de visualiser en instantanée les offres auxquelles chaque Employeur est associé dans l'outil et agir sur la propriété d'une offre notamment en transférant les droits associés à la propriété d'une offre (accès aux données candidats, traitement des candidatures, etc) à un nouvel Employeur. **Tickets associés : #549 #550**
- à l'employeur lui -même d'agir et de transférer les droits associés à la propriété d'une offre **Tickets associés : #551 #552**

### **Rôle concerné :**
Employeur (recruteur)

### **Comportement souhaité :**
En back office dans l'onglet "Paramètres" < Onglet "Comptes admin" : à côté de la colonne répertoriant la liste des offres, ajouter un bouton "changer le propriétaire". Ce bouton doit permettre au RF de saisir une "nouvelle" adresse INTRADEF qui sera associée aux offres listées. Ce nouveau compte doit automatiquement être taggué sur chaque offre en tant qu'Employeur. 

### **Format :**
- Ajouter un bouton "changer le propriétaire" 
- Lorsque le RF clique sur le bouton, accès à une page permettant de saisir et d'enregistrer l'adresse INTRADEF/ le compte en remplacement du précédent. (cf.écran ci -dessous) 
![Capture d’écran 2021-04-06 à 10 51 22](https://user-images.githubusercontent.com/51794334/113684974-0ebeac00-96c6-11eb-92ba-33725597b957.png)

- Une fois saisi et enregistré, ce compte doit être ajouté automatiquement en tant qu'Employeur sur chaque offre.

**Comment by Grainedepaillette** [comment]
@btrd Concernant la saisie de l'adresse INTRADEF devant en remplacement de l'ancienne, il y a 2 cas de figure : 
1. Le compte remplaçant existe déjà ALORS le simple fait de l'ajouter comme remplaçant permet de le notifier sur chaque offre 
2. Le compte remplaçant n'existe pas : est-ce que le fait de l'ajouter comme remplaçant pourra permettre de créer son compte + le notifier sur les offres ? Ou est-ce que selon toi il est préférable que le compte soit créé en amont de manière ad hoc (cf. procédure habituelle de création de compte "Employeur" par le RF).

**Comment by btrd** [comment]
Ce que tu veux c'est supprimer le compte existant ?
Modifier l'adresse mail du compte ? (conserver le compte comme auteur des messages, conserver le mot de passe, )

**Comment by btrd** [comment]
> Ou est-ce que selon toi il est préférable que le compte soit créé en amont de manière ad hoc (cf. procédure habituelle de création de compte "Employeur" par le RF).

Si c'est possible de créer le compte en amont ça m'arrange pour ne devoir gérer qu'un cas.

**Comment by Grainedepaillette** [comment]
@btrd L'option "changement de propriétaire" ne doit apparaître que pour les utilisateurs employeurs "créateurs" de l'offre.

**Comment by Grainedepaillette** [comment]
> > Ou est-ce que selon toi il est préférable que le compte soit créé en amont de manière ad hoc (cf. procédure habituelle de création de compte "Employeur" par le RF).
> 
> Si c'est possible de créer le compte en amont ça m'arrange pour ne devoir gérer qu'un cas.

Bien pris, on le précisera dans le MODOP de l'outil

**Comment by btrd** [comment]
MODOP ?

**Comment by btrd** [comment]
> Une fois saisi et enregistré, ce compte doit être ajouté automatiquement en tant qu'Employeur sur chaque offre.

Que fais t'on de l'ancien compte ? On lui retire le role employeur de toutes les offres ?

**Comment by btrd** [comment]
À tester ici
https://erecrutement-cvd-staging-pr889.osc-fr1.scalingo.io

Au final j'ai aussi géré le cas où l'administrateur n'existe pas, on le gère déjà dans le cas où on ajoute un employeur sur une offre donc c'est le même fonctionnement.

**Comment by Grainedepaillette** [comment]
@btrd 

Après test, toutes les fonctionnalités apparaissent bien sur la page et c'est très instinctif. 

Problématique rencontrée : dans la partie "transférer les offres", lorsque je saisie le courriel et clique sur le bouton "transférer" un message d'erreur apparaît (cf. vidéo). 
https://images.zenhubusercontent.com/146276066/8c010433-5c76-47a0-9c53-2fd5213e49c9/non_transfert_offre.mov

**Comment by btrd** [comment]
C'est corrigé.

**Comment by Grainedepaillette** [comment]
@btrd Testé et je confirme c'est opérationnel

**Comment by Grainedepaillette** [comment]
> Au final j'ai aussi géré le cas où l'administrateur n'existe pas, on le gère déjà dans le cas où on ajoute un employeur sur une offre donc c'est le même fonctionnement.

Je comprends donc que : si je transfère les offres à un recruteur dont le compte ne serait pas encore créé sur CVD, il recevra une notification pour créer son compte ? Le transfert de propriété permettra simultanément la création du compte ? 
Merci.

**Comment by btrd** [comment]
C'est bien ça

**Comment by Grainedepaillette** [comment]
Top, on gagnera une étape !
