### ISSUE TITLE
Protéger le bouton "Changer d'état" pour les candidatures suivant les droits de l'utilisateur courant

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#55]
Notamment les BRH n'ont pas le droit de changer d'état

**Comment by yannski** [comment]
Voir la gem cancancan utilisée pour gérer les autorisations https://github.com/CanCanCommunity/cancancan/wiki/checking-abilities

**Comment by N1colas** [comment]
j'ai ce problème quand je me connecte avec un compte BRH 
![image](https://user-images.githubusercontent.com/6283122/46197351-de823f80-c309-11e8-8c21-73932a996754.png)

je te propose de mettre cela :
`ary.unshift(current_administrator.employer.code) if current_administrator.employer?`
ainsi le BANT et le BRH ne seront pas impacté par le code employer.

**Comment by N1colas** [comment]
ensuite j'ai :
![image](https://user-images.githubusercontent.com/6283122/46197644-ae876c00-c30a-11e8-9a64-cb9b6bace803.png)

L'utilisateur BRH n'a pas d'offre, cela peut être compréhensible étant donné que c'est le BANT qui a créer les offres (dans le seed). Cependant, il n'a pas le bouton "créer un offre", peut il créer une offre ?
Est ce que tu as la liste des droits du BANT, BRH et employer ?

**Comment by yannski** [comment]
Voir https://github.com/betagouv/civilsdeladefense/blob/2f017108db14a833f7bd87a377ac1cd40fe26fa8/app/models/ability.rb

**Comment by yannski** [comment]
le BRH a seulement le droit de consulter.

**Comment by N1colas** [comment]
ok.
