### ISSUE TITLE
Back / Paramètres / Liste des annonces liées à un recruteur : fonctionnalité "ne plus notifier cette employeur"

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#550]

**Comment by Grainedepaillette** [comment]
### **Contexte :**
Cette fonctionnalité concerne le RGPD et l'accès aux données candidats. Cette fonctionnalité vise à limiter l'accès à l'outil et plus précisément aux données candidats par des utilisateurs "Employeur" qui n'aurait plus le droit d'y accéder en raison d'un changement de poste/de service/de ministère ou d'un départ.

Cette fonctionnalité doit donc permettre :
- au RF de visualiser en instantanée les offres auxquelles chaque Employeur est associé dans l'outil et agir sur la propriété d'une offre notamment en transférant les droits associés à la propriété d'une offre (accès aux données candidats, traitement des candidatures, etc) à un nouvel Employeur. **Tickets associés : #549 #550**
- à l'employeur lui -même d'agir et de transférer les droits associés à la propriété d'une offre **Tickets associés : #551 #552**

### **Rôle concerné :**
Employeur (recruteur)

### **Comportement souhaité :**
En back office dans l'onglet "Paramètres" < Onglet "Comptes admin" : à côté de la colonne répertoriant la liste des offres, ajouter un bouton "ne plus notifier cet utilisateur" (à la suite du bouton transférer le pr Ce bouton doit permettre au RF de ne plus notifier cet utilisateur et le retirer des acteurs concernés par les offres listées. 

### **Format :**
- Ajouter un bouton "ne plus notifier cet utilisateur"
- Lorsque le RF clique sur le bouton : le compte n'est plus associé aux offres listées et ne sera plus notifié.

**Comment by Grainedepaillette** [comment]
@btrd L'option ne doit apparaître que pour les employeur "créateurs" de l'offre.
