### ISSUE TITLE
Back / fonctionnalité "Transférer propriétaire de l'annonce"

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#551]
Uniquement si c'est moi le propriétaire actuel

**Comment by Grainedepaillette** [comment]
### **Contexte :**
Cette fonctionnalité concerne le RGPD et l'accès aux données candidats. Cette fonctionnalité vise à limiter l'accès à l'outil et plus précisément aux données candidats par des utilisateurs "Employeur" qui n'aurait plus le droit d'y accéder en raison d'un changement de poste/de service/de ministère ou d'un départ.

Cette fonctionnalité doit donc permettre :
- au RF de visualiser en instantanée les offres auxquelles chaque Employeur est associé dans l'outil et agir sur la propriété d'une offre notamment en transférant les droits associés à la propriété d'une offre (accès aux données candidats, traitement des candidatures, etc) à un nouvel Employeur. Tickets associés : #549 #550
- à l'employeur lui -même d'agir et de transférer les droits associés à la propriété d'une offre Tickets associés : #551 #552

### **Rôle concerné :**
Employeur (recruteur)

### **Comportement souhaité :**
En back office < Onglet "Offres" < Cartouche de l'offre < Bouton "..." (cf. écran) : ajouter une option "Changer le propriétaire" 
Lorsque le recruteur, actuel propriétaire de l'offre clique sur cette option, il est redirigé vers une page lui permettant de saisir l'adresse INTRADEF du  nouvel utilisateur qui sera propriétaire de l'offre. Ce nouveau compte doit automatiquement être taggué sur l'offre en tant qu'Employeur.
![Capture d’écran 2021-04-06 à 11 18 45](https://user-images.githubusercontent.com/51794334/113689327-842c7b80-96ca-11eb-8446-530197d9fbde.png)


### **Format :**
- Ajouter un bouton "changer le propriétaire"
- Lorsque le recruteur clique sur le bouton, accès à une page permettant de saisir et d'enregistrer l'adresse INTRADEF. (cf.écran ci -dessous) 
![Capture d’écran 2021-04-06 à 10 51 22](https://user-images.githubusercontent.com/51794334/113689415-9efef000-96ca-11eb-9069-1a63fdde48b9.png)

**Comment by Grainedepaillette** [comment]
@btrd L'option n'est affiché que lorsque l'utilisateur "Employeur" est créateur de l'offre d'emploi.

**Comment by btrd** [comment]
À tester ici
https://erecrutement-cvd-staging-pr889.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Testé, je confirme c'est opérationnel 

En complément serait-il possible de modifier la mention "Email du nouvel administrateur" par "Email du nouveau propriétaire de l'offre" ? Pour ce que ce soit plus parlant pour les recruteurs ? Car l'expression "administrateur" est utilisé pour le RF de l'outil. Merci.

**Comment by btrd** [comment]
C'est fait

**Comment by Grainedepaillette** [comment]
Je confirme, merci
