### ISSUE TITLE
 Back / fonctionnalité "Ne plus être propriétaire" 

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#552]

**Comment by Grainedepaillette** [comment]
### **Contexte :**
Cette fonctionnalité concerne le RGPD et l'accès aux données candidats. Cette fonctionnalité vise à limiter l'accès à l'outil et plus précisément aux données candidats par des utilisateurs "Employeur" qui n'aurait plus le droit d'y accéder en raison d'un changement de poste/de service/de ministère ou d'un départ.

Cette fonctionnalité doit donc permettre :
- au RF de visualiser en instantanée les offres auxquelles chaque Employeur est associé dans l'outil et agir sur la propriété d'une offre notamment en transférant les droits associés à la propriété d'une offre (accès aux données candidats, traitement des candidatures, etc) à un nouvel Employeur. Tickets associés : #549 #550
- à l'employeur lui -même d'agir et de transférer les droits associés à la propriété d'une offre Tickets associés : #551 #552

### **Rôle concerné :**
Employeur (recruteur)

### **Comportement souhaité :**
En back office < Onglet "Offres" < Cartouche de l'offre < Bouton "..." (cf. écran) : ajouter une option " Ne plus être notifié"
Lorsque le recruteur, actuel propriétaire de l'offre clique sur cette option, un message s'affiche sur l'écran pour lui demander confirmation (cf. écran ci - dessous).

![Capture d’écran 2021-04-06 à 11 29 25](https://user-images.githubusercontent.com/51794334/113690606-e5a11a00-96cb-11eb-8a9c-bf3faec7ce0b.png)

S'il confirme, alors il n'est plus notifié en tant qu'employeur sur l'offre en question : 
- retrait de la liste des acteurs notifiés dans le formulaire de l'offre
- retrait de la référence de l'offre dans les Paramètres/ Comptes admins/ Liste des offres associées à un utilisateur cf. #548

### **Format :**
- Ajouter une option " Ne plus être notifié" dans le menu déroulant "..." de l'offre.

**Comment by btrd** [comment]
![Capture d’écran 2021-04-07 à 19 01 11](https://user-images.githubusercontent.com/1385737/113905611-9fcf7900-97d3-11eb-9462-c99de9d47eaa.png)

On peut déjà le faire là non ? En cliquant sur la croix rouge

**Comment by Grainedepaillette** [comment]
@btrd Effectivement. Confirmes-tu que l'action de retrait de l'acteur à partir du formulaire offre correspondra au retrait de la référence de l'offre dans la liste des offres dans les paramètres ?
