### ISSUE TITLE
Back/ Offres : Date de publication offre postérieure aux dates de candidatures à l'offre 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#553]
Offres concernées : SID 218 et SID 151

**Comment by btrd** [comment]
Car on garde la dernière date de publication, si une offre est publiée le 10 juin puis mis en brouillon le lendemain et republié le 12 juin, la date de publication sera le 12 juin.

Est-ce que je change ça pour toujours garder la première date de publication ?

**Comment by Grainedepaillette** [comment]
Non, on va partir du principe que la dernière date de publication fait foi et que dans certains cas, si des candidatures ont une date antérieure c'est que l'offre a été publiée une 1ère fois en amont. 

Je ferme le ticket du coup :)
