### ISSUE TITLE
Compte candidat : 1an inactivité compte = suppression automatique compte 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#554]
Procédure de suppression automatique du compte candidat : 

a. SI connexion régulière ALORS aucune action 

b. SI absence de connexion 11 mois après la date de la dernière connexion ALORS 

i. Envoi d'un 1er courriel automatique : 

- Intitulé courriel : [Civils de la Défense] Votre compte candidat : mise à jour nécessaire 
- Texte : "Bonjour [Prénom/Nom candidat]. Nous vous invitons à mettre à jour votre compte candidat sur le site Civils de la Défense. Sans mise à jour de celui-ci sous 30 jours, nous vous informons qu'il sera supprimé automatiquement de notre base de données. [Bouton : Mettre à jour] L’équipe Civils de la Défense "

ii. Envoi d'un 2ème courriel automatique (30 jours après envoi du 1er courriel) : 

- Intitulé courriel : [Civils de la Défense] Votre compte candidat a été supprimé 
- Texte : "Bonjour [Prénom/Nom candidat]. Nous vous confirmons la suppression de votre compte candidat de notre base de données. Pour toute nouvelle candidature, nous vous invitons à créer un nouveau compte candidat sur notre site. [Bouton : Accéder au site] L’équipe Civils de la Défense"

**Comment by Grainedepaillette** [comment]
1ère liste données à conserver (non exhaustive) : 
- classe d’âge (année)
- sexe
- niveau de diplôme
- type d’emploi
- filière professionnelle
- employeur ministériel
- nombre de candidatures du candidat  
- durée du processus de recrutement

**Comment by yannski** [comment]
@Grainedepaillette vis-à-vis d'une candidature d'un candidat supprimé que fait-on avec les mails échangés ? Que fait-on avec les fichiers attachés ? Que fait-in avec les messages échangés ?

**Comment by Grainedepaillette** [comment]
![image005](https://user-images.githubusercontent.com/51794334/96722055-3c7c9680-13ad-11eb-929f-4d6f00e7dbb7.jpg)

**Comment by Grainedepaillette** [comment]
Test sera effectué situation réelle

**Comment by btrd** [comment]
Vérifier le bon fonctionnement du script de suppression
