### ISSUE TITLE
Back/Offres : pouvoir visualiser le contenu filtre "employeur" pour les rôles GE et CMG

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#557]
- En préproduction : rôles concernés : GE, ES, E et RH de proxi
- En production : remonté du GE "SGA" (cf. slack pour courriel) : copie écran ci - dessous
![unnamed](https://user-images.githubusercontent.com/51794334/76069540-5048c900-5f93-11ea-8a89-fc17f7670607.png)

La visualisation du contenu du filtre "Employeur" des onglets "Viver" et "Statistiques" est opérationnelle en préproduction  + production

**Comment by btrd** [comment]
@Grainedepaillette Ça a l'air ok je me permet de fermer

**Comment by Grainedepaillette** [comment]
@btrd Je réouvre le ticket mais apporte des précisions. 

### **Comportement constaté :** 
Aujourd'hui seul le rôle BANT (admin) peut visualiser le contenu du filtre "employeur" de l'onglet "offres" afin de filtrer et suivre les offres par employeur. 

Les autres rôles GE, ES, E, RH et CMG n'ont pas accès au contenu du filtre. Ceci est légitime pour les rôles ES, E et RH qui sont rattachés à une seule entité et un périmètre limité à un seul employeur (DIRISI par exemple) mais pas pour les rôles GE et CMG car ces rôles gèrent plusieurs employeurs et ont un périmètre plus large. Ils doivent donc pouvoir filtrer les offres par employeur au même titre que le BANT qui a la visibilité sur l'ensemble des offres d'emploi tous employeurs confondus. 

### **Comportement souhaité :** 

- Pour le rôle Grand employeur : Lorsqu'un utilisateur est notifié comme "grand employeur" sur une ou plusieurs offres, il doit pouvoir filtrer les offres par employeur. 
- Pour le rôle CMG : le rôle CMG doit pouvoir filtrer les offres par employeur.

**Comment by btrd** [comment]
Est-ce que ce serait pas plus simple de laisser le filtre Employeur à toutes les personnes ? De toute façon ils ont accès à l'information

**Comment by btrd** [comment]
Les BANT ont la visu sur tous les employeurs et les autres uniquement sur les sous-employeurs

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1005.osc-fr1.scalingo.io/

**Comment by Grainedepaillette** [comment]
@btrd Cela n'est pas opérationnel. Voici le résultat de mes tests : 

1. A l'aide du compte BANT, j'ai notifié 2 nouveaux acteurs sur une offre d'emploi : un compte grand employeur et un compte employeur superviseur. 

2. Une fois leur comptes confirmés, je clique sur le menu déroulant employeur, mais le contenu du champ est vide ALORS même que plusieurs entités "employeurs" sont renseignées dans les paramètres et devraient apparaître au niveau de l'onglet offres. 

Ce qu'on voit avec un rôle grand employeur ou employeur superviseur 
![Capture d’écran 2021-06-22 à 17.42.08.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/ef2e864b-dc4f-42cd-bbc0-35501fe37089)

Alors que dans les paramètres il y a ça : 
![Capture d’écran 2021-06-22 à 17.48.47.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/8263d865-b3f5-4326-b530-b469eb27c9de)

**Comment by btrd** [comment]
Comme convenu j'ai affiché le filtre pour tous les utilisateurs

**Comment by Grainedepaillette** [comment]
@btrd Trop bien c'est opérationnel !
