### ISSUE TITLE
Quand soumission d'une nouvelle candidature "Turbolinks is not defined"

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#559]
```ReferenceError: Turbolinks is not defined apply line 1 > scriptElement:1:1
    <anonyme> apply line 1 > scriptElement:1
    i rails-ujs.js:282
    t rails-ujs.js:195
    onreadystatechange rails-ujs.js:263
```

**Comment by Grainedepaillette** [comment]
1. Lorsque compte candidat (déjà créé) est connecté et qu'il repostule (mon espace candidat < nos offres < postuler) alors validation de la candidature 
![4](https://user-images.githubusercontent.com/51794334/76219194-be9cbe00-6215-11ea-9260-1a56d415fbd4.png)

2. Lorsque compte candidat (déjà créé) est déconnecté et qu'il repostule (nos offres < postuler) en saisissant les informations correspondant à son compte alors après le : 

- 1er clic sur bouton "je valide ma candidature "  : message indiquant que le courriel "n'est pas disponible" 
![2](https://user-images.githubusercontent.com/51794334/76216553-17b62300-6211-11ea-9dcb-b0f9a0b334e3.png)

- 2ème clic : affichage du formulaire mais champs vides qu'il y ait eu modification des champs ou non 
![3](https://user-images.githubusercontent.com/51794334/76216584-2b618980-6211-11ea-8228-484448412f57.png)

3. Lorsque candidat postule et créé son compte (nos offres < postuler) et qu'il complète les champs :  
- 1er clic sur bouton "je valide ma candidature " : erreur dans les champs saisis (ex : mot de passe).

- 2ème clic : affichage du formulaire mais champs vides qu'il y ait eu modification des champs ou non 
![1](https://user-images.githubusercontent.com/51794334/76216697-5946ce00-6211-11ea-87ec-5918eb9d6b60.png)

4. Lorsque candidat postule et créé son compte (nos offres < postuler) et qu'il complète les champs 
- 1er clic sur bouton "je valide ma candidature " : validation candidature (car aucune erreur dans la saisies des champs)
![8](https://user-images.githubusercontent.com/51794334/76219056-80070380-6215-11ea-937d-dee44c3e7906.png)

**Comment by Grainedepaillette** [comment]
Même résultat suite à des tests effectués en production

**Comment by yannski** [comment]
Le problème ici est le suivant : le formulaire de soumission ne comporte qu'un encart "Création de compte". Visiblement les gens s'attendent à pouvoir s'authentifier ici aussi. Je vais voir ce que je peux faire.
