### ISSUE TITLE
Back/Création comptes : non réception courriels 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#560]
Derniers courriels reçus le 4 mars. Tests réalisés sur pré-production (avec comptes Gmail)

PB : Non réception courriel "instruction de confirmation" 
- lorsque création compte par le BANT pour rôles employeur, GE, ES et RH de proxi 

- lorsque création compte par employeur pour rôles GE, ES et RH de proxi lorsque notification sur une offre 

Courriel BANT : testversionstaging@gmail.com
Courriel employeur : testversionstaging+e1@gmail.com

**Comment by yannski** [comment]
As-tu vérifié dans le dossier spam ?

**Comment by Grainedepaillette** [comment]
Oui

**Comment by Grainedepaillette** [comment]
@yannski Test réalisé en prod et même résultat. 
1 Tentative de renvoi du courriel d'activation (avec le rôle BANT)
Courriel : drh-md-srhc-civilsdeladefense.resp-aff-juridique.fct@intradef.gouv.fr
