### ISSUE TITLE
Back/Carte candidat : absence affichage bouton "demander" + "ne plus demander" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#564]
Test réalisé en production. 

1/ De l'étape "nouveau" à "refusé après entretien phys." : visualisation des boutons "demander" + "ne plus demander". 

![image](https://user-images.githubusercontent.com/51794334/76439828-4a048380-63bd-11ea-855b-aeba825074d2.png)

![image](https://user-images.githubusercontent.com/51794334/76439956-791af500-63bd-11ea-940f-5badd434fcf2.png)

2/ Lorsque candidature est à l'étape "retenue" + clic sur bouton "demander" d'une des PJ (ici copie diplômes) alors toutes les PJ sont sélectionnées et absence affichage du bouton "ne plus demander" sauf pour la PJ "copie diplômes" 

![image](https://user-images.githubusercontent.com/51794334/76440960-f1ce8100-63be-11ea-998f-ab88b7c6cac9.png)

**Comment by Grainedepaillette** [comment]
@yannski Test réalisé en prod et même résultat. 

Courriel candidat : testversionstagingcandidat+05@gmail.com

**Comment by btrd** [comment]
Quel est le comportement souhaiter ?

**Comment by btrd** [comment]
![Capture d’écran 2021-03-17 à 18 50 10](https://user-images.githubusercontent.com/1385737/111517803-c14dbf80-8755-11eb-84d7-f1aee9f5791a.png)

Il existe 4 cas différents sur cet écran, je vais prendre un exemple pour chaque : 
- CV : obligatoire et on a un fichier
- Bulletins de paie : uniquement une validation car le type de fichier est géré hors outils
- Pièce Facultatif : non obligatoire mais demandé par un recruteur, il peut retirer sa demande
- Carte  : obligatoire, le recruteur ne peut pas retirer un document obligatoire

Le ticket semble revenir sur la dernière règle : il faut qu'un recruteur puisse retirer une demande d'un document pour une candidature ?

**Comment by Grainedepaillette** [comment]
@btrd Après passage en revue de la fonctionnalité, l'affichage des options pour chaque P.J est lié : 
- au caractère obligatoire ou non de la P.J
- mais surtout au statut de la candidature (élément non pris en compte lors de l'ouverture du ticket..) 

### **Voici la DEMO en production** 

https://user-images.githubusercontent.com/51794334/112521806-38f69c80-8d9d-11eb-8561-0ee5a3d62532.mov

### **Conclusion :** 
- Tant qu'un candidat n'est pas à l'étape retenu, les P.J (qu'elles soient obligatoire ou pas cf. paramètres) peuvent être demander par le recruteur puis retirer 
- Lorsqu'un candidat est à l'étape "retenu" de fait, les P.J obligatoires ne peuvent être retirées. Seules les P.J optionnelles peuvent être retirer par le recruteur. 

Pour répondre à ta dernière question : le recruteur ne doit pas pouvoir retirer un document obligatoire lorsque le candidat est retenu car risque de compromettre le recrutement. 

Je te propose de fermer le ticket, car les règles sont correctes et la fonctionnalité opérationnelle
