### ISSUE TITLE
Back/Offres archivées : non enregistrement modifications 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#568]
- Test réalisé en pré-prod

- Lorsque modification d'une offre archivée (texte) + clic bouton "enregistrer" ou "désarchiver" : redirection vers la liste des offres actives mais non enregistrement des modifications apportées à l'offre archivée. Seule la modification du domaine professionnel est enregistrée.

**Comment by btrd** [comment]
Il faut uniquement que le titre ne soit pas modifiable quand l'offre est archivée ?

Si c'est ça, c'est corrigé
