### ISSUE TITLE
Back/Offres archivées : erreur affichage texte

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#571]
- Test réalisé en prod

- Lorsque clic sur bouton "modifier" une offre archivée alors affichage du texte avec des caractères spéciaux. 

![image](https://user-images.githubusercontent.com/51794334/76547500-8e5f5480-648d-11ea-8872-6927e914d061.png)

**Comment by btrd** [comment]
On a d
