### ISSUE TITLE
Back/Vivier : non visualisation listes candidats

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#578]
- Test pré-prod et prod. Vidéo démonstration dispo sur Slack : https://fabnum-minarm.slack.com/archives/CC1AS8E22/p1584636941001200
- Rôles concernés : Employeur , employeur superviseur et grand employeur. Le rôle BANT visualise bien les listes. 

Descriptif PB : 
- Lorsque clic sur onglet "Vivier" + clic " créer une nouvelle liste" : l'écran est grisé. Impossibilité de créer une liste ou d'accéder aux listes existantes.

**Comment by yannski** [comment]
@Grainedepaillette est-ce qu'il faut effectivement aussi autoriser les employeurs superviseurs et grand employeur à faire des listes ? Je me permets de poser la question étant donné qu'ils ont seulement le droit de lecture sur toutes les autres "ressources" de la plateforme.

**Comment by Grainedepaillette** [comment]
@yannski Le bouton pour la création de liste est actuellement dispo dans l'onglet "vivier" pour les rôles de GE et ES mais il serait en effet plus cohérent que la création/gestion des listes relève uniquement du rôle employeur
