### ISSUE TITLE
Back/Paramètres : erreur affichage texte 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#593]
- Test réalisé en pré-prod
- PB : Lorsque l'utilisateur effectue une modification texte et clic sur bouton "modifier" alors les modifications apportées sont enregistrées. Mais si l'on revient sur le champ modifié alors apparition de caractères spéciaux. Si l'on actualise la page, le texte apparaît normalement. Cf. Vidéo Slack : https://fabnum-minarm.slack.com/archives/CC1AS8E22/p1585739623003500

**Comment by btrd** [comment]
@Grainedepaillette Tu pourrais uploader la vidéo sur Github ? J'ai pas accès à ce Slack. Merci !

**Comment by Grainedepaillette** [comment]
Après test, ce ticket ne me semble plus d'actualité, je le ferme et le réouvrirai si nécessaire.
