### ISSUE TITLE
Tester API avec portail commun 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#598]
[API_Liste objets.pdf](https://github.com/betagouv/civilsdeladefense/files/4455707/API_Liste.objets.pdf)

**Comment by yannski** [comment]
J'aurais besoin de quelques renseignements supplémentaires :
- que veut dire "Type d’offre" ? CDI ou CDD ?
- pour "Niveau d’étude (valeur : 2 à 8)" à quoi correspondent les chiffres ?
- comment remplir "Source (contractuels/stage/etc.)" ?

**Comment by Grainedepaillette** [comment]
- Type d'offre = CDI/CDD
- Les chiffres correspondent au [niveau du diplôme ](https://www.service-public.fr/particuliers/vosdroits/F199) selon la nomenclature des diplômes de l'Etat. Deux possibilités pour API : 

         1. Mettre à jour les intitulés des diplômes dans CVD (Paramètres) pour s'aligner sur ceux de 
            la nomenclature des diplômes de l'Etat
         2. Associer les intitulés des diplômes tels qu'ils existent dans CVD aux chiffres de la 
             nomenclature 

- Remplir "Source" reviens à compléter par l'URL unique de l'offre/dédiée à l'offre
