### ISSUE TITLE
Back / Rédaction d'offre : avoir la possibilité de saisir plusieurs critères au champ "Avantages en nature"

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#623]

**Comment by Grainedepaillette** [comment]
@btrd 

### **Comportement constaté :** 
Aujourd'hui lorsqu'un recruteur rédige une offre d'emploi, il ne peut pas sélectionner plusieurs avantages en nature via le menu déroulant. Cela pose problème car une offre d'emploi peut cumuler plusieurs avantages en nature. Typiquement : crèche + restauration collective. 

### **Comportement souhaité :** 

Pouvoir sélectionner plusieurs avantages en nature via le formulaire de rédaction d'une offre. Ne pourrais-t-on pas reprendre ce qui a été fait pour les langues étrangères en front au niveau du formulaire de candidature ? Si je souhaite ajouter un avantage en nature, je clique sur un bouton ajouter et un 2ème menu déroulant apparaît. Qu'en penses-tu ?

**Comment by btrd** [comment]
> Ne pourrais-t-on pas reprendre ce qui a été fait pour les langues étrangères en front au niveau du formulaire de candidature ?

Ce qui a été fait pour les langues étrangères est côté front, là nous somme côté back c'est un peu différent. Mais dans l'idée oui.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr967.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Hello @btrd 
- Le menu déroulant ne s'ouvre pas 
- La taille de l'encadré a été modifié 
- L'intitulé est passé en anglais 

https://user-images.githubusercontent.com/58481185/119469077-54533900-bd47-11eb-8f5d-f1b5bd7ad1dd.mov

**Comment by btrd** [comment]
C'est corrigé (il n'y avais pas de Bénéfices en natures par défaut)

![Capture d’écran 2021-05-25 à 16 23 45](https://user-images.githubusercontent.com/1385737/119514776-97c49c00-bd75-11eb-9611-b007dbf279e6.png)

Pour info ça ressemble à ça, c'est le comportement par défaut ce qui m'a permis de gagner du temps sur le développement.

**Comment by btrd** [comment]
Corrigé

**Comment by btrd** [comment]
C'est amélioré

**Comment by Grainedepaillette** [comment]
@btrd Voici les retours suite au test : 

**1) L'intitulé est différent selon les pages sur l'outil :** 
- en back, page de rédaction de l'offre : " Avantages en nature" : 
- en back, cartouche offre / onglet "description" : "Bénéfices en nature" 
- en back, paramètres : "Bénéfices en nature" 
- en front, page description offre : "Bénéfices en nature" 

Il faudrait mettre l'intitulé "Avantage(s) en nature"  sur toutes les pages. 

**2) L'intitulé n'est pas en gras et il n'y a pas d'icône correspondant  sur les pages de descriptifs des offres en front et en back (cf. écrans)** 

**3) Il y a 2 fois ":" après l'intitulé sur les pages de descriptifs des offres en front et en back (cf. écrans)** 
![Capture d’écran 2021-06-10 à 15.52.30.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/3e2f353e-f115-4e5a-9e7e-5f1420b0aac8)

![Capture d’écran 2021-06-10 à 15.52.47.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/df0281e5-4d33-460f-aa1d-f90ef3a5c17e)

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd C'est OK sauf pour l'intitulé au niveau du formulaire de rédaction d'une offre : il manque un "s". (cf. écrans). Merci. 
![Capture d’écran 2021-06-16 à 17.05.40.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/6b2ebbd5-935d-4a0d-9b62-c64a3d5fd418)

**Comment by btrd** [comment]
Corrigé

**Comment by Grainedepaillette** [comment]
@btrd EN production l'intitulé du champ au niveau du formulaire n'est pas conforme : il y a un "s" à "nature" (cf. écran). Il faudrait retirer le "s". 

![Capture d’écran 2021-06-22 à 17.25.18.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/936f0554-bef2-4d2a-8cad-0d541be2a8f2)
