### ISSUE TITLE
Paramètre / Estimations salariales : non enregistrement ajout d'une estimation salariale

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#624]
Tests réalisés en pré-prod et en prod.

Avant saisie des champs, affiche message erreur + croix rouge sur les champs vides. 
Après saisie et clic sur "ajouter", non enregistrement de l'ajout, les champs se vident et affichent message "doit exister"

**Comment by yannski** [comment]
Je n'arrive pas à reproduire. Peux-tu donner un exemple ?

**Comment by mch2608** [comment]
Lorsque saisie des champs en oubliant de remplir l'un des champs "estimation annuels bruts" et "estimation annuels nets" et clic sur "ajouter", basculement vers une nouvelle page d'ajout dans laquelle: 
- message indiquant la non saisie dans le champ oublié
- les champs "catégorie" , "filière" et "expérience" se vident

<img width="1320" alt="Capture d’écran 2020-05-28 à 18 10 59" src="https://user-images.githubusercontent.com/58481185/83166060-a3ec2e00-a10e-11ea-92df-5767ae9e157a.png">

Lorsque saisie de tous les champs dans cette nouvelle page et clic sur bouton "ajouter": 
- non enregistrement de l'ajout
- les champs "catégorie", "expérience", "filière" se vident et affichent un message d'erreur + croix rouge.  
<img width="1099" alt="Capture d’écran 2020-05-28 à 18 15 31" src="https://user-images.githubusercontent.com/58481185/83166479-486e7000-a10f-11ea-815b-63fcd4ab8379.png">

<img width="1103" alt="Capture d’écran 2020-05-28 à 18 16 40" src="https://user-images.githubusercontent.com/58481185/83166573-6b991f80-a10f-11ea-833b-f9081e53bf74.png">

**Comment by Grainedepaillette** [comment]
@brtd  Après test, ce n'est plus d'actualité. La fonctionnalité est opérationnelle (cf. écran) 
![Capture d’écran 2021-05-04 à 10.55.44.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/0a575e3f-1309-40c5-aca2-1c1e398a8338)
