### ISSUE TITLE
Front / Page accueil : non affichage instantanée de la recherche après sélection d'un filtre sur Google Chrome (Version 83.0.4103.116) 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#627]
- Test réalisé en pré-prof et prod
- PB :  Lorsqu'on sélectionne un critère dans un filtre, la page ne se rafraîchit pas automatiquement pour afficher les offres correspondant au critère choisi. 
Les résultats de la recherche filtrée s'affichent lorsque une fois positionné sur le champ "Rechercher" vide, clic sur bouton "Entrer" du clavier. 
- Comportement souhaité : affichage instantanée de la recherche après sélection d'un filtre sans clic sur bouton "Entrer" du clavier sur le champ "Rechercher"

**Comment by yannski** [comment]
Je n'arrive pas à reproduire ce problème. Pour moi le rafraîchissement est immédiat. Peux-tu me donner ta version de navigateur et éventuellement un moyen de reproduire le problème ?

**Comment by mch2608** [comment]
Test réalisé sur la version 83.0.4103.116 de Google Chrome

Aperçu de la page après sélection d'un filtre: 

![Capture3](https://user-images.githubusercontent.com/58481185/87663146-a7da1b00-c763-11ea-94d9-b1e2476f69a5.PNG)

Malgré la sélection du filtre "Administration des systèmes d'information", toutes les offres sont affichés sur la page.

**Comment by btrd** [comment]
@Grainedepaillette Je me permet de fermer car j'imagine que c'est corrigé avec la nouvelle page d'acceuil.

**Comment by Grainedepaillette** [comment]
@btrd C'est ok, merci
