### ISSUE TITLE
Activer le retour de mail par Gandi

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#668]
Activer l'adresse rejoindre AT contractuels-etc.com

**Comment by Grainedepaillette** [comment]
@btrd, voici quelques précisions sur ce ticket : 

### **Comportement constaté** : Les mails envoyés par les candidats à la boîte fonctionnelle de la plateforme sont hébergés chez OVH (service tiers utilisé à la création de l'outil)

### **Comportement souhaité** : Les mails envoyés par les candidats à la boîte fonctionnelle de la plateforme doivent être hébergés chez Gandi (nouveau service tiers souhaité). 

Un changement de service doit être effectué. Pour ton info, l'instance ANSSI est déjà dotée du service Gandi pour la réception des courriels. 

Pour les SPEC techniques, je laisse @yannski t'apporter les infos nécessaires.

**Comment by yannski** [comment]
Demande de création de boîte mail en cours.

**Comment by btrd** [comment]
@yannski As-tu des nouvelles informations concernant la demande de création ?

**Comment by btrd** [comment]
Informations reçu en MP sur Slack

**Comment by btrd** [comment]
@Grainedepaillette Tout est en place pour faire le changement, j'attends votre GO pour l'effectuer.

**Comment by Grainedepaillette** [comment]
@btrd C'est OK
