### ISSUE TITLE
Vivier : lorsque candidat postule à plusieurs offres, une seule carte candidat doit apparaître 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#670]
- Comportement constaté : aujourd'hui le vivier est un vivier de candidatures, à chaque fois qu'un candidat postule une nouvelle carte candidat est créée. Chaque carte candidat correspond à une candidature sur un poste.  

- Comportement souhaité : une seule carte candidat par candidat. La carte candidat comprendrait comme aujourd'hui un historique des candidatures. Si l'on sélectionne une candidature à partir de l'historique alors chargement de la carte candidat associée à la candidature sélectionnée.

**Comment by mch2608** [comment]
Ticket à fermer
