### ISSUE TITLE
Back/Offres : ajouter date passage en brouillon 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#672]

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1031.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd C'est dispo en staging ? Car j'ai fait les tests pour la date de mise en pause mais pas pour la mise en brouillon. C'est la même fonctionnalité mais je voulais m'assurer que c'est ok. Merci.

**Comment by btrd** [comment]
Oui dispo en staging

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel en staging avec Mozilla.
