### ISSUE TITLE
Back/Offres : ajouter date mise en pause

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#673]

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1031.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Après test : 

- lorsque l'on suit le chemin suivant : onglet < liste de offres< clic bouton "modifier" de l'offre souhaitée < accès formulaire offre < clic bouton "mettre en pause" ALORS la date se met à jour. 

- lorsque l'on suit le chemin suivant : onglet < liste de offres< clic bouton "..." de l'offre souhaitée < accès au menu déroulant < sélection action "mettre en pause" ALORS, la date ne se met pas à jour.

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd Testé avec Mozilla c'est opérationnel.
