### ISSUE TITLE
Back/Trello : non accès à colonne "rédaction contrat" si toutes les P.J ne sont pas chargées et pas validées

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#674]

**Comment by btrd** [comment]
Est-ce qu'on s'intéresse aux documents qui sont dans le l'état Retenu(e) ou aussi ceux qui sont dans les états précédent ?

<img width="1178" alt="Capture d’écran 2021-06-30 à 10 54 47" src="https://user-images.githubusercontent.com/1385737/123932294-977d7900-d991-11eb-8d71-f13c2aa8ed36.png">

Par exemple dans ce cas pour passer à l'état "Rédaction contract" est-ce qu'il faut avoir validé les documents CV et LM en plus de Carte d'identité et Contrat ?

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1028.osc-fr1.scalingo.io

**Comment by btrd** [comment]
Ne demander que les documents du current state

**Comment by Grainedepaillette** [comment]
@btrd La fonctionnalité est opérationnelle (au niveau du Trello + de la carte candidat/menu déroulant). En revanche au niveau de la carte candidat, le message accompagnant le changement de statut de la candidature est apparaît très rapidement et est illisible pour les utilisateurs (cf. vidéo). 

Pourrais-tu prolonger de quelques secondes son affichage? D'autant que l'explication est relativement important et longue pour le statut retenu + rédaction contrat. 
Merci. https://images.zenhubusercontent.com/146276066/02540299-cc15-480a-b4b2-23c0b3f407f8/message_changement_statut.mov

**Comment by btrd** [comment]
C'est corrigé

**Comment by Grainedepaillette** [comment]
@btrd Testé sur Mozilla c'est opérationnel
