### ISSUE TITLE
Front/ Lien "Inscription" : afficher message confirmation création compte 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#675]
- Comportement constaté : lorsqu'un candidat crée son compte à partir du lien "Inscription" en front, aucun message de confirmation de la création de compte n'apparaît alors qu'il reçoit bien le courriel de confirmation de compte dans sa boîte mail par la suite. 

- Comportement souhaité : afficher un message de confirmation de la création de compte lorsque le candidat crée son compte via le lien "Inscription" (cf. création de compte via le formulaire de candidature)

**Comment by yannski** [comment]
La notif ne s'affiche pas une fois que j'ai rempli le formulaire d'inscription :/

**Comment by btrd** [comment]
Ça a bien fonctionné chez moi, je suis passé par ce lien https://erecrutement-cvd-staging-pr774.osc-fr1.scalingo.io/users/sign_up

<img width="946" alt="Capture d’écran 2021-01-19 à 16 35 52" src="https://user-images.githubusercontent.com/1385737/105056416-7163bc80-5a74-11eb-90de-a5740d0cf992.png">

**Comment by yannski** [comment]
@btrd quand on a un grand écran, la notif a trop de chance de passer inaperçue.

Je propose d'utiliser les notifs JS déjà utilisées ailleurs sur le site.

**Comment by yannski** [comment]
@btrd je propose de rediriger vers une page spécifique qui intégrera le message de la notif.

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)
