### ISSUE TITLE
Back/Offre : afficher l'intitulé de l'étape de recrutement dans la cartouche de l'offre 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#681]
- Comportement constaté : aujourd'hui l'étape de recrutement dans la cartouche de l'offre est un numéro, mais peu lisible pour les utilisateurs bien qu'une bulle d'information apparaisse avec l'intitulé de l'offre. 

- Comportement souhaité : afficher l'intitulé de l'étape de recrutement dans la cartouche de l'offre.

**Comment by btrd** [comment]
<img width="917" alt="Capture d’écran 2021-06-16 à 15 53 50" src="https://user-images.githubusercontent.com/1385737/122231834-0c917e80-cebb-11eb-8422-0a57edcf154f.png">

Ça a l'air ok maintenant

**Comment by Grainedepaillette** [comment]
@btrd Ce ticket concernait le back office : 
![Capture d’écran 2021-06-22 à 17.01.04.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/9239f026-71b8-4909-82a6-f336e29367e5)

Le dernier chiffre apparaissant sur la cartouche correspond au numéro de l'étape du processus du Trello mais c'est peu parlant bien que lorsque l'on glisse la souris, une bulle d'info apparaît avec l'intitulé de l'étape. On ne voit pas "d'un seul coup d'oeil" l'étape la + avancée du processus de recrutement pour une offre. 

Mais comme indiqué ce ticket n'est pas prioritaire :) 

Effectivement en front office/ côté candidat, cela apparaît bien depuis le début.
