### ISSUE TITLE
Back/Statistiques : pouvoir exporter les données 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#682]

**Comment by Grainedepaillette** [comment]
Créer un bouton "exporter" en bas de page. 

### **1. Pouvoir exporter les données statistiques candidatures** 

La liste des données à exporter :

### **Données présentes sur la page identifiée**
- Filtres choisis 
- Nombre de candidatures
- Période choisie
- Statistiques - Pourvoi des postes
- Statistiques des candidats refusés
- Statistiques des candidats 

### **Données à créer**
- Date de l’export 
- Utilisateur à l’origine de l’export

### **2. Pouvoir exporter les données statistiques offres** 

### **Données présentes sur la page identifiée**
- Filtres choisis 
- Nombre de candidatures
- Période choisie
- Statistiques offres : nombre offres publiées #514  ; nombre offres pourvues #516 ; nombres offres à pourvoir #517 ; nombre de candidature #518  ; Délai moyen recrutement #755 ; nombre de candidats disponibles #519 
### **Données présentes sur autres pages**
- Date de l’export 
- Utilisateur à l’origine de l’export

**Comment by btrd** [comment]
@Grainedepaillette Ce serait possible d'avoir un fichier d'exemple pour voir le format voulu ?

**Comment by Grainedepaillette** [comment]
@btrd Comme demandé, voici un exemple 
 Pour les stats candidatures (fichier 1) 
Pour les stats offres (fichier 2) 

FICHIER 1 
[https://app.zenhub.com/files/146276066/536be92a-9064-42cb-966c-09e77cc20f4b/download](https://app.zenhub.com/files/146276066/536be92a-9064-42cb-966c-09e77cc20f4b/download)

FICHIER 2 
[https://app.zenhub.com/files/146276066/9c08dad5-4b22-4469-bd64-b0b7f6a6e9b4/download](https://app.zenhub.com/files/146276066/9c08dad5-4b22-4469-bd64-b0b7f6a6e9b4/download)

**Comment by btrd** [comment]
@mch2608 Disponible https://erecrutement-cvd-staging-pr963.osc-fr1.scalingo.io/

**Comment by mch2608** [comment]
STATISTIQUES CANDIDATURES
A quoi correspond le chiffre présent ligne 4 en dessous de l'utilisateur à l'origine de l'export ? 
Mise en page : 
- le nom de la rubrique "Statistiques des candidatures - pourvoi des postes" n'apparaît pas
- la donnée "Genre" apparait sur la même lignée que le nom de la rubrique "Statistiques des candidats", ce serait plus clair qu'elle apparaisse sur la ligne du dessous 
- la donnée liée au filtre choisis apparait dans la ligne en dessous de l'intitulé, ce serait plus clair qu'elle apparaisse sur la même ligne que l'intitulé du filtre

**Comment by btrd** [comment]
- A quoi correspond le chiffre présent ligne 4 en dessous de l'utilisateur à l'origine de l'export ?
Une erreur, c'est retiré

- le nom de la rubrique "Statistiques des candidatures - pourvoi des postes" n'apparaît pas
Ajouté

- la donnée "Genre" apparait sur la même lignée que le nom de la rubrique "Statistiques des candidats", ce serait plus clair qu'elle apparaisse sur la ligne du dessous
- la donnée liée au filtre choisis apparait dans la ligne en dessous de l'intitulé, ce serait plus clair qu'elle apparaisse sur la même ligne que l'intitulé du filtre
J'ai repris l'exemple de Sarah, tu peux me refaire un exemple avec ce que tu veux ?

**Comment by mch2608** [comment]
[~$Modèle statistiques offres.xlsx](https://github.com/betagouv/civilsdeladefense/files/6514774/Modele.statistiques.offres.xlsx)

**Comment by mch2608** [comment]
L'exemple de Sarah s'appuyait sur la possibilité de fusion entre cellule. Voici l'exemple pour la mise en page sans fusion de cellule: 
[~$Modèle statistiques offres.xlsx](https://github.com/betagouv/civilsdeladefense/files/6514810/Modele.statistiques.offres.xlsx)

**Comment by btrd** [comment]
Le fichier ne fonctionne pas chez moi

**Comment by Grainedepaillette** [comment]
@mch2608 pourrais-tu partager le document sur mattermost ? Car il me semble que ce ne soit pas dommageable que ce soit sur la même ligne, te propose de comparer les 2 docs avant modifications du dev.

**Comment by mch2608** [comment]
Document envoyé à Jean le 27 mai sur Mattermost. @btrd l'as-tu bien reçu ?

**Comment by btrd** [comment]
Bien reçu mais je serais de l'avis de @Grainedepaillette 

> Car il me semble que ce ne soit pas dommageable que ce soit sur la même ligne

**Comment by Grainedepaillette** [comment]
@btrd Après test, voici les résultats : 

1) Page stats candidatures : 
- le bouton "exporter" doit être positionné en bas de page à droite (comme c'est le cas actuellement pour la page offres et vivier en production) 
- le fichier CSV n'a pas pris en compte les cellules fusionnées du modèle que je t'avais communiqué, donc de nombreuses données ne sont pas présents dans l'export. Aussi, voici le fichier (sans fusion de cellules qui doit être intégré)

2) Page stats offres : 
- le bouton "exporter" n'apparaît. Il faudrait ajouter le bouton et positionner en bas de page à droite (comme c'est le cas actuellement pour la page offres et vivier en production) 
- Voici le fichier (sans fusion de cellules qui doit être intégré) afin que toutes les données soient prises en compte.

**Comment by btrd** [comment]
> Page stats offres

Les stats offres ont été effectué sur un autre ticket, ça m'arrange si tu créés un nouveau ticket pour gérer ça (pour ne pas retarder plus la mise en production)

**Comment by btrd** [comment]
1.1. C'est déplacé
1.2.  Je ne fois pas de différences dans les données

**Comment by Grainedepaillette** [comment]
@btrd 
C'est ok pour le bouton 'export' et le contenu de l'export pour les stats candidatures. 

Pour la fonctionnalité stats offres, j'ouvre un nouveau ticket

**Comment by Grainedepaillette** [comment]
@btrd Je me permets de réouvrir le ticket, car **en production et pré-prod** au niveau de la page statistiques candidats : on a 2 boutons "exporter" : 1 en haut à gauche de la page et le 2ème en bas à droite de la page (comme demandé). Pourrais-tu supprimer le 1er bouton (cf. écran). Merci. 
![Capture d’écran 2021-06-30 à 15 37 56](https://user-images.githubusercontent.com/51794334/123970175-2fdb2400-d9b9-11eb-9198-32224e55270c.png)
![Capture d’écran 2021-06-30 à 15 38 02](https://user-images.githubusercontent.com/51794334/123970179-3073ba80-d9b9-11eb-9ec0-41e29b903616.png)

**Comment by Grainedepaillette** [comment]
@btrd Corrigé en pré-prod mais pas encore visible en prod (je suppose que c'est normal).
