### ISSUE TITLE
Général/expiration session utilisateur : affichage compteur avant expiration 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#683]
- Comportement constaté : aujourd'hui, session utilisateur expire au bout d'1h. Lorsqu'elle expire et que l'utilisateur saisit à nouveau ses identifiants, affichage de la page sur laquelle il était avant expiration #363

- Comportement souhaité : 
Afficher un compteur avant expiration de la session --> voir combien de temps avant, 5min ?

**Comment by Grainedepaillette** [comment]
@btrd Voici quelques précisions : 

### **Comportement constaté :** 

Lorsque le délai de 1h est écoulé sans que l'utilisateur n'ait effectué d'actions (clic bouton) ALORS il est éjecté du portail sans alerte/avertissement préalable ce qui peut être préjudiciable (perte des données saisies notamment #850). Aucun dispositif n'est en place pour permettre à l'utilisateur de prendre les dispositions nécessaires. 

### **Comportement souhaité :** 

Afficher un message d'information, indiquant que sans action de la part de l'utilisateur dans le prochaines minutes (5 ou 10min), sa session expirera et donner la possibilité de poursuivre la navigation. 

**2 formats possibles du message :** 
- afficher un message indiquant le délai restant et l'heure exacte à laquelle la session sera expirée + bouton " maintenir la session active" 
- afficher un compte à rebours + bouton " maintenir la session active" 

Cette fonctionnalité répond également au RGAA.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1043.osc-fr1.scalingo.io

J'ai affiché le message où bout de 5 sec sans action (au lieu de 50min) pour tester plus facilement.

Pour information en prod actuellement la durée est de 30min et non pas 1h, ça va être corrigé en même temps.

Je n'ai pas mis de bouton pour recharger la page, j'ai peur que l'utilisateur recharge la page sans sauvegarder ses données (quand il est en train d'éditer une offre par exemple).

**Comment by Grainedepaillette** [comment]
@btrd environnement plus dispo, et sur staging je ne vois rien apparaître.

**Comment by btrd** [comment]
> environnement plus dispo, et sur staging je ne vois rien apparaître

C'est corrigé

> Petite précision au cas où le ticket n'était pas explicite : le dispositif doit être disponible en back et en front.

Effectivement c'est une bonne précision car actuellement le système de déconnexion côté front n'existe pas. Je veux bien un ticket spécifique pour cette partie et garder ce ticket uniquement pour l'alerte côté back.

**Comment by Grainedepaillette** [comment]
@btrd Après test sur Mozilla : le message apparaît bien au bout de 5sec mais reste affiché après l'horaire indiqué dans le message (17H16) et le compte n'est pas déconnecté. Si l'utilisateur rafraîchit la page (à 17H18) alors le message disparaît. 

En complément, au niveau du message serait-il possible de mettre ce texte : **"Sans action de votre part dans les 10 prochaines minutes, votre session expirera et vous serez déconnecté de la plateforme à 17H16".**

**Comment by btrd** [comment]
> Après test sur Mozilla : le message apparaît bien au bout de 5sec mais reste affiché après l'horaire indiqué dans le message (17H16) et le compte n'est pas déconnecté. Si l'utilisateur rafraîchit la page (à 17H18) alors le message disparaît.

Quel est le comportement souhaité ?

**Comment by Grainedepaillette** [comment]
> Effectivement c'est une bonne précision car actuellement le système de déconnexion côté front n'existe pas. Je veux bien un ticket spécifique pour cette partie et garder ce ticket uniquement pour l'alerte côté back.

C'est fait, [ticket 1067](https://app.zenhub.com/workspaces/e---recrutement-contractuels-606dc7f03bd5d900102637b6/issues/betagouv/civilsdeladefense/1067) ouvert.

**Comment by btrd** [comment]
Le message a été modifié

**Comment by btrd** [comment]
J'ai mis 1 minute pour la déconnexion.

**Comment by Grainedepaillette** [comment]
@btrd Bien pris. Après tests, voici les résultats : 

**PB 1** **Lorsque l'utilisateur clique sur un onglet OU rafraîchit la page** passé le délai ALORS son compte est effectivement déconnecté et la page authentification apparaît MAIS le message d'information apparaît au bout de quelques secondes au niveau de la page d'authentification (cf. écran) 
![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/3bee67be-0450-4ac4-ab64-3e295fc598a6)

**PB 2**  Au niveau du message d'information, et de l'heure, les "0" ne sont pas pris en compte dans le message affiché. 
![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/761e51d5-c306-43ff-b268-533d41f173d9)

**Comment by btrd** [comment]
PB1: Si c'est ok je veux bien un nouveau ticket pour corriger ça, ça va prendre un peu de temps et j'aimerais passer sur les tickets PEP

PB2: Corrigé

**Comment by Grainedepaillette** [comment]
PB1 : nouveau ticket ouvert [1073](https://app.zenhub.com/workspaces/e---recrutement-contractuels-606dc7f03bd5d900102637b6/issues/betagouv/civilsdeladefense/1073)
