### ISSUE TITLE
Back/Paramètres : supprimer champ "Grand Employeur " dans formulaire invitation nouveau compte admin sur Internet Explorer

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#694]
Comportements constatés : 
-	Lorsqu’un membre du BANT remplit le formulaire de création de compte employeur **à partir d’Internet Explorer**, présence d’un champ « Grand Employeur" dans le formulaire 
-	Le membre du BANT remplit instinctivement le champ « Grand Employeur » 

PB : 
-	Champ « Grand Employeur » ne devrait pas exister 
-	L’admin ajouté sera recensé sur l’outil comme un employeur de son grand employeur, et non de son service

Comportement souhaité :
-	Suppression le champ « Grand Employeur » existant sur Internet Explorer.  

![image](https://user-images.githubusercontent.com/58481185/92620115-91af8d80-f2c2-11ea-8d8b-5c6a62909e28.png)

PS: Champ "grand employeur" inexistant sur les navigateurs Firefox, Google Chrome (et Safari)

**Comment by yannski** [comment]
@mch2608 peux-tu me préciser la version d'Internet Explorer utilisé ?

**Comment by mch2608** [comment]
> 
> 
> @mch2608 peux-tu me préciser la version d'Internet Explorer utilisé ?

Version Internet Explorer 11.0.9600.19230

**Comment by btrd** [comment]
@mch2608 Est-ce toujours d'actualité ? Si oui n'hésite pas à rouvrir le ticket
