### ISSUE TITLE
Passer un outil de test de conformance accessibilité sur la homepage et les pages publiques

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#696]

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
Outil : https://app.asqatasun.org (le nombre de pages est limité car produit gratuit. Possibilité de le faire en plusieurs fois pour avoir le résultat de l’ensemble des pages). 

Critères conformité : 
Dans chaque page web où elles sont présentes, la zone d’en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche respectent-elles au moins une de ces conditions :

o    La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature.

o    La zone possède un titre de hiérarchie dont le contenu permet de comprendre la nature du contenu de la zone.

o    La zone peut être masquée par le biais d’un bouton précédent directement la zone dans l’ordre du code source.

o    La zone peut être évitée par le biais d’un lien d’évitement précédent directement la zone dans l’ordre du code source.

o    La zone peut être atteinte par le biais d’un lien d’accès rapide visible à la prise de focus lors d’une tabulation.

Correspondances WCAG 2.1
    Critère(s) de succès WCAG 2.1 : 1.3.1 Info and Relationships (A), 2.4.1 Bypass Blocks (A), 4.1.2 Name, Role, Value (A).
    Technique(s) suffisante(s) et/ou échec(s) WCAG 2.1 : G115, ARIA4, ARIA11. 

Correspondances EN 301 549 V2.1.2 (2018-08)
    9.1.3.1 / 1.3.1 Info and Relationships (A),
    9.2.4.1 / 2.4.1 Bypass Blocks (A),
    9.4.1.2 / 4.1.2 Name, Role, Value (A). »

**Comment by Grainedepaillette** [comment]
****

**Comment by Grainedepaillette** [comment]
https://github.com/disic

**Comment by yannski** [comment]
En attente audit
