### ISSUE TITLE
Carte candidat : rôle GE/ES a accès à la carte candidat alors que non conforme à l'architecture de la confidentialité 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#703]
Test en prod et pré-prod

- Comportement constaté : rôle GE ou ES a accès à la carte candidat. Listing des actions réalisées : 
1. Clic sur l'onglet "candidature" de l'offre d'emploi
2. A partir du Trello, clic droit sur les icônes "messages" ou "notifications" de la carte candidat puis sélection via le menu des options "ouvrir un nouvel onglet/une nouvelle fenêtre" permet l'accès à la carte candidat en lecture seule. 
       Onglet "PROFIL" : les modifications apportées par le GE/ES (alimentation profil) ne sont pas enregistrées 
       Onglet "CANDIDATURE" + "COURRIELS" : visualisation du contenu mais aucune action possible par l'utilisateur
       Onglet "DOCUMENTS" : les modifications apportées validation/refus pièce, téléversement pièce) sont enregistrées 

- Comportement souhaité : rôle GE/ES ne doit pas avoir accès au détail de la carte candidat

**Comment by yannski** [comment]
@Grainedepaillette peux-tu me passer par un autre moyen que GitHub l'adresse email de quelqu'un qui a le rôle GE/ES ?

**Comment by yannski** [comment]
D'autre part, ce ticket semble en conflit avec le #714 non ?

**Comment by Grainedepaillette** [comment]
@yannski @btrd Je ferme le ticket car opérationnel en production : le GE et ES visualise les cartes candidats à partir d'une offre sans pour autant accéder au contenu --> conforme à l'architecture de la confid telle qu'elle avait été pensée.
