### ISSUE TITLE
Raccordement portail commun : URL avec code 404 si offre obsolète 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#704]
Voici le message communiqué par l'équipe projet "Devenez Civil de la Défense" : 

**Objet : CVD : URL + écrans offres obsolètes** 
Serait-il possible de retourner l’URL avec le code 404 au lieu de conserver l’URL de recherche ? Exemple pour la PEP :
- Lien de l’offre initiale : https://www.place-emploi-public.gouv.fr/offre-emploi/gestionnaire-des-habilitations-hf-reference-2019-209063
- Si l’offre n’est plus accessible : https://www.place-emploi-public.gouv.fr/404/

**Comment by yannski** [comment]
L'exemple fonctionne. D'autre part on renvoie bien le code 404 quand l'annonce n'est pas publiée. A rouvrir avec un autre exemple.
