### ISSUE TITLE
Back/Vivier : non accessibilité à l'onglet vivier 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#714]
Tests réalisés en pré-prod et en prod

Avec rôle RH, ES ou GE :
- Comportement constaté : Non visibilité sur le bouton « Vivier »
- Comportement souhaité : Apparition du bouton « Vivier » car ces rôles sont censés
avoir accès au vivier de candidatures relatif aux offres sur lesquelles ils ont été notifiés

![bug vivier ES](https://user-images.githubusercontent.com/58481185/98120482-496daf80-1eae-11eb-94fb-eff599cce797.PNG)

Avec compte employeur : 
- Comportement constaté : Visibilité sur le bouton "Vivier", lorsqu'on clique sur le bouton « Vivier », un message d’erreur apparaît
- Comportement souhaité : Ouverture de l’onglet « Vivier »

![vivier employeur](https://user-images.githubusercontent.com/58481185/98121336-7373a180-1eaf-11eb-8738-f44e3f26f846.PNG)

Avec compte BANT :
- Comportement constaté : Visibilité sur le bouton "Vivier", lorsqu'on clique sur le bouton "Vivier", ouverture de l'onglet mais les filtres n'apparaissent pas (seuls les boutons "rechercher" et "réinitialiser" sont présents) 
- Comportement souhaité : Apparition des filtres

![vivier bant](https://user-images.githubusercontent.com/58481185/98121696-ebda6280-1eaf-11eb-87da-01c7a6df8517.PNG)

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production et production (test effectué sur Mozilla)
