### ISSUE TITLE
[Talents] TTU- Impossibilité de candidater

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#715]
Plusieurs candidats et recruteurs nous font part de l'impossibilité de candidater sur le site Talents.ssi, malgré un compte actif.

![20201106_message_erreur_candidats](https://user-images.githubusercontent.com/74023020/98370781-64b9f580-203b-11eb-8fe4-9479dd6c5c1e.png)

**Comment by yannski** [comment]
Le problème survenait effectivement quand une personne est déjà identifiée avant d'arriver sur la page.

Fixed in https://github.com/betagouv/civilsdeladefense/commit/dfdc867c5ae0ed7d5998ce89f437c2936a180316
