### ISSUE TITLE
[Talents] TTU Problèmes sur la messagerie

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#718]
Plusieurs managers nous ont signalé des difficultés avec la messagerie de Talents.

J'ai vérifié avec une personne de mon équipe, et après plusieurs tests, voici ce que nous constatons :
- l'envoi depuis la plateforme d'un message simple au candidat fonctionne ;
- les réponses des candidats sur la plateforme ne fonctionnent plus : les messages ne sont pas intégrés sur Talents ;
- l'envoi de messages depuis la plateforme aux candidats avec ajout de pièce jointe ne fonctionne pas : pas de réception de mail par les candidats alors que sur Talents, le message semble envoyé.

Par ailleurs, l'absence de notification ou de pastille sur la fiche candidat est problématique. 
Les managers ne savent pas quel candidat leur écrit et comme nous avons beaucoup de candidatures (ce qui est très positif en revanche), le traitement des messages est rendu particulièrement complexe.

**Comment by yannski** [comment]
Il y a plusieurs tickets à ouvrir ici.

Pour les problèmes de traitement des emails entrant c'est un doublon de #708 .

Je vais fermer ce ticket.
