### ISSUE TITLE
[Talents] TTU suite ticket #717 - question vivier

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#725]
Suite au ticket #717, le filtre a été rétabli, mais  
    les cartes candidats ne peuvent toujours pas être ouvertes via l'onglet

Merci beaucoup

**Comment by yannski** [comment]
@jtledoux pouvez-vous me donner plus de détails ? Sur quelle page se situe le problème ? Quel profil n'arrive pas à ouvrir les cartes ?
