### ISSUE TITLE
[Talents] problèmes dans la gestion des fiches candidats

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#728]
Plusieurs recruteurs nous font remonter les problèmes suivants :
- le changement de statut n'est pas effectif: si passation du candidat en "refus", la fiche candidat ne change pas de colonne;
- la fiche candidat ne change pas de colonne de "nouveau" à "refusé" même en manuel;
- il n'y a plus de motif de refus qui apparaît lorsqu'on met le candidat en "refusé";
- lorsque lemotf apparaît, le choix du motif n'est pas pris en compte malgré la réactualisation de la page ;
 - l'actualisation de la fiche candidat remet automatiquement le statut du candidat en "nouveau" ;
- Lors de la rédaction de courriel, possibilité de l'objet du mail mais le template (le corps du mail) n'apparaît pas, la case reste vide ;
- les fiches candidats ne sont plus consultables dans la partie vivier.

**Comment by Grainedepaillette** [comment]
@jtledoux Ces problématiques sont-elles toujours d'actualité sur votre instance ? Car un certain nombre d'éléments ont été traités dans des tickets distincts.
