### ISSUE TITLE
[Talents] statistiques : correction sur les statistiques liées au motif de refus

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#732]
Exclure les candidatures en cours de traitement des statistiques sur le motif de refus (elles sont actuellement comptabilisées dans les statistiques de refus dans le motif inconnu alors que pas à l'état refusé)

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé (test effectué sur Mozilla)
