### ISSUE TITLE
[Talents] pastilles pour le bon traitement des candidatures et des échanges

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#735]
Rétablir les pastilles sur la fiche candidat, visibles depuis le trello de l'offre d'emploi ou le vivier, pour savoir qui a adressé un message et quelle est la candidature à traiter, en complément des pastilles présentes sur l'offre d'emploi et les onglets de la fiche candidat

**Comment by jtledoux** [comment]
Précisions
La pastille présente dans la fiche candidature est dupliquée sur la fiche candidat afin de savoir précisément quelle carte candidat doit être ouverte pour traitement.
Concrètement, la pastille est ainsi visible dans le trello de l'offre d'emploi, ainsi que dans le vivier sur la fiche candidat (à préciser ce qui est possible : sur la fiche candidat ou uniquement sur la fiche candidature ? - idéalement les deux).
La pastille permet de savoir qu'une action est requise et reste visible tant que la pastille présente dans la fiche candidat (mail ou pièces) n'a pas été désactivée.

**Comment by jtledoux** [comment]
Voir pièce jointe

**Comment by yannski** [comment]
Reste à faire : pastilles relatives aux nouveaux fichiers

**Comment by Grainedepaillette** [comment]
Opérationnel en pré-production : passage en production validé
