### ISSUE TITLE
[Talents] prise en compte du dernier jour du mois dans les statistiques

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#737]
Nous avons constaté qu'en cas de sélection d'une période incluant le dernier jour du mois dans la partie statistiques, celui-ci n'est pas pris en compte (exp. période du 1er au 31 octobre, le 31.10 n'est pas inclus dans les statistiques) alors qu'en sélectionnant une autre période le dernier jour sélectionné est pris en compte (exp. période du 1er octobre au 1er novembre, le 31.10 et le 01.11 sont inclus)

**Comment by btrd** [comment]
Le dernier jour du mois est bien pris en compte pour preuve les captures d'écrans suivantes. Par contre dans le graphique le dernier jour n'est pas forcément affiché, pour des raisons de lisibilité.

<img width="1053" alt="Capture d’écran 2021-07-01 à 19 10 40" src="https://user-images.githubusercontent.com/1385737/124163734-2a0c3e00-daa0-11eb-8f29-778f2d785e0f.png">
<img width="1037" alt="Capture d’écran 2021-07-01 à 19 10 51" src="https://user-images.githubusercontent.com/1385737/124163740-2b3d6b00-daa0-11eb-8bbe-8983e7b2a2d0.png">
<img width="1029" alt="Capture d’écran 2021-07-01 à 19 10 46" src="https://user-images.githubusercontent.com/1385737/124163741-2b3d6b00-daa0-11eb-90b2-baa7888bbbf7.png">
