### ISSUE TITLE
[Talents] Problème sur les liens des messages électroniques

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#739]
Nous avons constaté un problème dans les messages envoyés aux recruteurs au moment de la validation de leurs comptes. 

Le lien indiqué pour activer le compte est désormais déformé par SendInBlue (pour des raisons de traçage du nombre de clic je suppose).
Les liens envoyés aux recruteurs ont désormais cette forme : https://chcefgh.r.af.d.sendibt2.com/

Bien que cette URL pointe, in fine, sur le site internet talents.ssi.gouv.fr, cela créé une confusion en interne en laissant à penser qu’il s’agit d’une tentative de phishing. 

Afin d’éviter toute confusion en lien à la SSI, est-il possible d’afficher et transformer le lien en faisant pointer directement vers la plateforme en .gouv.fr ?

**Comment by btrd** [comment]
@jtledoux Est-ce toujours d'actualité ? Si oui n'hésite pas à rouvrir le ticket
