### ISSUE TITLE
Back / Vivier : accorder l'accès à l'ensemble des cartes candidats pour les rôles employeurs

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#742]
Comportement constaté : les employeurs ont seulement la visibilité sur les candidats relatifs à leur offre d'emploi ou celles sur lesquels ils ont été notifié. 

Comportement souhaité : au même rang que le BANT, les employeurs ont l'accès à l'ensemble des cartes candidats de l'outil dans leur vivier

**Comment by Grainedepaillette** [comment]
@btrd @yannski Opérationnel en pré-production : passage en production validé
