### ISSUE TITLE
Front / Offres : option "Télé-travail" n'apparaît pas dans les infos clés de l'offre

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#750]
Comportements constatés : En back, lorsqu'un employeur sélectionne "Oui" dans l'option "Télétravail possible ?", l'information n'apparaît pas dans les informations clés de l'offre d'emploi (en back et en front). 

<img width="1440" alt="Capture d’écran 2020-12-11 à 11 50 39" src="https://user-images.githubusercontent.com/58481185/101894900-1c947280-3ba7-11eb-912e-f5e8c63156fd.png">

<img width="1440" alt="Capture d’écran 2020-12-11 à 11 51 16" src="https://user-images.githubusercontent.com/58481185/101894963-32099c80-3ba7-11eb-9d84-a81cd3bdca90.png">

<img width="1440" alt="Capture d’écran 2020-12-11 à 11 51 35" src="https://user-images.githubusercontent.com/58481185/101895012-3df55e80-3ba7-11eb-97b2-d258d59932d7.png">

Comportements souhaités : visibilité sur l'option télétravail dans les informations clés de l'offre

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr966.osc-fr1.scalingo.io
