### ISSUE TITLE
Général : changement de l'URL actuel pour " contractuels.civils.defense.gouv.fr "

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#751]

**Comment by Grainedepaillette** [comment]
@yannski As -tu besoin d'informations complémentaires pour procéder au changement au delà de la nouvelle URL : contractuels.civils.defense.gouv.fr ?

**Comment by yannski** [comment]
@Grainedepaillette c'est configuré du côté de Scalingo. Maintenant il faut que le nom de domaine contractuels.civils.defense.gouv.fr  soit un enregistrement `CNAME` pointant vers `erecrutement-cvd-production.osc-secnum-fr1.scalingo.io.` (le point à la fin est important).

**Comment by Grainedepaillette** [comment]
@yannski Okay ce que je comprends c'est que le nom de domaine en .gouv.fr doit rediriger vers le nom de domaine "réel" : erecrutement-cvd-production.osc-secnum-fr1.scalingo.io.

J'ai plusieurs questions : 
A-t-on besoin de communiquer cette info à l'organisme créateur du .gouv.fr , le SIG, pour obtenir un quelconque accès, clé ? A l'équipe projet du portail commun ? 
Globalement est-ce que l'on doit mener une action à notre niveau ? 
Les anciennes offres seront forcément reroutées après le changement ? 

Merci.

**Comment by yannski** [comment]
Ce n'est pas une redirection. Tout le contenu sera immédiatement disponible sur l'autre url. Je mettrai, en plus, une redirection de l'ancienne url vers la nouvelle, pour ne pas perdre le référencement.

**Comment by Grainedepaillette** [comment]
Demande de création d'un enregistrement CNAME effectuée auprès des services le 22.12 - en cours

**Comment by yannski** [comment]
Toujours pas bon aujourd'hui https://dnschecker.org/#CNAME/contractuels.civils.defense.gouv.fr

**Comment by Grainedepaillette** [comment]
@yannski Création prévue pour le 2 ou 3 février. Est-ce qu'on pourra avoir l'URL visible sur CVD le jour de la création ? 

Il est prévu de tester les raccordements entre les 2 SI le 3 ou 4.02 en interne (services de COM) en prévision du 18.02 et ils voudraient voir les URL en .gouv.fr

**Comment by yannski** [comment]
Dès que le ndd est bien configuré on pourra rediriger vers la nouvelle URL.

**Comment by Grainedepaillette** [comment]
Bien pris, merci !

**Comment by Grainedepaillette** [comment]
@yannski Suite à la soumission de la Fiche SFR pour création de l'enregistrement CNAME, voici ce qui nous a été communiqué : 

![Capture d’écran 2021-02-02 à 11 34 12](https://user-images.githubusercontent.com/51794334/106588005-95320280-654a-11eb-9c8a-ff89534e00d1.png)

**Comment by Grainedepaillette** [comment]
@yannski Après vérification sur le site https://dnschecker.org/#CNAME/contractuels.civils.defense.gouv.fr

Un DNS situé à Lille apparaît (cf. écran). Si c'est le bon, est-il possible de rediriger aujourd'hui ou demain ? Merci. 
![Capture d’écran 2021-02-02 à 14 00 29](https://user-images.githubusercontent.com/51794334/106603761-04195680-655f-11eb-87c1-1fce0b7bd31a.png)

**Comment by yannski** [comment]
Redirection effectuée !
