### ISSUE TITLE
Back/Offres : un acteur notifié ne peut être supprimé après enregistrement/publication offre 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#769]
- Test en production (cf. remontée utilisateur) 

- Rôle concerné : BANT ; Employeur 

- Comportement constaté : lorsqu'un utilisateur notifie un acteur (quel que soit le rôle) et enregistre en format brouillon ou publie l'offre et qu'il souhaite ensuite modifier l'offre en supprimant des acteurs notifiés (clic croix rouge du compte notifié) alors la page se charge mais le compte n'est pas supprimé. 

Ce problème n'apparaît pas lors de la rédaction de l'offre : après avoir notifié des acteurs, la suppression fonctionne dès lors que l'utilisateur les supprime AVANT d'enregistrer en brouillon ou publier l'offre. Le pb concerne donc la modification post enregistrement de l'offre. 

- Comportement souhaité : pouvoir supprimer des comptes notifiés (quel que soit le rôle) après enregistrement de l'offre en format brouillon ou publication.

**Comment by btrd** [comment]
C'est corrigé et en staging

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel
