### ISSUE TITLE
Front/ Lien "Inscription" + "postuler" : afficher message confirmation création compte

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#783]
Le message de confirmation de création de compte et d'explication de la procédure de vérification d'email devrait apparaitre sur une page dédiée.

Voir l'exemple Trackdechets :

![Screenshot_2021-01-29 Trackdéchets La tracabilité des déchets en toute sécurité](https://user-images.githubusercontent.com/11287/106258389-0bb6c380-621e-11eb-9838-ac47e9cbd553.png)

**Comment by Grainedepaillette** [comment]
Le message actuel : 

![Capture d’écran 2021-05-12 à 17.09.40.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/21736c2a-c15d-404c-8d04-a39fe0317327)

**Comment by btrd** [comment]
Spécification attendue : message à afficher

**Comment by Grainedepaillette** [comment]
@btrd C'est à nous de te communiquer le contenu du message ? Merci.

**Comment by btrd** [comment]
@Grainedepaillette Oui, si vous voulez changer le message il me faut le contenu du nouveau message à afficher

**Comment by Grainedepaillette** [comment]
Pourrais-tu également mettre à jour ce message lorsqu'un candidat postule à une offre ? Merci.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr997.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel. Seul élément : la mention "contactez notre équipe" ne comprends pas le lien URL de la rubrique "nous contacter". Est-ce possible de l'ajouter/paramétrer ? 

Auquel cas, ajouter en fin de message "via la rubrique "Nous contacter" !" donc la dernière phrase serait : "En cas de non réception ou pour toute autre question, contactez notre équipe via la rubrique "Nous contacter !"
