### ISSUE TITLE
Page d'accueil/ Offres à la une : pouvoir paramétrer les offres de la rubrique en back 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#794]
#752 

Afin de traiter le ticket, des retouches design peuvent être apportées : 3 options : 
- conserver le fond gris et la flèche car recommandations du Design System de l’Etat. 
- reprendre le design initial 
- mixer le design initial et les recommandations

**Comment by mch2608** [comment]
@btrd Aujourd'hui le contenu est fixe, voici la "règle" associée :

- Doit être paramétrable par le Responsable fonctionnel (rôle BANT) en back office. L’idée est de laisser la main au RF sur le choix des offres à mettre en avant.

**Comment by btrd** [comment]
@mch2608 @Grainedepaillette  Est-ce que ce serait ok comme design ? Disponible uniquement pour les admins

![Capture d’écran 2021-04-29 à 16 14 44](https://user-images.githubusercontent.com/1385737/116565289-03961f00-a906-11eb-8393-55e476f05253.png)
![Capture d’écran 2021-04-29 à 16 14 23](https://user-images.githubusercontent.com/1385737/116565301-05f87900-a906-11eb-874c-442e37a12005.png)

Dans la partie Paramètres j'ai pas forcément d'idée de comment le faire notamment la partie recherche et sélection de l'offre, si jamais vous avez des idées je suis preneur.

**Comment by mch2608** [comment]
Ok pour ce design. Je pense qu'on peut seulement changer l'appellation par "Offre à la une" et "Mettre en offre à la une". Offre favorite peut laisser croire qu'il s'agit d'une liste d'offre sous le même principe que la liste de candidat. 
@Grainedepaillette es-tu ok ?

**Comment by Grainedepaillette** [comment]
@mch2608 @btrd Le design convient. En intitulé au niveau du bouton plutôt mettre "afficher à la une" et au niveau de l'onglet reprendre l'intitulé en front "Offres à la Une". 
J'ai une question quand tu cliques sur l'onglet : tu ne pourras que supprimer les offres précédemment sélectionnées par les admins ? Où tu pourras également modifier la liste des offres à la une à partir de l'onglet ? Merci.

**Comment by btrd** [comment]
> Où tu pourras également modifier la liste des offres à la une à partir de l'onglet ?

Non car je ne vois pas quoi faire comme design pour chercher/sélectionner une offre. Si tu as des idées je suis preneur.

**Comment by Grainedepaillette** [comment]
@btrd Est-ce qu'on ne pourrait pas reprendre le design qui permet d'envoyer une offre d'emploi (ticket #528) (cf.écran 1) ? Ou même le système que propose Github pour mentionner des tickets ? (cf. écran 2)
Un menu déroulant avec la liste des offres relatives au périmètre de chaque acteur, à partir duquel on pourrait également saisir la référence de l'offre afin de faire remonter l'offre souhaitée et la sélectionnée. 

### **Ecran 1** 
https://user-images.githubusercontent.com/51794334/116064295-2a462280-a686-11eb-9c55-72b03ea3f03a.png

### **Ecran 2** 
![Capture d’écran 2021-05-04 à 10 04 36](https://user-images.githubusercontent.com/51794334/116975620-394d5600-acc0-11eb-9e6d-a9600ead4909.png)

**Comment by btrd** [comment]
Pour l'écran 1 je vois pas ce que doit faire le dropdown ? Il faut de l'autocomplétion ?

On doit pouvoir utiliser le même compostant, mais comme il n'est pas encore fait/spécifié/designé je vais mettre ce ticket en attente.

**Comment by Grainedepaillette** [comment]
@btrd Cela veut dire que le ticket 528 doit être développé avant de traiter celui ci ? Ou que tu as besoin que ce ticket soit spécifier ? et qu'un design de la page soit créé spécifiquement pour cette fonctionnalité ? Merci !

**Comment by btrd** [comment]
Comme le #528 me semble plus important que ce ticket, oui je préfère m'occuper du #528 est utilisé ce qui a été fait pour ce ticket.

**Comment by Grainedepaillette** [comment]
@btrd Ok, bien pris

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr948.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd testé, c'est opérationnel. 
Seul point : retirer la majuscule à "Une" en back. Merci !
