### ISSUE TITLE
Page d'accueil/ 2ème image : ajouter l'image "témoignage" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#795]
#752 

Ajouter l'image témoignage + titre + bouton (cf. design).

**Comment by btrd** [comment]
@Grainedepaillette Le bouton il envoi vers une nouvelle page dans l'app ou sur un lien externe ?

**Comment by Grainedepaillette** [comment]
@jean le bouton renvoi vers un lien externe. 
Exemple : https://whttps://www.civils.defense.gouv.fr/metier/13

**Comment by btrd** [comment]
@Grainedepaillette Est-ce que l'image peut-être différente de l'image du début ? C'est un carousel ou un contenu fixe ?

**Comment by Grainedepaillette** [comment]
@btrd Cela correspond à un contenu fixe, voici les "règles" associées : 

- Doit être paramétrable par le Responsable fonctionnel (rôle BANT) en back office (image, intitulé, texte du bouton, URL). L’idée est de laisser la main au RF pour la mise en avant d’une information, dans le cas de CVD cela correspondra aux métiers civils. 

- Une règle doit également permettre à ce que lorsqu'il n’y a pas de contenu associé au module, celui-ci n’apparaisse pas sur la page d'accueil (cf. ANSSI qui pour l'instant n'a pas besoin de l'option).

**Comment by btrd** [comment]
@Grainedepaillette Je te laisse valider le fonctionnement ici : https://erecrutement-cvd-staging-pr834.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Afin de vérifier, serait-il possible de me créer un compte admin BANT ? Car je n'ai pas d'accès back pour cet environnement. Merci !

**Comment by btrd** [comment]
Je viens de t'inviter
