### ISSUE TITLE
Back/ Rédaction offre : lorsqu'un CMG sur une offre, il est affiché indisponible pour les autres offres sur lesquelles un recruteur souhaiterait le notifier. 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#804]
#531 

- Testé en pré-prodution 
- Testé sur Mozilla (PC DELL) et Chrome (PC Macbook)
- Testé avec rôle BANT (RF) et rôle employeur 

- Comportement constaté : Lorsqu'un recruteur souhaite notifier un courriel CMG alors lorsque le CMG est notifié pour la 1ère fois cela fonctionne mais si ce même recruteur ou un autre recruteur souhaite le notifier à nouveau sur une autre offre, alors le courriel CMG est indiqué comme indisponible par le système. 

- Comportement souhaité : un recruteur doit pouvoir notifié sur plusieurs offres le même courriel CMG et plusieurs/ différents recruteurs doivent pouvoir notifier le même CMG sans qu'il ne soit affiché comme indisponible. 

Démonstration en vidéo : 

https://user-images.githubusercontent.com/51794334/107535861-6f979f80-6bc1-11eb-829d-8a1c25853974.mov

**Comment by Grainedepaillette** [comment]
@yannski Test effectué en pré-prod dans le cas d'une modification d'offre existante et dans le cas d'une création d'offre mais problème persistant

**Comment by btrd** [comment]
@Grainedepaillette J'ai redéployé la pré-prod et c'est ok

**Comment by Grainedepaillette** [comment]
@btrd Après vérification, ce n'est pas opérationnel en staging de mon côté. Je réouvre le ticket.

**Comment by btrd** [comment]
C'est à nouveau corrigé, le problème viens des adresses des CMG en staging qui comporte un espace à la fin, j'ai ajouté une validation sur le format des emails des CMG pour ne plus que ça arrive.

**Comment by Grainedepaillette** [comment]
@btrd Après test, c'est opérationnel en staging

**Comment by Grainedepaillette** [comment]
@btrd Après test, c'est opérationnel en staging
