### ISSUE TITLE
Onglet Statistiques : les données relatives au motif de refus ne sont pas visibles

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#805]
- Testé en pré-prodution 
- Testé sur Mozilla et Chrome 
- Testé avec rôle BANT (RF) et rôle employeur 

- Comportement constaté : Les statistiques relatives au motif de refus ne sont pas visibles via l'onglet "Statistiques" principal
alors même que des motifs de refus sont renseignées dans les cartes candidats présentes dans le vivier 
![Capture d’écran 2021-02-10 à 17 03 21](https://user-images.githubusercontent.com/51794334/107536302-e9c82400-6bc1-11eb-8901-fe3f8c703eed.png)

NB : Lorsque l'on souhaite accéder aux statistiques des candidatures relatives à une offre via le chemin suivant Offres < Une offre < onglet "Statistiques" ALORS les données relatives au motifs de refus sont visibles. 

- Comportement souhaité : visualiser les statistiques du motifs de refus à partir de l'onglet "statistiques" principal.

**Comment by btrd** [comment]
![Capture d’écran 2021-06-14 à 16 40 44](https://user-images.githubusercontent.com/1385737/121910589-46357e80-cd2f-11eb-90b3-18f6c82aa6bf.png)

J'ai bien des refus, j'ai ajouté un message lorsqu'on a aucun refus dans les candidatures pris en compte.

**Comment by Grainedepaillette** [comment]
@btrd Super merci c'est + parlant comme ça !
