### ISSUE TITLE
Front/Espace candidat : le menu n'est pas visible 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#815]
- Test pré-production 
- Comportement constaté : lorsque le candidat est connecté à son espace candidat il ne visualise pas le menu (onglet "accueil" et "offres"). Il doit cliquer sur le header (logo + titres) OU faire un retour afin d'accéder à la page d'accueil. 

![Capture d’écran 2021-02-12 à 18 31 07](https://user-images.githubusercontent.com/51794334/107801556-83c5d300-6d60-11eb-8139-de0ea070e96e.png)

- Comportement souhaité : visualiser le menu depuis l'espace candidat.

**Comment by yannski** [comment]
Mon idée initiale était de ne pas laisser d'opportunités au candidat connecté dans son espace candidat de se "tromper", d'en sortir et de se perdre. Ca serait d'autant plus vrai avec les éléments de navigation qui pointent vers d'autres sites. Mais je peux tout à faire remettre la sous-nav si vous le souhaitez.

**Comment by Grainedepaillette** [comment]
@yannski C'est validé, je ferme le ticket
