### ISSUE TITLE
Carte candidat/ onglet "Documents" : ne pas afficher les pastilles lorsque le CV et la LM sont téléversées

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#839]
CF. #735 

- Comportement constaté : lorsqu'un candidat postule à une offre, en back office, une pastille apparaît au niveau de la carte candidat/onglet "documents" afin de signaler le téléversement du CV et de la LM. Or ces documents étant obligatoires à l'étude du dossier, il n'est pas nécessaire que le recruteur soit informé de cette action. Les pastilles ne sont pertinentes que lorsque le candidat est retenu et téléverse les AUTRES documents constitutifs du dossier de recrutement. 

![document CV + LM](https://user-images.githubusercontent.com/51794334/108730677-0c482e80-752c-11eb-8fce-a11a0c3000ac.png)

- Comportement souhaité : Ne pas afficher les pastilles lorsque le CV et la LM seulement sont téléversées par le candidat lorsqu'il postule à une offre.

**Comment by btrd** [comment]
Ne pas mettre de pastille à la création de la candidature.

**Comment by Grainedepaillette** [comment]
@btrd Opérationnel en review app

**Comment by Grainedepaillette** [comment]
@btrd Non opérationnel en review app : lorsqu'un candidat postule, une pastille au niveau de la carte candidat/ onglet document apparaît pour le CV et la LM

**Comment by btrd** [comment]
<img width="304" alt="Capture d’écran 2021-03-26 à 12 42 09" src="https://user-images.githubusercontent.com/1385737/112626591-b3243100-8e30-11eb-8a86-f28affa966aa.png">

J'avais pas décoché la case dans le backoffice. C'est chose faite !

**Comment by Grainedepaillette** [comment]
Ah c'était donc ça ! Du coup je comprends mieux l'apparition de cette nouvelle case quand j'ai fait la démo à la DGA vendredi !

**Comment by mch2608** [comment]
@btrd
 Il n'y a plus aucune pastille lorsqu'un candidat dépose une candidature. 
- Pas de pastille sur l'offre à laquelle le candidat a postulé
- Pas de pastille sur la carte candidat sur le trello associé à l'offre à laquelle le candidat a postulé

**Comment by btrd** [comment]
C'est pas ce qui a été demandé dans ce ticket ? Retirer les pastilles quand la personne postule
