### ISSUE TITLE
Modification des anciennes offres

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#841]
Suite aux modifications faites sur les offres pour encadrer le format, il n'est plus possible de passer une ancienne offre en brouillon sans la modifier, s'agissant notamment du nombre de caractère : appliquer le format aux nouvelles offres sans bloquer la mise en pause ou l'archivage des anciennes.

**Comment by btrd** [comment]
La limitation du nombre de caractères a été enlevé, mais il faut que l'on déploie le nouveau design pour que ce soit effectif.
