### ISSUE TITLE
Message d'erreur et impossibilité de modifier une offre

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#842]
Je ne parviens pas à accéder à l'offre https://talents.ssi.gouv.fr/admin/offresdemploi/chef-fe-adjoint-e-de-la-division-scientifique-et-technique/edit en modification.
Un message d'erreur s'affiche : We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Habituellement le changement de navigateur suffit, mais pas pour cette offre.
L'offre est actuellement en pause et ne peut être ni modifiée ni republiée.

**Comment by btrd** [comment]
C'est normalement corrigé, ne pas hésiter à rouvrir l'issue si ce n'est pas le cas
