### ISSUE TITLE
Vivier / Carte candidat : afficher le dernier CV télé-versé par le candidat 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#845]
### **Comportement constaté :** 
Aujourd'hui, lorsqu'un employeur clique sur une carte candidat, il visualise la liste des candidatures associées au profil mais n'a pas directement accès au CV du candidat. 

![Capture d’écran 2021-04-06 à 09 12 13](https://user-images.githubusercontent.com/51794334/113672579-41fa3e80-96b8-11eb-925d-37cd479d77d1.png)

### **Chemin actuel pour accéder au CV à partir d'une carte candidat :** 
Clic sur une carte candidat à partir du vivier < Clic sur une des candidatures  < Clic sur onglet "candidature" de la carte < Accès au CV et la LM. 

![Capture d’écran 2021-04-06 à 09 25 47](https://user-images.githubusercontent.com/51794334/113674119-1bd59e00-96ba-11eb-9ac7-6ed06231bebc.png)

### **Comportement souhaité :** 

Afin que l'employeur puisse apprécier la qualité d'un profil candidat (dès qu'il clique sur la carte), ajouter un encart "CV" ou serait affiché le dernier CV télé-versé par le candidat pour postuler. L'accès au CV sera rapide et simplifié pour l'employeur. lE CV doit être positionné avant l'encart "liste des candidatures". 

### **Chemin souhaité pour accéder au CV à partir d'une carte candidat :**  
Clic sur une carte candidat à partir du vivier < Affichage du CV + liste des candidatures

**Comment by Grainedepaillette** [comment]
@btrd PTI, j'ai apporté des précisions au commentaire précédent. Finalité du ticket reste inchangée.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr872.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@brt Après test, c'est opérationnel mais 2 sujets : 
1. La LM est également affichée
2. L'affichage du CV (+ LM) n'est effectif que pour les nouvelles candidatures. Lorsque l'on clique sur des précédentes candidatures le changement n'est pas pris en compte. Est-ce que ce sera également le cas en prod ?

**Comment by btrd** [comment]
1. Mauvaise lecture du ticket de ma part, je corrige
2. Ça ne devrait pas être le cas en staging, je vais voir pourquoi

**Comment by btrd** [comment]
1. C'est corrigé
2. J'ai déjà corrigé le soucis pour la fonctionnalité où le candidat reprends un CV existant, si tu me dis ok je met tous en staging

**Comment by Grainedepaillette** [comment]
@btrd C'est OK !
1. C'est opérationnel 
2. On vérifiera donc en staging

**Comment by Grainedepaillette** [comment]
Résultat sur la Review app
![Capture d’écran 2021-04-08 à 12 25 33](https://user-images.githubusercontent.com/51794334/114162682-9eb06000-9929-11eb-805f-b84748c471ab.png)

**Comment by Grainedepaillette** [comment]
@btrd C'est passé en staging ? Merci

**Comment by btrd** [comment]
C'est passé en staging oui !

**Comment by Grainedepaillette** [comment]
@btrd J'ai testé avec une nouvelle candidature mais le CV n'apparaît pas (cf. capture d'écran)

![Capture d’écran 2021-04-09 à 18 57 08](https://user-images.githubusercontent.com/51794334/114215109-7d6d6500-9965-11eb-958a-41d40e3b9cec.png)

**Comment by Grainedepaillette** [comment]
@btrd Je me permets de te relancer sur ce ticket. Il a été fermé mais après 2ème test ce jour, le CV n'apparaît toujours pas au niveau de la carte candidat (cf. écran). Merci. 
![Capture d’écran 2021-04-21 à 12 34 02](https://user-images.githubusercontent.com/51794334/115540055-f93cab00-a29d-11eb-8322-e95a07fd8f7b.png)

**Comment by btrd** [comment]
En fait c'était pas disponible en staging, c'est maintenant le cas.
