### ISSUE TITLE
Vivier / Carte candidat : pouvoir visualiser un aperçu du CV lorsque recruteur glisse la souris sur une carte candidat

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#846]

**Comment by jrmlnzz** [comment]
@sebastiencarceles pareil, je te demande ton avis. Aucune idée du temps que ça pourrait te demander !

**Comment by sebastiencarceles** [comment]
Ça semble gérable en temps raisonnable, mais il y a quand même un peu d'efforts à fournir :
- il faudrait pré-générer une image du CV à partir du PDF
- il faudrait un système de tooltips qui permette d'afficher les images

**Comment by jrmlnzz** [comment]
Hum, je vois. Je lui mets la priorité la plus basse alors, on voit comment on avance sur les autres points.
