### ISSUE TITLE
Limitation du nombre de caractères pour la description de l'offre

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#847]
La limitation du nombre de caractères pour la description de l'offre comprend aussi le texte inséré dans "profil recherché" et "process de recrutement". 
Serait-il possible de borner cette limitation à la seule description de l'offre ?

**Comment by Grainedepaillette** [comment]
Travail de limitation du nombres de caractères en cours pour chaque champ de saisie. cf. CR point du 25.02. 
Un ticket spécifique sera ouvert pour fixer la limitation pour chaque champ texte.

**Comment by btrd** [comment]
Pour la limitation du nombre de caractères on peut utiliser ce ticket https://github.com/betagouv/civilsdeladefense/issues/441
