### ISSUE TITLE
Back/Formulaire rédaction offre : ajoute un champ "Descriptif de l'organisation" 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#849]
Format : champ texte

**Comment by Grainedepaillette** [comment]
@btrd Opérationnel en review app

**Comment by btrd** [comment]
C'est lié à l'issue https://github.com/betagouv/civilsdeladefense/issues/441

**Comment by Grainedepaillette** [comment]
@btrd Bien pris en compte

**Comment by Grainedepaillette** [comment]
@btrd A déployer au prochain sprint (le temps que la campagne de COM auprès des utilisateurs soit close). Ticket déplacé dans le prochain SPRINT.

**Comment by Grainedepaillette** [comment]
@btrd pourrais-tu m'indiquer dans quel environnement se trouve ce ticket ? je n'ai aucune trace et il n'est pas dispo en staging. Merci !

**Comment by btrd** [comment]
Celui là :) https://erecrutement-cvd-staging-pr870.osc-fr1.scalingo.io

**Comment by btrd** [comment]
@Grainedepaillette Ce sera forcément vide tant que personne n'a remplis le champs oui

**Comment by Grainedepaillette** [comment]
C'est noté, merci. 
D'un point de vue métier, nous indiquerons aux employeurs de rapatrier cette partie du texte dans le bon champ du coup

**Comment by Grainedepaillette** [comment]
@btrd Campagne finalisée, prêt à être déployé. Je ferme le ticket.

**Comment by btrd** [comment]
Comme c'est une nouvelle demande j'ai créé un ticket spécifique https://github.com/betagouv/civilsdeladefense/issues/1131
