### ISSUE TITLE
Général/expiration session utilisateur : sauvegarde des actions réalisées et données saisies

### ISSUE THREAD

**Issue by btrd** [betagouv/civilsdeladefense#850]
- Comportement constaté : aujourd'hui, session utilisateur expire au bout d'1h. Lorsqu'elle expire et que l'utilisateur saisit à nouveau ses identifiants, affichage de la page sur laquelle il était avant expiration #363

- Comportement souhaité : 
Sauvegarde automatique des actions réalisées et données saisies

Lié https://github.com/betagouv/civilsdeladefense/issues/683

**Comment by btrd** [comment]
https://geoffreycrofte.github.io/form-saver/

**Comment by jrmlnzz** [comment]
@sebastiencarceles qu'est-ce que tu penses de celui-ci en terme de temps de travail/ valeur apportée ?

**Comment by sebastiencarceles** [comment]
Est-il possible de préciser un peu le cas d'usage ? Voici ce que je comprends : 

> En tant qu'admin, si ma session expire alors que j'étais en train de rédiger une offre, alors je voudrais reprendre ma rédaction au même point après m'être de nouveau authentifié

Dit autrement, on sauvegarderait le contenu du formulaire de création d'offre, tant qu'il n'est pas soumis. En conséquence, même si la personne ferme le navigateur, puis revient au même endroit, sa saisie serait encore présente.

Est-ce que je comprends bien ?

Est-ce qu'il y a d'autres cas d'usage ? D'autres endroits dans l'application où on voudrait faire de même ?

**Comment by jrmlnzz** [comment]
Ouaip, c'est bien ça ! J'ai pas relevé d'autres cas d'usages, mais est-ce que tu penses que ce serait possible d'avoir le même comportement côté candidat, lorsqu'il postule pour une offre ? Enfin, je veux dire dans quelle mesure ça peut te rallonger le travail ? Parce que si c'est trop complexe, on le met uniquement pour la rédaction d'offre dans le bo.

**Comment by sebastiencarceles** [comment]
À mon avis 80 - 90 % de l'effort porte sur la mécanique de sauvegarde d'un formulaire (Jean suggérait la lib `form-saver`, ça semble être une bonne option). Une fois qu'on a ça en place, le mettre sur un ou plusieurs formulaire ne change pas grand chose. Donc si tu vois plusieurs endroits dans l'application où ça serait utile, je t'invite à en faire la liste.
