### ISSUE TITLE
Choisir plusieurs valeurs pour chaque filtres

### ISSUE THREAD

**Issue by btrd** [betagouv/civilsdeladefense#851]

**Comment by btrd** [comment]
https://github.com/select2/select2

**Comment by btrd** [comment]
![Capture d’écran 2021-03-18 à 17 17 49](https://user-images.githubusercontent.com/1385737/111659906-dede6000-880d-11eb-998e-25c2da65e5e5.png)

Reprendre l'ordre là (avec région en 3).

**Comment by btrd** [comment]
C'est fait

**Comment by Grainedepaillette** [comment]
@btrd Après test, voici ce que j'ai constaté : 

- Lorsque l'on sélectionne les filtres multi-critères : les résultats de la sélection s'affiche automatiquement (sans cliquer sur le bouton "Rechercher" 
- Lorsqu'on saisie dans un mot-clé dans la barre de recherche OU on sélectionne des dates (début contrat + publication) : les résultats ne s'affichent pas automatiquement (il faut cliquer sur le bouton "Rechercher" pour que le mot-clé et les soient pris en compte dans les résultats de la recherche)

Conséquence : cela peut déstabiliser l'usager. Il faudrait que l'affichage des résultats soit conditionné par le clic sur le bouton "rechercher"

**Comment by btrd** [comment]
Comportement corrigé.

**Comment by Grainedepaillette** [comment]
@btrd Après test c'est opérationnel !
