### ISSUE TITLE
Pouvoir gérer la FAQ dans le backoffice

### ISSUE THREAD

**Issue by btrd** [betagouv/civilsdeladefense#858]

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr968.osc-fr1.scalingo.io/

**Comment by mch2608** [comment]
Opérationnel. Est-ce que c'est possible de changer les intitulés pour que ce soit plus clair pour l'admin ?  
- "Nom" --> "Question" 
- "Value" --> "Réponse"

**Comment by Grainedepaillette** [comment]
@mch2608 @btrd C'est opérationnel (y compris changement d'intitulés)
