### ISSUE TITLE
Simplifier la de création de compte pour les candidats

### ISSUE THREAD

**Issue by seiteta** [betagouv/civilsdeladefense#86]
### Comportement actuel
En tant que candidat :
1/ Je clique sur "je valide ma candidature"
<img width="645" alt="capture d ecran 2018-09-27 a 16 39 21" src="https://user-images.githubusercontent.com/5756228/46153875-471edd00-c274-11e8-97dd-64c650381579.png">

2/ Je me retrouve sur la page d'accueil avec le warning "Vous devez vous connectez ou vous enregistrez pour continuer" et je clique sur "Accéder à mon espace candidat"
<img width="339" alt="capture d ecran 2018-09-27 a 16 40 31" src="https://user-images.githubusercontent.com/5756228/46154034-a1b83900-c274-11e8-8029-4bdc712c097d.png">

3/ J'ai un nouveau warning "Vous devez confirmer votre compte par courriel"
<img width="331" alt="capture d ecran 2018-09-27 a 16 41 04" src="https://user-images.githubusercontent.com/5756228/46154187-e47a1100-c274-11e8-835f-ba3e34746485.png">

4/ Je me rends sur ma boîte pour confirmer mon courriel

### Comportement attendu
En tant que candidat :
1/ Je clique sur "je valide ma candidature"
<img width="645" alt="capture d ecran 2018-09-27 a 16 39 21" src="https://user-images.githubusercontent.com/5756228/46153875-471edd00-c274-11e8-97dd-64c650381579.png">

2/ J'ai un message qui me dit "Votre demande est prise en compte. Veuillez confirmer votre accès à l'aide du lien sur votre boîte courriel"

**Comment by yannski** [comment]
@seiteta je te laisse faire un test ici pour valider l'UX : https://civilsdeladefense-pr93.scalingo.io/offresdemploi/ingenieur-expert-en-systemes-d-information-reseau-et-active-directory-chef-de-section/apply

**Comment by seiteta** [comment]
C'est parfait 👍

Tu fermes l'issue avec une PR ?
