### ISSUE TITLE
Documentation Installation

### ISSUE THREAD

**Issue by odurgeau** [betagouv/civilsdeladefense#861]
Bonjour,

J'ai remarqué une petite différence dans la documentation pour créer l'organisation, en reprenant les propriétés obligatoires :

```
hsh = {
  service_name: 'Civils de la Défense',
  brand_name: 'le Ministère des Armées',
  subdomain: 'XXX',
  domain: 'XXX.YYY.ZZZ',
  prefix_article: 'mna'
}
organization = Organization.create!(hsh)
```

Et pour que les notifications fonctionnent, j'ai du rajouter une variable d'environnement `DEFAULT_FROM`

```
DEFAULT_FROM=username@host
```

**Comment by sisitototest** [comment]
Bonjour

Après modification du DEFAULT_FROM le résultat est toujours le même

![image](https://user-images.githubusercontent.com/78742013/111274102-e1d22880-8634-11eb-9c6c-f23d649cb39c.png)

Cette erreur intervient depuis l'ajout d'un smtp_url valide

SMTP_URL=smtp://prenomnom%40gmail.com:CN6SjsB321HWDkEV@smtp-relay.sendinblue.com:587

Pouvez vous jeter un oeil directement sur la plateforme?

Merci beaucoup pour votre aide

**Comment by btrd** [comment]
@odurgeau Je m'étais noté de faire la correction, avoir l'issue c'est une bonne chose aussi. Merci !
