### ISSUE TITLE
Back / Rédaction offre : pouvoir déselectionner un acteur notifié sans vider l'ensemble des champs du formulaire

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#862]
Comportement constaté : lorsqu'un employeur remplit l'ensemble des champs du formulaire de rédaction d'offre et désélectionne un acteur notifié avec la petite croix rouge, la page s'actualise et l'ensemble des autres champs remplis se vident. L'employeur perd toutes les autres saisies. 

Comportement souhaité : lorsqu'un employeur souhaite retirer un acteur notifié avant la publication de son offre, l'ensemble des données saisies dans les autres champs doivent rester.

**Comment by btrd** [comment]
C'est corrigé avec https://github.com/betagouv/civilsdeladefense/issues/769

**Comment by mch2608** [comment]
Après vérification, le problème toujours existant. 

https://user-images.githubusercontent.com/58481185/116706840-59ce9500-a9ce-11eb-9aeb-dbdf388eebdc.mov

**Comment by btrd** [comment]
Désolé j'avais mal compris le ticket, je le rouvre.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr974.osc-fr1.scalingo.io/
