### ISSUE TITLE
Front/formulaire candidature : non soumission du formulaire de candidature 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#864]
Constaté en production 

### **Comportement constaté :** 
Lorsqu'un candidat complète le formulaire de candidature et clique sur le bouton "Je postule" la candidature n'est pas envoyée. Un message d'erreur apparaît "veuillez corriger les champs ci - dessosu" ALORS que les champs sont corrects et soulignés en vert. (cf. vidéo) 

https://user-images.githubusercontent.com/51794334/111618733-079e2f80-87e5-11eb-84b2-30f1939ce450.mov

### **Comportement souhaité :** 
Pouvoir soumettre la candidature en cliquant sur le bouton "je postule" lorsque le formulaire est complet.

**Comment by btrd** [comment]
C'est corrigé !

**Comment by Grainedepaillette** [comment]
@btrd J'ai testé en staging mais cela ne fonctionne pas : lorsque je complète le formulaire et clique, un message d'erreur apparaît (cf. capture d'écran)
![soumissionstaging](https://user-images.githubusercontent.com/51794334/111645384-f105d180-8800-11eb-9c65-2f12fc46cf26.png)

**Comment by Grainedepaillette** [comment]
@btrd Opérationnel en staging : testé à 2 reprises sur 2 offres distinctes et 2 courriels candidats (création de compte).
