### ISSUE TITLE
Back / Page confirmation compte : Non accès à la page du formulaire de confirmation de compte

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#867]
Comportement constaté en pré-prod : lorsque l'utilisateur reçoit son mail de confirmation de compte après invitation par le BANT ou une première notification sur une offre d'emploi, il clique sur le bouton "Je confirme mon courriel" : une page s'ouvre avec un message d'erreur 

![image](https://user-images.githubusercontent.com/58481185/112277236-d5c41780-8c81-11eb-8561-0f50c7431081.png)

Comportement souhaité : lorsqu'un utilisateur est invité à partir d'un mail à confirmer son compte, il atterrit sur le formulaire de confirmation de compte.

**Comment by mch2608** [comment]
- Comportement constaté sur le staging CVD 
- Impossibilité de tester en production CVD parce qu'il est demandé une adresse intradef 
- Accès au formulaire de confirmation opérationnelle sur le staging DGA

**Comment by btrd** [comment]
@mch2608 C'est corrigé en staging, si tu me valides je déploie en production

**Comment by mch2608** [comment]
@btrd C'est bien opérationnel en staging ! merci

**Comment by mch2608** [comment]
@btrd Le problème se re-manifeste en staging. Peux-tu regarder ?

**Comment by mch2608** [comment]
16H35 : problème résolu

**Comment by mch2608** [comment]
@
