### ISSUE TITLE
Problèmes liés à l'envoi et la réception de mails

### ISSUE THREAD

**Issue by jtledoux** [betagouv/civilsdeladefense#868]
Certains mails adressés via la plateforme ne parviennent pas aux candidats. De la même manière des mails adressés par les candidats ne nous parviennent pas, sans que nous puissions avoir une notification d'erreur.
Ce problème a été signalé à plusieurs reprises et semble se reproduire malgré les interventions.

**Comment by Grainedepaillette** [comment]
@btrd Suite à la remontée ANSSI, j'ai positionné le ticket 1ère position du sprint pour traitement car bloquant pour ANSSI.

**Comment by btrd** [comment]
On récupère les 100 premiers emails de la boite de réception toutes les 5min, lors de la prochaine mise en production je vais retirer la limite de 100 pour récupérer tous les emails de la boite de réception. Je pense que jusque maintenant la limite des 100 emails était assez grande pour tous les traiter et ce n'est plus le cas maintenant.

Le script en l'état peut poser problème dans le cas où l'on reçoit un trop grand nombre d'emails, je vais surveiller le fonctionnement du script dans les jours suivant la mise en production pour être sûr que ça fonctionne comme prévu et sinon il faudra refaire le script pour le rendre plus robuste au plus grand nombre de messages.

**Comment by btrd** [comment]
@jtledoux Ça devrait être réglé, n'hésite pas à me contacter à nouveau si tu vois des mails qui ne sont pas pris en compte.

**Comment by btrd** [comment]
Toujours des mails non pris en compte dans la boite de l'ANSSI.

Bouger les mails pris en compte mais où l'on n'est pas concerné (email non existant par exemple), mettre dans une boite d'archive.

**Comment by btrd** [comment]
@jtledoux Problème réglé ! Les mails sont passé automatique dans le dossier archive si ils ne nous concernent pas. J'ai corrigé un bug dans un cas particulier qui avais l'air de concerner qu'un seul mail actuellement.

Si jamais tu vois un mail dans la boite d'archive qui est censé nous concerner n'hésite pas à m'en faire part.
