### ISSUE TITLE
Front/ Cartouche "Nos dernières offres" : pb affichage 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#899]
En production, l'affichage du cartouche "nos dernières offres" est décalé et ne permet pas de visualiser correctement les offres. 

![Capture d’écran 2021-04-20 à 09 40 52](https://user-images.githubusercontent.com/51794334/115384396-473aab80-a1d7-11eb-801c-76a667e6cd49.png)

**Comment by Grainedepaillette** [comment]
@btrd Après test sur Mozilla et Chrome ce n'est toujours par opérationnel en production, je me permets de réouvrir le ticket. 
Merci.

**Comment by btrd** [comment]
Le ticket se ferme automatiquement quand je déploie en staging, j'ai pas voulu déployé hier soir je le fais ce matin.

**Comment by Grainedepaillette** [comment]
@btrd D'accord, au temps pour moi. Merci
