### ISSUE TITLE
Front/ Filtre "Publication" : afficher les offres entre la date sélectionnée et la date d'aujourd'hui

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#903]
**Règles associées au filtre** 
- La date sélectionnée permet d'afficher la liste des offres publiées entre cette date et aujourd'hui 

**Comportements constatés** (en PROD): 
- La sélection d'une date postérieure à une autre entraine une liste plus longue d'offre  

<img width="1439" alt="Capture d’écran 2021-04-21 à 10 16 00" src="https://user-images.githubusercontent.com/58481185/115520916-ecfb2280-a28a-11eb-98b6-788e5f9589d7.png">
<img width="1439" alt="Capture d’écran 2021-04-21 à 10 16 31" src="https://user-images.githubusercontent.com/58481185/115520953-f5535d80-a28a-11eb-8265-23d0dc2fe243.png">

- La sélection d'une date future affiche une liste 
<img width="1440" alt="Capture d’écran 2021-04-21 à 10 22 18" src="https://user-images.githubusercontent.com/58481185/115521655-a5c16180-a28b-11eb-95ab-4b56b9cb6445.png">

**Comportements souhaités** : 
- La sélection d'une date permet d'afficher toutes les offres publiées entre cette date et aujourd'hui 
- Empêcher la sélection d'une date future sur le calendrier

**Comment by Grainedepaillette** [comment]
>Comportements constatés (en PROD):
La sélection d'une date postérieure à une autre entraine une liste plus longue d'offre

@mch2608 Pourrais-tu reformuler ? Tu parle bien du cas où lorsqu'on saisit une date de publication, le filtre n'est pas totalement pris en compte dans les résultats de la recherche, ce qui explique que des offres antérieures ou postérieurs à la date indiqué par le candidat dans les filtres, apparaissent dans les résultats ? Merci

**Comment by mch2608** [comment]
**Règles associées au filtre** : La date de publication sélectionnée doit permettre d'afficher la liste des offres publiées entre cette date et aujourd'hui comme résultat de recherche.

**Comportements constatés** : 
- Lorsque candidat saisit une date de publication pour filtre, les résultats de la recherche proposent les offres publiées entre le début de la plateforme et la date sélectionnée.  Ce qui explique que la sélection d'une date postérieure à une autre date affiche une liste d'offre plus longue comme résultat et que la sélection d'une date future permet d'afficher une liste d'offre comme résultat. 

**Comportements souhaités** : 
- La sélection d'une date permet d'afficher toutes les offres publiées entre cette date et aujourd'hui
- Empêcher la sélection d'une date future sur le calendrier

**Comment by btrd** [comment]
C'est corrigé (en staging directement) je renvoyais la liste des offres publiés avant la date et non pas après.

**Comment by Grainedepaillette** [comment]
@btrd Opérationnel en pré-production.
