### ISSUE TITLE
Front/ Espace candidat : Pouvoir téléverser une PJ par le "glisser/déposer" 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#904]
Test réalisé en pré-prod et en prod

Comportement constaté : Lorsqu'un candidat dépose une PJ par le "glisser/déposer" sur l'espace dédié au dépôt de document, une page affichant le document s'ouvre. La PJ n'est pas effectivement télé-versée dans l'emplacement prévu et donc non enregistrée dans l'espace candidat. 

https://user-images.githubusercontent.com/58481185/115525708-9fcd7f80-a28f-11eb-827f-acc2c16ab157.mov

Comportement souhaité : Pouvoir télé-verser une PJ par "glisser/déposer" sans entrainer l'ouverture d'un nouvelle page hors outil.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr921.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Testé, ça fonctionne !
