### ISSUE TITLE
Back/Formulaire offres : appliquer les règles de saisie seulement aux offres actives

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#905]
Règles de saisie actuelles : 
- Obligation de saisie de la mention "F/H" avant publication 
- Limitation de caractères sur les champs 

Comportements constatés : 
- Lorsque un employeur souhaite désarchiver une offre qui ne respecte pas la règle de la mention "F/H", le désarchivage est impossible. Il est demandé à l'employeur de modifier le titre pour ajouter la mention. Or, il n'est pas possible de modifier ce champ sur une offre archivée. 

https://user-images.githubusercontent.com/58481185/115529626-5848f280-a293-11eb-95f9-9c47c8633bcf.mov

Comportements souhaités : 
- Etant possible de modifier une offre en brouillon, appliquer les règles de restrictions de saisie sur les champs qu'aux offres actives. En effet, une offre désarchivée devient une offre brouillon. Ainsi la modification du titre sera possible avant la publication.

**Comment by btrd** [comment]
Si on laisse l'utilisateur désarchivé l'offre sans ajouté H/F ça veut dire que l'offre est en brouillon mais non valide. Ce qui peut poser des problèmes dans certains cas, par exemple le système ne pourra pas modifier l'offre car elle est non valide.

Est-ce qu'il y a encore beaucoup d'offres où H/F manque ? Je peux les modifier de mon côté, ce sera au final plus simple

**Comment by Grainedepaillette** [comment]
@btrd C'est ok pour moi

**Comment by btrd** [comment]
C'est effectué

**Comment by Grainedepaillette** [comment]
@btrd Top, merci
