### ISSUE TITLE
Formulaire de candidature : modifications à apporter suite à ajout données 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#907]
@btrd Après test du formulaire de candidature en staging, c'est opérationnel. Quelques modifications à apporter notamment sur l'ordonnancement des données : 

### **1ère PARTIE : Vos informations** 
- Remplacer l'intitulé "Informations générales par "Vos informations" 

--> Cette partie doit comprendre : 

**a) Civilité** 
- Remplacer l'intitulé "Genre" par "Civilité" 
- Rendre obligatoire pour soumission du formulaire 

**b) Prénom** 
**c) Nom** 
**d) Poste actuel** 
**e) Tél. 
f) Photo 
g) CV
h) LM 
i) Disponibilité** 
**j) Niveau d’études**
- Rendre obligatoire 

**k) Expérience** 

**l) Expérience antérieure au sein du Ministère des Armées** 
- Remplacer l'intitulé "Expérience MINARM" par "Expérience antérieure au sein du Ministère des Armées" 

**--> En complément, supprimer la tranche d’âge**

### **3ème PARTIE :  Votre création de compte **

**Comment by Grainedepaillette** [comment]
Est-il possible que les données soient enregistrées et automatiquement incrémentées lors de nouvelles candidatures lorsque le compte candidat est actif/ connecté ?

**Comment by btrd** [comment]
Je te propose une autre organisation qui correspond mieux à comment sont organisés les données.

```
Partie 1: Vos informations
- Prénom
- Nom
- Poste actuel
- Tél.
- Photo
Partie 2: Votre profil
- Civilité
- Disponibilité
- Niveau d’études
- Expérience
- Expérience antérieure au sein du Ministère des Armées
- CV
- LM
Partie 3: Votre présence sur Internet
Partie 4: Votre création de compte
```
Ça va correspondre à ce que la personne va retrouver dans la page "Mes informations" dans son compte et "Mon profil" sur les offres auxquelles il a postulé.

> Est-il possible que les données soient enregistrées et qu'elles remplissent automatiquement les champs lors de nouvelles candidatures lorsque le compte candidat est actif/ connecté ?

C'est le cas (je viens de tester).

**Comment by Grainedepaillette** [comment]
@btrd Ta proposition me convient ! C'est le positionnement de la donnée civilité qui peut surprendre car elle correspond à la déclinaison de l'identité du candidat et donc selon moi plus à la partie "vos informations". Si on la déplace dans la partie vos informations, cela devient forcément une donnée rattachée à l'utilisateur ? 

> Est-il possible que les données soient enregistrées et qu'elles remplissent automatiquement les champs lors de nouvelles candidatures lorsque le compte candidat est actif/ connecté ?

> C'est le cas (je viens de tester).

C'est noté, merci.

**Comment by btrd** [comment]
Changements effectués

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel en staging ! Merci.
