### ISSUE TITLE
Création fonctionnalité candidature spontannée

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#923]
Tickets de spécifications
#956
#958
#959
#960
#961
#962

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr975.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Voici les modifications à apporter : 
- **Onglet "Candidature spontanée"/Formulaire de candidature :** retirer les "S" à "Domaine" et professionnel" 
- **Onglet "Candidature spontanée"/Formulaire de candidature :** au niveau de la partie "vos documents" : l'emplacement pour déposer le CV n'apparaît pas (cf. écran). 
![Capture d’écran 2021-06-06 à 21.33.12.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/3b319aa6-1e5b-4882-b301-e6908a3966e7)
- Courriel automatique reçu par le candidat : dans l'intitulé et le corps du courriel il apparaît la mention "offre" + la référence de l'offre (cf. écran)![Capture d’écran 2021-06-06 à 21.42.26.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/73a772a4-6130-434a-a8ee-4718b79c1e12)
 Il faudrait qu'apparaisse seulement la mention : 
- pour l'intitulé  **" Votre candidature  spontanée sur Civils de la Défense "** 
- pour le corps du courriel : **"Nous avons bien reçu votre candidature spontanée"**

**Comment by btrd** [comment]
1. Retiré
2. Il faut aller dans la partie admin pour configurer les documents par défaut
3. C'est fait

**Comment by Grainedepaillette** [comment]
@btrd Testé, c'est opérationnel !
