### ISSUE TITLE
Page d'accueil : intégrer un bouton pour renvoi vers questionnaire en ligne 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#925]

**Comment by btrd** [comment]
@Grainedepaillette J'ai besoin de plus de spécifications pour ce ticket

**Comment by Grainedepaillette** [comment]
@btrd J'attends toujours la confirmation du métier pour spécifier le ticket. 

Globalement : 
Il s'agira d'avoir un ou plusieurs boutons à un ou plusieurs endroits en front office (pour l'instant 2 endroits identifiés : le footer de la page d'accueil à côté des réseaux sociaux et l'espace candidat au niveau de la colonne où l'on retrouve l'ensemble des onglets. 

Ces boutons devront être paramétrables par le RF en back office : 
- le nombre de boutons 
- l'intitulé de chaque bouton 
- le lien URL pour chaque bouton

**Comment by Grainedepaillette** [comment]
@btrd Voici les spécifications suite au retour du métier : 

Le candidat doit pouvoir à partir de son espace candidat accéder à des questionnaires de satisfaction (crées et accessibles sur l'outil Mediatec-CX) : s'il souhaite répondre, il doit cliquer sur l'un des boutons disponibles et sera redirigé vers le questionnaire en ligne. 

Il s'agira d'avoir un ou plusieurs boutons au niveau de l'espace candidat au dessous des onglets mes candidatures/informations/compte (cf. écran). 

Ces boutons devront être paramétrables par le RF en back office :
- le nombre de boutons
- l'intitulé de chaque bouton
- le lien URL pour chaque bouton

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1088.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Fonctionnalité opérationnelle. Merci. 
Quelques remarques : 
- En front : Dans l'environnement, il n'y a pas l'onglet "Mon compte" dans l'espace candidat. Est-ce que c'est normal ? 
- En back : on pourrait modifier "menu compte candidat" par "Onglet espace candidat". 
- En back : on pourrait positionner ce paramètre dans la partie "Configuration" des paramètres.

**Comment by btrd** [comment]
C'est modifié !

**Comment by mch2608** [comment]
Tout est correct merci !
