### ISSUE TITLE
Réponse un message d'erreur en cas de non prise en compte d'un message

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#943]

**Comment by btrd** [comment]
@Grainedepaillette J'ai besoin de plus de spécifications pour ce ticket

**Comment by Grainedepaillette** [comment]
@btrd 

Situation de départ : lorsque le recruteur envoie un courriel au candidat, le candidat reçoit le courriel dans son espace candidat et sur sa messagerie personnelle. 

Problème constaté : les candidats ont tendance à répondre aux courriels reçus par le recruteur directement depuis leurs messageries personnelles de la façon suivante : clic sur bouton "répondre" et donc envoi du courriel à l'adresse rejoindre@contractuels-civilsdeladefense.fr

Le courriel se perd donc. Aujourd'hui un message est affiché en bas de page du courriel indiquant à l'utilisateur de répondre en cliquant sur le lien le redirigeant vers son espace candidat/ onglet courriel. 

**Message "no reply"** 
Afin de renforcer l'information et diminuer aux maximum les risques de perte, l'objectif est de pouvoir afficher la mention no reply en entête (dans le courriel mais peut être est-ce lourd à configurer) ou tout simplement par défaut dans l'intutlé de l'objet du courriel. 
exemple : 

![Capture d’écran 2021-07-08 à 11.14.30.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/647e012c-5fe9-4681-9023-7ed0828c36a7)
![Capture d’écran 2021-07-08 à 11.15.00.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/ec2f97c5-351f-40e6-a773-918826b472f6)
**Message d'erreur** 
2ème niveau de "blocage" : lorsqu'un candidat envoie effectivement un courriel de réponse sur l'adresse rejoindre@contractuels-civilsdeladefense.fr ; envoyer un message d'erreur au candidat afin qu'il soit informé que le courriel n'a effectivement pas été transmis.

**Comment by btrd** [comment]
Règles :

- Si email valide (c'est à dire que j'ai pu intégrer l'email dans la plateforme) alors je met l'email dans la poubelle
- Si email invalide alors j'envoie un email à la personne à l'origine du mail invalide pour lui dire de passer directement par la plateforme puis je met l'email dans la poubelle

@Grainedepaillette tu confirmes les règles ?

**Comment by Grainedepaillette** [comment]
@btrd Je confirme les hypothèses. 

En revanche après test sur l'environnement sur Mozilla,  le candidat qui répond directement au courriel reçu depuis sa messagerie MAIS à la mauvaise adresse mail (cf. écran) ne reçoit pas de message d'erreur (7min après envoi du courriel par le candidat, aucun courriel reçu dans la messagerie personnelle y compris dans les spams). 

![image.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/718169f8-997c-4665-bcfe-b704179a1d26)

**Comment by btrd** [comment]
En staging actuellement on utilise l'ancien système avec une adresse OVH et pas Gandi qui est nécessaire pour le nouveau système. Ça va du coup être compliqué de tester dans les mêmes conditions.

Si tu peux me fournir une adresse Gandi pour tester ce serait le mieux si tu veux tester la fonctionnalité en entier.

**Comment by Grainedepaillette** [comment]
@btrd 

> Si tu peux me fournir une adresse Gandi pour tester ce serait le mieux si tu veux tester la fonctionnalité en entier.

Je ne suis pas sûre d'avoir compris, Tu veux dire un compte candidat en production, qui reçoit des courriels en provenance de rejoindre@contractuels-civilsdeladefense.fr et qui sont visibles sur Gandi ?

**Comment by btrd** [comment]
En production on utilise l'email rejoindre@contractuels-civilsdeladefense.fr, il me faut une autre adresse mail géré par Gandi pour la staging (pour ne pas utiliser l'adresse de prod en staging).

Par exemple staging@contractuels-civilsdeladefense.fr

**Comment by Grainedepaillette** [comment]
J'ai cherché sur l'outil Gandi mais je ne vois pas de fonctionnalité permettant la création d'un nouvelle adresse. As-tu des pistes ?

**Comment by Grainedepaillette** [comment]
Attente lundi 26.07 retour agents fabnum ayant accès admin à Gandi.

**Comment by Grainedepaillette** [comment]
Relance faite auprès de la FabNum le 26.07 via Mattermost. 
Si absence de réponse, déployer en production avant le 31.07 et tester en production la réception du message d'erreur par le candidat sur sa messagerie personnelle.

**Comment by btrd** [comment]
J'ai reçu les informations de la Fabnum :)

**Comment by btrd** [comment]
@Grainedepaillette @mch2608 c'est opérationnel sur https://erecrutement-cvd-staging-pr1054.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
J'ai testé, c'est opérationnel. 

Comportement constaté : lorsque le candidat envoie un courriel, l'historique des échanges recense "un courriel automatique a été envoyé à PRENOM NOM" 
En back 

<img width="1440" alt="Capture d’écran 2021-07-27 à 15 05 11" src="https://user-images.githubusercontent.com/58481185/127158396-0598136d-4557-44c5-8256-688e20cbdeea.png">

En front 

<img width="1440" alt="Capture d’écran 2021-07-27 à 15 07 19" src="https://user-images.githubusercontent.com/58481185/127158716-1aa9d4e3-4495-41be-bee3-4cd7eb096f85.png">


Comportement souhaité : Afficher "PRENOM NOM a envoyé un courriel " (cf staging ci-dessous) 

BACK 

<img width="1440" alt="Capture d’écran 2021-07-27 à 15 06 43" src="https://user-images.githubusercontent.com/58481185/127158608-bf75cdc4-27cb-4a99-aaaf-9d27992f9112.png">

FRONT 

<img width="1440" alt="Capture d’écran 2021-07-27 à 15 08 21" src="https://user-images.githubusercontent.com/58481185/127158809-eb11d924-6c86-488f-8086-7f3f0394e91a.png">

**Comment by btrd** [comment]
Je suis pas sûr de comprendre le soucis, c'est possible de faire un nouveau ticket si ce n'est pas lié à ce ticket ?

**Comment by mch2608** [comment]
Le problème est lié à l'environnement de ce ticket puisqu'on ne rencontre pas le problème en staging.

**Comment by btrd** [comment]
Je viens de tester et je n'ai pas eu ce soucis, est-ce que tu arrives à reproduire ?

**Comment by mch2608** [comment]
https://user-images.githubusercontent.com/58481185/127307635-4f34a473-267b-4ec1-928c-4dd7f89b2286.mov


https://user-images.githubusercontent.com/58481185/127307717-de657225-65d1-4da5-884c-b1e98be0ed10.mov

**Comment by btrd** [comment]
Je viens de comprendre pourquoi, tu es inscrit sur CVD avec l'adresse `mch260898+candidat1304bis@gmail.com` sauf que quand tu envois un message sur la plateforme c'est avec l'adresse `mch260898@gmail.com` du coup je ne retrouve pas de compte associé.

C'est possible de corriger mais ça peut impliquer des soucis de sécurité, à discuter ensemble pour voir ce qu'on veut faire. 

Ce n'est par contre pas un soucis lié à ce développement, ça existe aussi en staging et prod. Si c'est ok pour toi on peut donc clôturer ce ticket.

**Comment by mch2608** [comment]
J'ai testé en m'inscrivant avec l'adresse mch260898@gmail.com et le problème n'apparait pas. 
Je pense que le cas est relativement minime et ne posera pas de grand problème. J'ouvre un ticket propre au problème  pour le MCO.
