### ISSUE TITLE
Gandi/Transférer les courriels "Archive" vers boîte fonctionnelle minArm 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#944]
Boîte fonctionnelle minArm : drh-md-srhc-civilsdeladefense.charge-qualite.fct@intradef.gouv.fr

**Comment by btrd** [comment]
À annuler

**Comment by Grainedepaillette** [comment]
@btrd Cf. le #943 qui répond au besoin a priori
