### ISSUE TITLE
Back/Offres : intégrer les statistiques dans l'export des données d'une offre 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#945]
**Comportement actuel :** 
Aujourd'hui, l'export des données relatives à une offre ne prend pas en compte les données statistiques relatives à l'offre. #916 

**Comportement souhaité :** 
Ajouter les données statistiques de l'offre (données présentes sur l'onglet "statistiques" d'une offre) dans l'export.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1019.osc-fr1.scalingo.io/

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel (clic bouton + export) Mais lorsque l'on applique les filtres "domaine pro" ; "contrat"; "BOP", il n'apparaissent pas dans l'export, alors que côté chiffres, les résultats affichés (correspondant aux filtres appliqués) apparaissent bien.

**Comment by btrd** [comment]
Effectivement c'était pas prévu, je dois le rajouter ?

**Comment by Grainedepaillette** [comment]
@btrd Dans le document excel, la ligne filtres choisis suggéraient de faire apparaître les filtres effectivement choisis dans l'outil mais peut être que cela n'était pas assez spécifié. 

Il faudrait que ce soit le cas pour tous les exports statistiques "offres et candidats".

**Comment by btrd** [comment]
Normalement c'est le cas pour les autres exports.

Je vais juste rouvrir ce ticket.

**Comment by Grainedepaillette** [comment]
@btrd Je confirme pour les statistiques candidatures, on visualise bien les intitulés des filtres appliqués dans l'export CSV :)

**Comment by Grainedepaillette** [comment]
@btrd le staging est down pour ce qui est de l'onglet statistiques offres ; je réouvre le ticket au cas où en attente de ta confirmation. 

![Capture d’écran 2021-07-08 à 21.45.54.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/8e225849-1e06-4bb9-8938-647b3aa42298)
