### ISSUE TITLE
Front / formulaire candidature : ajouter champ "Domaine professionnel" 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#958]
Comportement constaté : lorsque candidat dépose sa candidature spontanée, elle bascule dans le vivier, l'employeur n'a pas la possibilité de trier parmi le vivier les candidatures spontanées ainsi que le champ de recherche du candidat. 

Comportement souhaité : demander le "Domaine professionnel" recherché par le candidat dans le formulaire de candidature

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr975.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Je ne vois pas le champ "Domaine professionnel" sur cet environnement @btrd

**Comment by Grainedepaillette** [comment]
@btrd serait-il possible d'étendre cette option aux formulaires de candidature à une offre d'emploi ? De sorte à pouvoir filtrer l'ensemble du vivier par domaine professionnel et avoir des cartes candidats au même niveau d'information. 

Si nécessaire, j'ouvre un nouveau ticket.

**Comment by btrd** [comment]
Je ne suis pas sûr de comprendre la demande, du coup je veux bien un nouveau ticket pour en discuter.

**Comment by Grainedepaillette** [comment]
C'est fait, ticket #1012 ouvert
