### ISSUE TITLE
Back/Vivier : ajouter filtre "Domaine professionnel" 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#959]
Comportement constaté : lorsque candidat dépose sa candidature spontanée, elle bascule dans le vivier, l'employeur n'a pas la possibilité de trier parmi le vivier les candidatures spontanées ainsi que le champ de recherche du candidat. 

Comportement souhaité : l'information étant fourni dans le formulaire de candidature, ajouter le filtre "Domaine professionnel" dans le vivier afin que les employeurs puissent rechercher les candidats en fonction de leur domaine professionnel.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr975.osc-fr1.scalingo.io
