### ISSUE TITLE
Front/ formulaire de candidature : Retirer la LM lorsqu'il s'agit du formulaire de candidature spontanée

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#960]
Comportement constaté:  Lorsqu'un candidat souhaite postuler à une offre, il est obligatoire de fournir une lettre de motivation dans le formulaire de candidature pour pouvoir envoyer sa candidature à l'offre. 
 
Comportement souhaité : Lorsque le candidat postule à l'offre "CANDIDATURE SPONTANÉE F/H" (https://contractuels.civils.defense.gouv.fr/offresdemploi/candidature-spontanee-f-h), la lettre de motivation ne doit pas lui être demandée. Le champ "Lettre de motivation" de la rubrique "Vos documents" doit ainsi être supprimé du formulaire de candidature associé à l'offre "CANDIDATURE SPONTANÉE F/H".

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr975.osc-fr1.scalingo.io

**Comment by mch2608** [comment]
Après vérification, le CV aussi a été supprimé. Seule la lettre de motivation doit être supprimée dans la partie "Vos documents" du formulaire de candidature pour une candidature spontanée. 

https://user-images.githubusercontent.com/58481185/119831298-70004000-befd-11eb-963f-c8d36bfcd75b.mov

**Comment by btrd** [comment]
@mch2608 Il faut configurer dans la partie admin les documents nécessaires ou non
