### ISSUE TITLE
Back/Vivier : ajouter l'état "Candidature spontanée" au filtre "Etat de candidature" 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#962]
Comportement souhaité : sur le vivier, les employeurs pourront sélectionner le filtre "Etat de candidature" et sélectionner "Candidature spontanée" pour obtenir tous les candidats ayant déposé une candidature sur l'offre "CANDIDATURE SPONTANEE F/H" (https://contractuels.civils.defense.gouv.fr/offresdemploi/candidature-spontanee-f-h)

**Comment by btrd** [comment]
Les données `état de candidature` et `candidature spontanée` n'ayant pas de lien entre elles, je propose de faire un filtre à part

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr975.osc-fr1.scalingo.io
