### ISSUE TITLE
Carte candidat : faire instantanément apparaitre la coche verte après sélection d'un motif de refus

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#964]
Comportement constaté : 
1 - Lorsqu'on sélectionne un état de candidature parmi "Refusé(e)", "Refusé(e) après entretien téléphonique", "Rencontré(e) mais refusé(e)", le champ "Choisissez un motif de refus" apparait instantanément. 
2 - Lorsqu'on sélectionne un motif de refus, le message "Profil mis à jour" apparait en bas de page mais la coche verte n'apparaît pas au niveau du motif de refus
3 - Après actualisation ou changement d'onglet, la coche verte apparaît bien et le motif de refus est bien enregistré 

Problème : La coche verte est le signe qui sert de confirmation pour les employeurs et il n'est pas instinctif d'actualiser la page

Comportement souhaité : 
1- Lorsqu'on sélectionne l'un des états parmi "Refusé(e)", "Refusé(e) après entretien téléphonique", "Rencontré(e) mais refusé(e)", le champ "Choisissez un motif de refus" apparait instantanément. 
2 - Lorsqu'on sélectionne un motif de refus, le message "Profil mis à jour" apparait en bas de page et la coche verte apparaît instantanément au niveau du motif de refus 

https://user-images.githubusercontent.com/58481185/118795769-3a26e000-b89b-11eb-89ee-d8ab0179135d.mov

**Comment by btrd** [comment]
Disponible
