### ISSUE TITLE
augmenter nombre de champs recupéres en cas de rejet action "postuler"

### ISSUE THREAD

**Issue by Halfton4** [betagouv/civilsdeladefense#97]
Il faudrait avoir davantage de champs recuperés au delà des nom prenom en cas de refus de l'action "postuler" pour une candidature cause incomplète. Conserver tous les champs sauf les incorrects/vides.

**Comment by yannski** [comment]
Comment reproduire le problème ? De mon côté cela fonctionne correctement.

**Comment by yannski** [comment]
Capture + conditions pour reproduire + version du navigateur

**Comment by yannski** [comment]
OK, j'ai compris ce ticket :)

**Comment by yannski** [comment]
Stocker toutes les informations d'une candidature dans le compte du candidat afin de les réutiliser pour une prochaine candidature. Lors de la réutilisation, la LM et le CV sont prépositionnés mais le candidat doit pouvoir en uploader de nouvelles.
