### ISSUE TITLE
Front/page accueil : partie témoignage est visible sans qu'il y ait les infos 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#985]
Testé en PROD : 

Comportement constaté : aujourd'hui alors même que toutes les informations relatives à la partie témoignage ne sont pas renseignées en back/paramètres, la partie est affichée en front office/page d'accueil. 

Comportement souhaité : si toutes les informations ne sont pas renseignées en back/paramètres/partie témoignage ALORS, la partie ne doit pas être visible en front.

**Comment by btrd** [comment]
Ça a été corrigé mais pas encore déployé, je fais ça dans la semaine !

**Comment by Grainedepaillette** [comment]
@btrd j'ai checké staging et la prod, l'affichage partielle est toujours présent (cf. écrans). 

![Capture d’écran 2021-06-16 à 16.07.39.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/9b015035-a2d5-4afb-8d8a-30d1d1f11590)

![Capture d’écran 2021-06-16 à 16.08.06.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/5c56544c-bf87-423a-8d2b-9fd922c6b604)

**Comment by btrd** [comment]
Ça a été corrigé en même temps que la FAQ du coup disponible ici https://erecrutement-cvd-staging-pr968.osc-fr1.scalingo.io/

**Comment by Grainedepaillette** [comment]
@btrd C'est okay, merci
