### ISSUE TITLE
Back/Paramètres/ partie témoignage : bouton pour télé-versement image n'apparaît pas 

### ISSUE THREAD

**Issue by Grainedepaillette** [betagouv/civilsdeladefense#986]
Comportement constaté : lorsque l'utilisateur souhaite téléverser l'image qui correspondra à la partie témoignage métier en front/page d'accueil, il n'y a pas de bouton qui apparaît. En revanche lorsque l'on clique sur l'espace vide (en gris), l'action est bien pris en compte et on accède au bureau de notre PC pour téléverser une P.J (image) (cf. vidéo). https://images.zenhubusercontent.com/146276066/69e4f78f-f7b8-4402-bdb9-4ea322113378/image_te_moignage.mov

Comportement souhaité : ajoute un bouton pour télé-verser l'image.

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel en staging ! Est-ce qu'on pourrait avoir un bouton pour supprimer lesdites images. Car en l'état on ne peut seulement qu'écraser l'image précédente par une nouvelle image.

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1002.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd Lors d'un premier test, j'ai pu visualiser la coche "remove the picture" mais en effectuant un second test je ne l'ai plus vu et ne la vois actuellement plus l'environnement, as-tu modifié quelque chose ? 

Mon retour : cela fonctionne avec la coche : lorsque je téléverse une image et enregistre la modification de mes paramètres PUIS reviens et coche la case pour retirer l'image téléversée et enregistre la modification de mes paramètres, cela fonctionne MAIS le processus est relativement fastidieux. Ne pourrait-on pas supprimer l'image à l'aide d'un bouton ? Merci

**Comment by btrd** [comment]
C'est plus compliqué via un bouton, tu peux faire un ticket et voir si on a le temps à la fin du projet ?

> Lors d'un premier test, j'ai pu visualiser la coche "remove the picture" mais en effectuant un second test je ne l'ai plus vu et ne la vois actuellement plus l'environnement, as-tu modifié quelque chose ?

Si il n'y a pas d'image je cache la coche

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel. Est-ce que tu pourrais également ajouter la coche pour la partie "témoignage" ? (cf. écran) Pour que l'on puisse avoir la main sur les 2 parties de la home page où il y a des images. 

![Capture d’écran 2021-06-30 à 12.30.26.png](https://images.zenhubusercontent.com/606dc7d974e7c82154831f4d/d25841cb-a679-4dc9-97e3-963051ca0b9b)

Merci.

**Comment by btrd** [comment]
La coche est affiché si une image a été uploadé

**Comment by mch2608** [comment]
Après test sur l'environnement : la coche n'apparait pas sur la partie "témoignages", et ce, même après upload d'une image

**Comment by btrd** [comment]
C'est corrigé
