### ISSUE TITLE
Back / Statistiques offres : pouvoir exporter les données 

### ISSUE THREAD

**Issue by mch2608** [betagouv/civilsdeladefense#996]
Comportements souhaités : 
- Création du bouton "Exporter" en bas de page à droite (comme pour la page offre et vivier) 
- Données à apparaître sur fichier CSV envoyées par @Grainedepaillette sur Zen et Mattermost

**Comment by Grainedepaillette** [comment]
@mch2608 merci pour la création !

**Comment by btrd** [comment]
Disponible https://erecrutement-cvd-staging-pr1019.osc-fr1.scalingo.io

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel au niveau de l'export. Pourrais-tu déplacer le bouton et le positionner en bas de page à droite comme sur les autres pages/onglets de l'outil pour la même fonctionnalité ? Merci.

**Comment by btrd** [comment]
Corrigé !
